### ISSUE TITLE
Could not pass event IslandWorthUpdateEvent

### ISSUE THREAD

**Issue by jack201819** [BG-Software-LLC/SuperiorSkyblock2#552] opened 2021-08-30 17:05 UTC
### Minecraft's Version

This server is running Paper version git-Paper-787 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-786 (MC: 1.16.5)

### Plugin's Version

SuperiorSkyblock2-b274(1).jar

### Describe the bug

java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget from class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator (org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @505812fe; org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator is in unnamed module of loader com.bgsoftware.superiorskyblock.modules.ModuleClassLoader @48c587b) at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.createJumpTarget(LocalVariableTypesCalculator.java:419) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.getOrCreateJumpTarget(LocalVariableTypesCalculator.java:1196) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1234) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1230) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:457) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:461) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpressionOnEmptyStack(LocalVariableTypesCalculator.java:598) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterExpressionStatement(LocalVariableTypesCalculator.java:580) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.CompilationPhase$LocalVariableTypeCalculationPhase.transform(CompilationPhase.java:277) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1528) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
30.08 16:56:01 [Server] INFO at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
30.08 16:56:01 [Server] INFO at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:204) ~[?:?]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:190) ~[?:?]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:186) ~[?:?]
30.08 16:56:01 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor507.execute(Unknown Source) ~[?:?]
30.08 16:56:01 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandWorthUpdateEvent(EventsCaller.java:174) ~[?:?]
30.08 16:56:01 [Server] INFO at com.bgsoftware.superiorskyblock.island.SIsland.lambda$saveBlockCounts$62(SIsland.java:1882) ~[?:?]
30.08 16:56:01 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-787]
30.08 16:56:01 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
30.08 16:56:01 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
30.08 16:56:01 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

None

### Additional Information

![Error](https://user-images.githubusercontent.com/89706117/131377058-e0acec97-3be6-4007-9178-b726d7095932.png)

**Comment by OmerBenGera** [comment] 2021-08-30 17:34
Duplicate of #371

**Closed by OmerBenGera** 2021-08-30 17:34 UTC
Labels: Pending
