### ISSUE TITLE
Received an unexpected error while taking a snapshot

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/SuperiorSkyblock2#1951] opened 2023-12-30 16:22 UTC
### Minecraft's Version

git-Pufferfish-27 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-2023.3-b124.jar

### Describe the bug

when I give /is level, it says an error that I have to contact the server administrator, I don't know why this is happening

error: https://mclo.gs/fs7bq7C

### To Reproduce

/is level

**Comment by SrMonsterYT** [comment] 2024-01-12 19:52
> I cannot seem to replicate the issue myself. Are you able to replicate it on a server running Pufferfish that only has SuperiorSkyblock and WildStacker installed?
> 
> Also, what Java version do you use?

java 17

**Comment by OmerBenGera** [comment] 2024-01-20 13:59
Duplicate of #1931

**Closed by OmerBenGera** 2024-01-20 13:59 UTC
Labels: ❌ Unconfirmed
