### ISSUE TITLE
Bug with island permission

### ISSUE THREAD

**Issue by shika258** [BG-Software-LLC/SuperiorSkyblock2#1031] opened 2022-04-03 16:10 UTC
### Minecraft's Version

1.8.8

### Plugin's Version

last

### Describe the bug

Hello, I am contacting you because I have a problem on my server with the permissions, in order to avoid lags as we host 250 players permanently on the same machine, we restart the server every 4 hours and some players are complaining that the permissions they set default after a restart, can you please help me to solve this problem
i talk about these:
https://pastebin.com/TCZ1t3PA

the permissions that players assign to their members in the /is cp
Sincerely.

### To Reproduce

when you restart the server

**Comment by OmerBenGera** [comment] 2022-04-03 17:24
Duplicate of #831

**Closed by OmerBenGera** 2022-04-03 17:24 UTC
Labels: Pending
