### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by HWSCrew** [BG-Software-LLC/SuperiorSkyblock2#1917] opened 2023-11-14 14:33 UTC
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3

### Describe the bug

Bug 1:
For a few days now, my island value and level have been going down very quickly when I leave my island and go to the farm world or the admin shop, for example. Both values don't just go down a little but go well into the millions. But whenever I restart the server everything goes back to normal, at least as long as I'm on my island.

Bug 2:
My hopper upgrades are gone and i have a unlimited amount of hoppers that i can use on my island.
![2023-11-14_15 27 56](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/58859848/7606bed5-7080-48ec-90b6-526f473ec0e3)

Bug 3:
I got a big warn message in my log files:
![Code_t1OQ5zreDz](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/58859848/9d1aaab9-079a-448e-b517-6e025c00e39e)

### To Reproduce

I don't know? 1&2 came random. The Plugin worked fine for months.

### Additional Information

![Code_t1OQ5zreDz](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/58859848/3bb37be0-1d40-42e8-9c56-6e4620e203aa)
![2023-11-14_15 27 56](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/58859848/11dbf089-38d2-4f5f-8815-a19412760b53)

**Comment by OmerBenGera** [comment] 2023-11-17 16:23
Bug 1 -
Seems like you have blocks being broken on your island. Run `/is admin debug block_break` to find out which blocks exactly are broken on your island.

Bug 2 -
Make sure your configuration file is correct. Look for warnings in console as well.

Bug 3 -
You are missing a SlimeWorldManager plugin, therefore the SlimeWorlds module cannot work.

What I don't understand in this report is how anything worked before, as you have the SlimeWorlds module without a SlimeWorldManager plugin, which means it never worked - is this intended?

**Comment by HWSCrew** [comment] 2023-11-17 17:26
Bug 1:
I've run the Command and the console was full with this:
  [Fr. 18:19:01 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:02 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:07 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:08 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:23 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:24 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:25 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:30 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {HOPPER:0} {1}
  [Fr. 18:19:42 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:44 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  [Fr. 18:19:45 INFO  com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin] [SuperiorSkyblock2] DefaultIslandBlocksTrackerAlgorithm::untrackBlock {crepisteve} {WHEAT:7} {1}
  
  Bug 2:
  The only error with SSB ist the one on the screen shot in my original message
  
Bug 3:
We have Slime Worlds installed. Did i put the .jar in the wrong place?
![WinSCP_VhSy2YI3Hd](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/58859848/cb2e2453-aac1-439b-b27e-491e1350960e)

**Comment by OmerBenGera** [comment] 2023-11-24 16:43
Bug 1:
You see what block is broken which causes your island worth to go down, it is wheat.
This is not a bug.

Bug 2:
There is, you just missed it. There's a warning or an error in console regarding the missing upgrade.
Check your configuration and look for console messages when the plugin loads.
If you need help with that, ask on the discord server for help.

Bug 3:
You need to install a SlimeWorlds plugin, the module has nothing to do with that.

I am closing this for now, as there's no actual bug reported in here.
For support, ask on the discord for help.

**Closed by OmerBenGera** 2023-11-24 16:43 UTC
Labels: 📝 Missing information, ❌ Unconfirmed
