### ISSUE TITLE
Problem with /is level

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/SuperiorSkyblock2#485] opened 2021-08-18 18:43 UTC
### Minecraft's Version

paper 1.8.8

### Plugin's Version

Last dev version b239

### Describe the bug

Hello, I was looking the /is counts from my island, and I realized that there was much more level in /is counts than it showed me in the placeholders, that's why I decided to make /is level and the level dropped to 0, and went back up when I restarted the server. not only happens to me 
![image](https://user-images.githubusercontent.com/73038322/129967496-1f795314-3c8b-4255-8c7c-c8ce9528ce18.png)

### To Reproduce

Check /is counts, appears more level than in the placeholder
do /is level or /is recalc
the level and worth comes to 0
then restart the server and the issue is fixed, but if you try to put /is level again, the level got bugged, again

**Comment by CayeOficial** [comment] 2021-08-18 19:00
![image](https://user-images.githubusercontent.com/73038322/129956544-295b5b13-8969-4afd-8b72-49a2c11b7f44.png)
It comes negative value

**Comment by CayeOficial** [comment] 2021-08-18 20:29
I've saw in discord that there are another player with the same bug (1.17.1 and lastest dev version b239)
![image](https://user-images.githubusercontent.com/73038322/129967941-0f8aa706-5e4b-4760-a851-ddb1ed6c26e3.png)

**Comment by MineagePvP** [comment] 2021-08-19 13:22
This is the issue i was referring to but i wasn't sure if it's due to a restart omre but apparently this guy confirms it happened to him too so i guess you got 2 people with the same issue and no it's version dependent cause i'm on 1.8.8 and it's happening to me to this may be the main issue you need to fix to resolve mine

**Comment by MineagePvP** [comment] 2021-08-19 15:58
https://gyazo.com/c9d8d81b26fcaf8066eadde8989dbca2
https://gyazo.com/1b7146f83c536978e837dbfb0972b8ff

I also just noticed it does it even with defaults the plugin comes with and happens when you restart the server or randomly even when online and in the config i have schematic-offset: true

**Comment by MineagePvP** [comment] 2021-08-19 20:51
I've read the issues that are all open on github issues rn and apparently they are all issues that are happening to them, me and my friends whom run superiorskyblock as well

**Comment by OmerBenGera** [comment] 2021-08-20 10:13
I will look into that.
Not sure why it happens, as the counts and worth levels are co-responding to each other.
It shows negative values because you have a worth/level bonus to offset your schematic values to 0.

**Comment by OmerBenGera** [comment] 2021-08-20 13:08
> 
> 
> https://gyazo.com/c9d8d81b26fcaf8066eadde8989dbca2
> https://gyazo.com/1b7146f83c536978e837dbfb0972b8ff
> 
> I also just noticed it does it even with defaults the plugin comes with and happens when you restart the server or randomly even when online and in the config i have schematic-offset: true

Run /is admin show, show me the results of the command.

**Comment by MineagePvP** [comment] 2021-08-21 08:33
post a video of multiple issues all in that's also related to some of the tickets people made it's in one of the tickets

**Comment by OmerBenGera** [comment] 2021-08-21 09:02
I don't understand why are you fighting me instead of doing what I ask you to do.
I am trying to understand the issue, and the result of /is admin show will help me.
If you are not gonna help me to help you, I am just gonna close this ticket.

**Comment by MineagePvP** [comment] 2021-08-21 10:13
Well in the video i show the issues and how they happen, the /is counts, the /is values and the /is top and what's disabled and what's not and what all the issues are so no i'm not trying to fight you i'm just trying to make things simple for you

**Comment by OmerBenGera** [comment] 2021-08-21 11:50
> 
> 
> Well in the video i show the issues and how they happen, the /is counts, the /is values and the /is top and what's disabled and what's not and what all the issues are so no i'm not trying to fight you i'm just trying to make things simple for you and watching the video and listening to it you'll see my actions and what happens when i do what's specified i know it may be a lot people ask of you to do but just do this once for me please i do not mean to be mean or angry in any way i'm just better explaining and making actions in the video https://www.youtube.com/watch?v=CXglzFzCqj0&t=3s

That's a 5 minutes video, no way I am gonna watch the entire video.
Also, it seems like you mix a few issues in this video - don't do that. Open separate issues for each bug report, and don't mix them all in one video / issue.

**Comment by JamesSmily** [comment] 2021-08-21 12:23
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment] 2021-08-21 12:23
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment] 2021-08-21 12:26
If i don't get an unban i swear to you i will do this all day and if not come back and do it and if i get banned i'll make more accounts along with that tell my friends to do it as well you'll have 8 people doing it consecutively for 1 hour cause they will

**Comment by CayeOficial** [comment] 2021-08-21 12:36
Why you are fighting on my issue?
My issue was solved so please if you have another issue, open it on a separate ticket. Thanks.

**Comment by OmerBenGera** [comment] 2021-08-21 15:39
> 
> 
> Why you are fighting on my issue?
> My issue was solved so please if you have another issue, open it on a separate ticket. Thanks.

I reported his account, don't worry.
How was it solved?

**Comment by CayeOficial** [comment] 2021-08-21 18:27
I updated to the last dev version and the issue never appears more, but I will be pending if happens again.

**Comment by OmerBenGera** [comment] 2021-08-21 21:43
If it occurs again, make sure you let me know here

**Comment by CayeOficial** [comment] 2021-08-22 13:38
Happens again. Same description

**Comment by OmerBenGera** [comment] 2021-08-22 14:24
The issue is that /is level is not setting your worth to 0 (aka schematic is not offset), or that there are more levels in /is counts than your actual island level?

**Comment by OmerBenGera** [comment] 2021-08-25 14:46
?

**Comment by PhuongBlu** [comment] 2021-08-28 06:41
i have same error ? when i /island level all block in /is count have been reset and level of island is reset = 0 (aka turn off  negative  value island level)

**Comment by OmerBenGera** [comment] 2021-08-28 07:18
> i have same error ? when i /island level all block in /is count have been reset and level of island is reset = 0 (aka turn off negative value island level)

You have worth bonus tho which removes some counts from levels from your island

**Comment by OmerBenGera** [comment] 2021-08-28 07:19
I dont think there is an actual bug here, but more of a misunderstanding on how the plugin works and how schemarics offset work.
I am closing this, feel free to ask more questions here.

**Closed by OmerBenGera** 2021-08-28 07:19 UTC
Labels: Unconfirmed
