### ISSUE TITLE
Island warps not working

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1006] opened 2022-03-19 02:28 UTC
### Minecraft's Version

Paper version git-Paper-260 (MC: 1.18.2)

### Plugin's Version

558-562 (tested all of them)

### Describe the bug

When you try to use island warp teleport to any island, it will tell you that it couldnt find any safe location and you wont be teleported. Version 557 worked perfectly.

### To Reproduce

Create island warp and try to use it

**Comment by Davisiiiik** [comment] 2022-03-19 02:32
Maybe duplicate of #1004?

**Comment by OmerBenGera** [comment] 2022-03-19 07:56
Duplicate of #1004

**Closed by OmerBenGera** 2022-03-19 07:56 UTC
Labels: Pending
