### ISSUE TITLE
Island Worth/Counts Duplicating on restarts

### ISSUE THREAD

**Issue by MythricHD** [BG-Software-LLC/SuperiorSkyblock2#386] opened 2021-07-20 19:37 UTC
### Minecraft's Version

Paper 1.12.2

### Plugin's Version

b199

### Describe the bug

We've had this issue on and off for a few updates now where on restarts the spawner count and thus island worth gets duplicated on restart. I tested with the latest build of ss2 and ws but the issue is persistent. 

Image of issue: https://i.riftmc.co/xwRsg5btqS.png (as you can see there is only one spawner placed)

Doing /is admin recalc refreshes the count and corrects it but a restart will mess it up again

### To Reproduce

Config attached, You can take a look in the worth file to see how I have it set up but essentially just place down a spawner, restart the server and check your /is counts menu

[archive-2021-07-20T153449-0400.tar.gz](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6850821/archive-2021-07-20T153449-0400.tar.gz)

**Comment by OmerBenGera** [comment] 2021-07-30 17:02
I can't seem to replicate the issue, might be something with your worth file.
Mind uploading it to pastebin (I know you attached a zip file, I prefer to have it on pastebin)

**Comment by MythricHD** [comment] 2021-07-30 19:14
https://bin.bloom.host/isawejexeg

**Comment by OmerBenGera** [comment] 2021-07-31 09:45
it looks fine - do you have a limit or something for "MOB_SPAWNER" as a global block?

**Comment by MythricHD** [comment] 2021-08-03 23:58
Nope its worked before and i have never touched the file, it just stopped working within the last b196-199 updates that I noticed

**Comment by OmerBenGera** [comment] 2021-08-04 09:34
> Nope its worked before and i have never touched the file, it just stopped working within the last b196-199 updates that I noticed

I will look into that as soon as possible.

**Comment by WarnDangerous** [comment] 2021-08-13 22:27
I have the same issue since some month, but I don't know how to replicate the issue.

My player get for example 100 spawners, it counts as 200-250 spawners, using wildstacker as spawner provider on paper 1.12

**Comment by OmerBenGera** [comment] 2021-08-14 08:54
I can't seem to replicate the issue, mind sharing with me your files of SSB?

**Comment by MineagePvP** [comment] 2021-08-19 20:50
This happens on 1.8.8 too and it's random

**Comment by JamesSmily** [comment] 2021-08-21 12:28
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment] 2021-08-21 12:28
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment] 2021-08-21 12:28
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by DebuffPvP** [comment] 2021-08-31 06:04
yo the dude with the issue are you using shopguiplus by any chance for the worth of the spawners or doing it directly through superiorskyblock?

**Comment by MythricHD** [comment] 2021-08-31 15:09
I do use shopgui for players to obtain spawners

**Comment by OmerBenGera** [comment] 2021-08-31 15:21
> 
> 
> I do use shopgui for players to obtain spawners

We suspect that the issue is caused by integration with SSB and SGP.
The fact that you have it installed only increases the chance that the issue is due to that, and I am gonna check that out asap.

**Comment by OmerBenGera** [comment] 2021-09-05 06:32
Check out latest dev build, should be fixed.

**Comment by MythricHD** [comment] 2021-09-07 01:01
Seems like its fixed, /is admin recalc seems to be broken in b295 but I can open a new ticket for that if desired

**Comment by OmerBenGera** [comment] 2021-09-07 08:58
> Seems like its fixed, /is admin recalc seems to be broken in b295 but I can open a new ticket for that if desired

Please do so

**Closed by OmerBenGera** 2021-09-07 08:58 UTC
Labels: 🔧 Potential fix, 📝 Missing information, ❌ Unconfirmed
