### ISSUE TITLE
IslandWorthUpdateEvent fail

### ISSUE THREAD

**Issue by FrancyMak** [BG-Software-LLC/SuperiorSkyblock2#423] opened 2021-08-06 16:41 UTC
### Minecraft's Version

Tuinity .16.5-RO01-SNAPSHOT

### Plugin's Version

1.7.0-Dev209

### Describe the bug

IslandWorthUpdateEvent fail

### To Reproduce

Use java16 and NashronEngine as addon, when you place a block in the island you should get this error

**Comment by OmerBenGera** [comment] 2021-08-06 23:08
Duplicate of #371

**Closed by OmerBenGera** 2021-08-06 23:08 UTC
Labels: Bug Report, Pending
