### ISSUE TITLE
Is missions gets restarted

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#901] opened 2022-01-31 15:59 UTC
### Minecraft's Version

1.17

### Plugin's Version

SuperiorSkyblock2-1.8.4-b501

### Describe the bug

All missions progress gets deleted except for the killing mobs ones. Well, it does gets deleted but somehow when I kill 1 mob, the progress % returns, but for farming and mining, it doesn't no matter what. 

So If i complete mining missions or farming missions and progress to level 2. When the server gets restarted, all the first level missions gets deleted and to continue progressing the level 2 mission, i have to complete level 1 mission again. 

### To Reproduce

complete missions, use mysql, restart the server. 

### Additional Information

![image](https://user-images.githubusercontent.com/98068350/151826820-d3162a0e-d970-4d2b-a0f9-46084a705cb5.png)

**Comment by OmerBenGera** [comment] 2022-01-31 21:46
Duplicate of #847

**Closed by OmerBenGera** 2022-01-31 21:46 UTC
Labels: Pending
