### ISSUE TITLE
I have mixed placeholders 

### ISSUE THREAD

**Issue by DofyAdm** [BG-Software-LLC/SuperiorSkyblock2#1005] opened 2022-03-18 15:39 UTC
### Minecraft's Version

Minecraft 1.16.5 spigot 

### Plugin's Version

Version 1.8.4

### Describe the bug

When I want to use the placeholder that returns the level of an island, it returns its value. 

I haven't tried with other placeholders though

### To Reproduce

I noticed this bug while trying to use them on holograms, via the HolographicDisplay plugin and its extension holographicextension

**Comment by OmerBenGera** [comment] 2022-03-18 15:46
When you run `/papi parse me %superior_island_worth%` and `/papi parse me %superior_island_level%`, do they return the same value?

**Comment by DofyAdm** [comment] 2022-03-18 15:50
it returns me the good values it is strange

**Comment by OmerBenGera** [comment] 2022-03-18 15:51
> it returns me the good values it is strange

It means the issue is not with the plugin but with the holograms plugin.
It may cache data or something and this is what causes it to occur.

Closing this for now

**Closed by OmerBenGera** 2022-03-18 15:51 UTC
Labels: ❌ Unconfirmed
