### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Scorbunny10** [BG-Software-LLC/SuperiorSkyblock2#2043] opened 2024-03-28 10:16 UTC
### Minecraft's Version

[11:10] This server is running CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-2023.3.rar

### Describe the bug

https://www.veed.io/view/ad70ff46-2524-4aff-9297-b0d7d2bca135?panel=share

ore from generator is not visible. If I use rmb on hidden ore  makes visible

### To Reproduce

make generator
and click rmb on not visible ore/stone

**Comment by OmerBenGera** [comment] 2024-03-30 13:50
Duplicate of #2039

**Closed by OmerBenGera** 2024-03-30 13:50 UTC
Labels: Pending
