### ISSUE TITLE
The command /island admin setupgrade doesn't exist

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#275] opened 2021-05-22 13:15 UTC
**Minecraft's Version**
Tuinity 1.16.5 (Build #231)

**Plugin's Version**: -
Dev build 150

**Describe the bug**
I get some reports of an issue since I updated the plugin that upgrades are counted as bought but without getting access to what they bought

**To Reproduce**
Here is a code I use to give access to the nether. Players don't get the removed block limit of soul_sand and can't go in the nether but it says that they already bought the upgrade.
`  nether:
    '1':
      price: 5000000.0
      price-type: Money
      commands:
      - island admin setupgrade %player% nether 2
      - island admin removeblocklimit %player% soul_sand
      - island admin unlockworld %player% nether true
      - island admin msg %player% &bSky&6Republic &7Vous avez débloqué le nether.
    '2':
      price: 0.0
      price-type: Money
      commands:
      - island admin msg %player% &bSky&3&lRepublic &7» Vous avez déjà accès au Nether.`

**Additional information**
The command /is admin setupgrade doesn't exist when you use it IG, I don't know if it should work normaly?

**Comment by OmerBenGera** [comment] 2021-05-22 13:37
Does it work if you use it manually?

**Comment by banicola** [comment] 2021-05-22 13:42
No it doesn't work if I use /is admin setupgrade it returns the help menu

**Comment by OmerBenGera** [comment] 2021-05-22 13:51
It sounds like the upgrade module is not enabled for you.

**Comment by banicola** [comment] 2021-05-22 15:13
![image](https://user-images.githubusercontent.com/25954399/119231393-f513df80-bb20-11eb-8d0e-dc3b7979e003.png)

**Comment by OmerBenGera** [comment] 2021-05-22 15:15
If you restart, does it help?

**Comment by banicola** [comment] 2021-05-22 15:22
Ok it's working with the restart.

**Comment by OmerBenGera** [comment] 2021-05-22 15:28
I really don't know why it didn't work in first place...

**Comment by banicola** [comment] 2021-05-22 15:39
I don't know myself... But anyway if it is working now it's ok for me. Thanks !

**Comment by ElBananaa** [comment] 2021-05-22 21:21
Hey!
I can confirm I had the same issue when upgrading to the build 155. The module was enabled, but for some reason the command didn't work until I restarted the server a second time. It's not a big deal, but I must admit that if I wouldn't have seen this issue earlier today, it would've taken me hours to figure out why it didn't work. You should probably add a warn to the log if this can't be fixed. ^^

**Comment by Obliviated** [comment] 2021-05-27 19:53
![image](https://user-images.githubusercontent.com/36128276/119888612-3e5b9900-bf3e-11eb-9c55-1626245d6672.png)
i decompiled the plugin and i examined github page.

**Comment by OmerBenGera** [comment] 2021-05-28 15:46
Fixed in build 156 (the /is admin reload part), good one on that.
Hopefully it will fix all the issues alongside of it.

**Comment by OmerBenGera** [comment] 2021-06-04 18:30
I am closing this as it seems to be fixed
If the issue still persists, make sure you let me know here.

**Closed by OmerBenGera** 2021-06-04 18:30 UTC
Labels: Bug Report, Potential fix
