### ISSUE TITLE
Error when creating schematic

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#271] opened 2021-05-21 19:26 UTC
**Minecraft's Version**
yatopia-1.16.5

**Plugin's Version**: -
devbuild-143

**Describe the bug**
I can't create an island schematic

**To Reproduce**
do /island admin schematic, select 2 pos, do /island admin schematic testa

**Additional information**
https://pastebin.com/NREmgs6M

**Comment by WarnDangerous** [comment] 2021-05-21 19:52
It was due to "multithreaded worldgen" of yatopia. On default branch it works.

**Comment by WarnDangerous** [comment] 2021-05-21 23:14
But if I create the island on default branch (without the multithreading world generation, it will work, but once I switch to the threaded worldgeneration, it bugs and generate wrongly the world.

Normal island : 
![Screenshot_3796](https://user-images.githubusercontent.com/31826333/119206289-fef2ff80-ba9a-11eb-8cf1-d22bc13f9f53.png)


Once I create it with multithreading worldgen : 
![Screenshot_3795](https://user-images.githubusercontent.com/31826333/119206304-0a462b00-ba9b-11eb-880d-a2aec80d0b7e.png)

**Comment by WarnDangerous** [comment] 2021-05-21 23:21
Yatopia master branch : 
https://yatopiamc.org/download.html
(or codemc link : https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%252F1.16.5/ )


The multithreaded-worlgen version which get the issue : 
https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/dev%252Fc2me-port/

**Comment by WarnDangerous** [comment] 2021-05-21 23:26
The problem doesn't come from yatopia itself, as with worldedit it works great (I can make the schematic and paste it with worldedit without any issue)

**Comment by OmerBenGera** [comment] 2021-05-22 06:57
It seems to work fine for me with default schematics. I am pretty sure I installed the multithreaded worldgen version correctly, but I might have not. Mind testing it with default schematic?

**Comment by OmerBenGera** [comment] 2021-05-22 07:03
Also, when I place glowstone, it turns into jack o lantern, and blocks turn into other blocks when I place them.
I think these versions of the mutlithreaded worldgen are just bugged.

**Comment by WarnDangerous** [comment] 2021-05-22 10:57
When I create the island on default yatopia, it works great, I can use them, but once I use the c2me port branch, if I use the same .schematic it will bug and past it with all blocks turned facing "south" (button, sign, etc) that's strange :/

**Comment by OmerBenGera** [comment] 2021-05-22 11:35
> 
> 
> When I create the island on default yatopia, it works great, I can use them, but once I use the c2me port branch, if I use the same .schematic it will bug and past it with all blocks turned facing "south" (button, sign, etc) that's strange :/
> 
> But all blocks are still the same, signs still have their writing, just a bug of placing in the good rotation

It worked fine for me, not sure what the issue is
But I noticed that the branch you talk about is buggy af, and the client is not synchronized with it at all (As I said before, when I placed a glowstone, my client thought it's jack o lantern, and it happened with lots of other blocks), so I don't recommend using it at all

**Comment by WarnDangerous** [comment] 2021-05-22 11:37
Yes this branch is in alpha state and can be buggy with generation plugin, that's why it's in alpha, but I'll use the main branch for now, and wait for some fix (but this branch add good performances improvement with multithreading worldgeneration, that's why I used it).

Hope yatopia will soon fix all theses issues ^^

**Comment by OmerBenGera** [comment] 2021-05-22 11:39
I understand
Well, I tried creating a simple schematic in this version and it worked fine for me, so it's probably something specific with your schematic. Mind sending it here (using WE schematic or a SSB schematic) so I can try replicate it myself?

**Comment by WarnDangerous** [comment] 2021-05-22 11:43
You created a schematic on which branch ? master one or "c2me port" one ?

As personnaly I can't create a schematic on c2me branch because I get the error I reported above :
https://pastebin.com/NREmgs6M

**Comment by OmerBenGera** [comment] 2021-05-22 12:05
I could replicate the issue using your schematic.
Again, even if I fix it, I don't recommend using this branch, as in the 5 minutes that I tried it, I had multiple times issues with the blocks not syncing with client correctly. This branch is really broken and I am not gonna be surprised if the issue turns to be due to that. Anyways, I am gonna check that out.

**Comment by WarnDangerous** [comment] 2021-05-22 12:08
I'll try that branch during my alpha tests, and if it's really bugged I'll switch to the main branch, but it's still nice to fix this issue, as when yatopia will fix this branch, I'll use it without any problem on superior :)

**Comment by OmerBenGera** [comment] 2021-05-22 12:37
Check out latest dev build, it should be fixed.
The issue turned to be on all Yatopia versions, not only on the multithreaded gen branch.

**Comment by WarnDangerous** [comment] 2021-05-22 12:59
I try it later (currently I got some player online that test the whole server), but thanks a lot ! :D

**Comment by WarnDangerous** [comment] 2021-05-23 18:43
It works nice :)

**Comment by OmerBenGera** [comment] 2021-05-28 13:15
Perfect :)

**Closed by OmerBenGera** 2021-05-28 13:15 UTC
Labels: Bug Report, Potential fix
