### ISSUE TITLE
Heavy task since I upgraded from 1.16 -> 1.17

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1039] opened 2022-04-08 10:47 UTC
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b577 

### Describe the bug

Since I upgraded my server from 1.16 to 1.17, plugin is taking 20% performances in spark (on main thread), I don't know why, maybe it converts the map, or idk, but it shouldn't.

https://spark.lucko.me/t6Vy72tDsz
![image](https://user-images.githubusercontent.com/31826333/162420705-51e7e94d-c7be-4e1d-a6af-cd9328495097.png)

### To Reproduce

Convert a big world from 1.16 to 1.17, and do a spark

### Additional Information
- On 1.16, plugin used 2-4% server ressources in spark (for the entity limit).
- I tried to disable entity-limit, it still take 15% in a spark https://spark.lucko.me/fIxLB2DKe0
- Even with 0 players online plugin take 20% server ressources, so it's not related to online players

**Comment by OmerBenGera** [comment] 2022-04-08 11:05
The issue is with chunk loading

**Comment by WarnDa** [comment] 2022-04-08 11:13
> The issue is with chunk loading, not really related to the plugin

It is, I enabled debug to see why chunk loading is heavy, 
50 000 lines of debug in 6 seconds.
So 25 000 chunks loaded in 6 seconds, it is not normal : https://paste.helpch.at/alokulilax.sql

**Comment by OmerBenGera** [comment] 2022-04-08 14:42
> > The issue is with chunk loading, not really related to the plugin
> 
> It is, I enabled debug to see why chunk loading is heavy, 50 000 lines of debug in 6 seconds. So 25 000 chunks loaded in 6 seconds, it is not normal : https://paste.helpch.at/alokulilax.sql

I will add a reason for the debug messages when loading chunks, we'll see why it's loading the chunks.

**Comment by OmerBenGera** [comment] 2022-04-08 15:16
> > The issue is with chunk loading, not really related to the plugin
> 
> It is, I enabled debug to see why chunk loading is heavy, 50 000 lines of debug in 6 seconds. So 25 000 chunks loaded in 6 seconds, it is not normal : https://paste.helpch.at/alokulilax.sql

Please re-upload the paste that you sent here, it's not valid anymore.

**Comment by WarnDa** [comment] 2022-04-08 15:21
If needed : https://paste.helpch.at/zijujihira.sql

**Comment by OmerBenGera** [comment] 2022-04-08 15:21
I added the reason for loading the chunk to the debug messages - please install latest dev build and enable the debug as you've done before. Currently this is the list of available reasons:
SCHEMATIC_PLACE - Chunk is loading for placing blocks for a schematic
ENTITY_TELEPORT - Chunk is loading for teleporting an entity.
BLOCKS_RECALCULATE - Chunk is loading for calculating blocks inside it.
ENTITIES_RECALCULATE - Chunk is loading for calculating entities inside it.
FIND_SAFE_SPOT - Chunk is loading for finding a safe block inside it.
API_REQUEST - Chunk is loading through the API's methods.

Report back once you updated :)

**Comment by WarnDa** [comment] 2022-04-08 15:37
It's telling it's "ENTITIES_RECALCULATE" but not possible.
I disabled entity limit to test (yesterday) and it's still taking 15% server ressources : https://spark.lucko.me/fIxLB2DKe0

And why it would calculate sooo much chunks just for entities ?
https://paste.helpch.at/ehajipavim.sql

**Comment by OmerBenGera** [comment] 2022-04-08 17:38
> It's telling it's "ENTITIES_RECALCULATE" but not possible. I disabled entity limit to test (yesterday) and it's still taking 15% server ressources : https://spark.lucko.me/fIxLB2DKe0
> 
> And why it would calculate sooo much chunks just for entities ? https://paste.helpch.at/ehajipavim.sql

There was an issue that entities were still calculated when entity limits was disabled - this is fixed in latest dev build.
I also try to improve the recalculation of entities by making it to only occur in 5 minute intervals.
Let me know if it's better.

**Comment by WarnDa** [comment] 2022-04-08 23:03
I just updated and tried, limit seems to work like before without issue, and spark is really fine : 
https://spark.lucko.me/UZNEgeZwic

**Comment by WarnDa** [comment] 2022-04-09 12:34
Way better, it also fixes #1040 !
Here is the spark : https://spark.lucko.me/cR1TranBrH
For the entity limit that fail (and you can get more than the maximal amount) is still present but better, I'll open an issue if needed

**Comment by OmerBenGera** [comment] 2022-04-09 16:46
What do you mean by `For the entity limit that fail (and you can get more than the maximal amount) is still present but better`?

**Comment by WarnDa** [comment] 2022-04-09 16:51
> What do you mean by `For the entity limit that fail (and you can get more than the maximal amount) is still present but better`?

Some player can go higher than the limit, sometimes some mobs are not counted correctly (or I don't know) and player get a total of 35 stacks even if the limit is 25 stacks.
I can't really find an exact way on how to reproduce this, it seems random, and it happens less often than before

**Comment by OmerBenGera** [comment] 2022-04-09 16:52
> > What do you mean by `For the entity limit that fail (and you can get more than the maximal amount) is still present but better`?
> 
> Some player can go higher than the limit, sometimes some mobs are not counted correctly (or I don't know) and player get a total of 35 stacks even if the limit is 25 stacks. I can't really find an exact way on how to reproduce this, it seems random, and it happens less often than before

I see.
Find how to replicate it and open a new issue regarding this.
For now, closing this one :)

**Closed by OmerBenGera** 2022-04-09 16:52 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
