### ISSUE TITLE
Dupe with Mobdrop upgrade

### ISSUE THREAD

**Issue by Faceless0102** [BG-Software-LLC/SuperiorSkyblock2#212] opened 2021-04-11 11:59 UTC
**Minecraft's Version**
PaperSpigot 1.12.2

**Plugin's Version**: -
b111

**Describe the bug**
So basically if you upgrade the mob drop and kill an entity with a saddle it will dupe the saddles and also if a donkey, llama, mule has a chest and it contains items, the items will be duped

**Comment by OmerBenGera** [comment] 2021-04-15 08:36
Duplicate of #205

**Closed by OmerBenGera** 2021-04-15 08:36 UTC
Labels: Bug Report, Further Investigation
