### ISSUE TITLE
Issue with spawn (multiverse/essentials)

### ISSUE THREAD

**Issue by AlecMcCutcheon** [BG-Software-LLC/SuperiorSkyblock2#1820] opened 2023-08-01 15:49 UTC
### Minecraft's Version

1.19.4

### Plugin's Version

2-2023.2

### Describe the bug

So this is kind of a multi part issue I don't know if I would classify it as a bug but stay only in place that I thought would be suitable to post this, basically I have multiverse server with survival creative and Skyblock, I'm also using essentials, currently when hi enter one of the other worlds like survival are creative it brings me to where I was when I left and when I enter skyblock it does not, so I wanted to know if there was anything I could change in the configurations to make it so that it functions like the other worlds do. I've tried messing with the priority in the essential settings and that didn't seem to do anything.

### To Reproduce

Have a server with essentials and multiverse and skyblock  and then enter skyblock no matter what you do you'll be brought back to the skyblock spawn.

**Comment by OmerBenGera** [comment] 2023-08-04 12:05
I have no clue what the issue is tbh.
You should however use Proxy for multi game modes as having them all in one server will cause a lot of lag and will be unplayable. Also, this is not supported by SuperiorSkyblock and may cause issues.

Therefore, I am closing this - as even if there is a bug, I don't have intentions to fix it.

**Closed by OmerBenGera** 2023-08-04 12:05 UTC
Labels: Pending
