### ISSUE TITLE
Nashorn logs and server crashing

### ISSUE THREAD

**Issue by Redwolf223** [BG-Software-LLC/SuperiorSkyblock2#648] opened 2021-10-04 09:03 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

b327

### Describe the bug

When i start building on my island the server is spamming this logs in console. I'm running nashornengine b4

https://pastebin.com/WP4kCz9s

### To Reproduce

Unfortunately i don't know how to reproduce this.

**Comment by OmerBenGera** [comment] 2021-10-06 05:41
Duplicate of #371

**Closed by OmerBenGera** 2021-10-06 05:41 UTC
Labels: Pending

**Comment by Redwolf223** [comment] 2021-10-10 21:18
Hi i've changed the engine and now i'm having this problem.

https://pastebin.com/Znn29pU3
