### ISSUE TITLE
entity and placehoders

### ISSUE THREAD

**Issue by LeRoiDamien** [BG-Software-LLC/SuperiorSkyblock2#255] opened 2021-05-15 08:12 UTC
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
b134

Hello, after some research I can not find how with the entities in the / is values ​​I join the screen of my config

then there are no placeholders like him either
"% superior_island_count_ <block>%" but for entities?

![Screenshot_188](https://user-images.githubusercontent.com/68817729/118353327-0c256100-b566-11eb-9430-9bd1378cb8ba.png)

**Comment by OmerBenGera** [comment] 2021-05-15 11:01
What are you trying to do?
(Also this is not a bug, so I am closing this)

**Closed by OmerBenGera** 2021-05-15 11:01 UTC
Labels: Bug Report, Pending

**Comment by LeRoiDamien** [comment] 2021-05-15 13:19
I try to make so that in the / is values ​​the "entity" of the type item_fame armor_stand minecart is displayed in the menu
And for the placeholders to create a menu with all the limits of the entities


On the screens the number does not change it remains at 0
![Screenshot_188](https://user-images.githubusercontent.com/68817729/118362728-f8dbbb00-b590-11eb-991d-4be763dab5f0.png)
![Screenshot_189](https://user-images.githubusercontent.com/68817729/118362729-fa0ce800-b590-11eb-8992-153139ade86f.png)

**Comment by OmerBenGera** [comment] 2021-05-15 14:27
This is because it only shows block amounts. SSB doesn't track the amount of entities on the island, therefore you can't display such information.

**Comment by LeRoiDamien** [comment] 2021-05-15 14:43
Ok thank you very much for answering
