### ISSUE TITLE
Error in saving mission data

### ISSUE THREAD

**Issue by kamo125** [BG-Software-LLC/SuperiorSkyblock2#1501] opened 2022-12-10 15:50 UTC
### Minecraft's Version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Purpur-1857 (MC: 1.19.2)
* You are running the latest version

### Plugin's Version

2022.9-b925

### Describe the bug

The plugin seems to be having problem with saving data for my players missions.

Error:
![obrázek_2022-12-10_164958756](https://user-images.githubusercontent.com/118190496/206863534-59f8546d-fb96-4a06-8fc9-ac854bb9bf08.png)

### To Reproduce

Just complete mission and this appears in console.

**Comment by OmerBenGera** [comment] 2022-12-11 05:53
Duplicate of #1450

**Closed by OmerBenGera** 2022-12-11 05:53 UTC
Labels: Pending
