### ISSUE TITLE
Problem with /is top

### ISSUE THREAD

**Issue by Chrqmated** [BG-Software-LLC/SuperiorSkyblock2#100] opened 2021-03-04 05:13 UTC
Hello ! When I do /is top the heads appear like steve's heads ... A player having told me "you have surely modified the item in your config" so I then deleted the file to reveal the default file . But alas, still the same worry ... The heads are meant to be steves: http://prntscr.com/10cnfsn

**Comment by OmerBenGera** [comment] 2021-03-05 11:54
It can be caused if you have a server in offline mode (allows cracked accounts) without having a skins restorer plugin.
If that's the case, but you do have a skins plugin, let me know what plugin are you using.
Also, let me your SSB plugin and spigot jar.

**Comment by OmerBenGera** [comment] 2021-03-07 09:08
Any news regarding this?

**Comment by Chrqmated** [comment] 2021-03-08 01:01
Excuse for my late, i have Skinrestorer and yes my server allowed cracked accounts

**Comment by OmerBenGera** [comment] 2021-03-09 14:08
What version of the plugin and what version of spigot are you using?

**Comment by OmerBenGera** [comment] 2021-03-23 11:29
Any news regarding this?

**Comment by adviis** [comment] 2021-04-03 13:15
Good morning, I also have this problem. I guess it's the bungeecord's fault, because when I disconnected the server from the bungee, everything was working normally.
Spigot version 1.12.2, plugin version 1.5.2-DEVb102, I have a SkinRestorer plugin.
Have a nice day!

**Comment by OmerBenGera** [comment] 2021-04-03 13:21
> 
> 
> Good morning, I also have this problem. I guess it's the bungeecord's fault, because when I disconnected the server from the bungee, everything was working normally.
> Spigot version 1.12.2, plugin version 1.5.2-DEVb102, I have a SkinRestorer plugin.
> Have a nice day!

This happens when you have SkinsRestorer in your bungeecord plugins folder and not the spigot plugins folder.

**Comment by adviis** [comment] 2021-04-03 13:32
Is there a solution to this or not? :( (the console displays an error each time a player enters) If it is impossible, could you add functions in config.yml disabling the connection to SkinRestorer (to avoid spam errors in the console?) 
 
[SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.6.0-DEVb111 generated an exception while executing task 325
java.lang.NullPointerException: null
        at net.skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:209) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:149) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook$SkinsRestorerNew.getSkin(SkinsRestorerHook.java:69) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.setSkinTexture(SkinsRestorerHook.java:23) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.lambda$setSkinTexture$0(SkinsRestorerHook.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by OmerBenGera** [comment] 2021-04-03 13:35
> 
> 
> Is there a solution to this or not? :( (the console displays an error each time a player enters) If it is impossible, could you add functions in config.yml disabling the connection to SkinRestorer, please (to avoid spam errors in the console?)
> 
> [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.6.0-DEVb111 generated an exception while executing task 325
> java.lang.NullPointerException: null
> at net.skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:209) ~[?:?]
> at net.skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:149) ~[?:?]
> at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook$SkinsRestorerNew.getSkin(SkinsRestorerHook.java:69) ~[?:?]
> at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.setSkinTexture(SkinsRestorerHook.java:23) ~[?:?]
> at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.lambda$setSkinTexture$0(SkinsRestorerHook.java:19) ~[?:?]
> at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
> at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

This is because of SkinsRestorer being on the bungeecord, as I said earlier.
This cannot be fixed on my side - they need to properly handle that and fix it.

I am closing this anyways, as it's a duplicate of #154

**Closed by OmerBenGera** 2021-04-03 13:35 UTC
Labels: Bug Report, Further Investigation
