### ISSUE TITLE
Permissions reset

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1218] opened 2022-06-30 17:53 UTC
### Minecraft's Version

1.12.2 paper

### Plugin's Version

1.11.0.696

### Describe the bug

On every restart the permissions go back to the default values from the config

### To Reproduce

-

**Comment by OmerBenGera** [comment] 2022-06-30 18:03
Duplicate of #831

**Closed by OmerBenGera** 2022-06-30 18:03 UTC
Labels: Pending
