### ISSUE TITLE
Island get deleted after Restart

### ISSUE THREAD

**Issue by AdityaVishu** [BG-Software-LLC/SuperiorSkyblock2#556] opened 2021-09-01 15:24 UTC
### Minecraft's Version

1.16

### Plugin's Version

267

### Describe the bug

I created island yesterday but when I restart the server there was not my island it got wipe out 

### To Reproduce

.

**Comment by OmerBenGera** [comment] 2021-09-01 16:13
Duplicate of #554

**Closed by OmerBenGera** 2021-09-01 16:13 UTC
Labels: Pending
