### ISSUE TITLE
SuperiorSkyBlock2 1.17.1 server crashing solution

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#404] opened 2021-07-27 21:25 UTC
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

SuperiorSkyblock2-b199.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

there are 2 bugs that I will report to be fixed and also to help people who are having this problem and have no solution.

1° server crashing:  when you have 10 - 20 players or even more and if someone uses /is biome the server crashes and knocks out all players you will have to restart the server.

2° server crashing:  another problem that is causing this error ( https://pastebin.com/xFDRU4dY )  within the superiorskyblock settings you have this option -> entity-limits: if you add a list of mobs to limit by that your server will crash so don't add any mobs and everything will work fine.

those are the 2 worst bugs that are crashing the server when it has a lot of players like 20 - 30, I hope this gets fixed because who hasn't found these problems I bet has given up on the plugin.

### To Reproduce

/is biome with about 10 - 20 players online.

within the superiorskyblock settings you have this option -> entity-limits:  don't add any mobs and everything will be fine.

**Comment by WarnDangerous** [comment] 2021-07-27 21:44
Are you using pterodactyl panel ?

**Comment by brasilcraft54** [comment] 2021-07-28 13:50
> Are you using pterodactyl panel ?

yes

**Comment by WarnDangerous** [comment] 2021-07-28 13:52
The issue comes from pterodactyl since their latest update.
Here is the solution :

<img width="518" alt="Screenshot_5362" src="https://user-images.githubusercontent.com/31826333/127334233-e5d57ff5-a250-4958-ad9f-131b507df8c4.png">


I had the same issue, I had to set pid_limit to 0 to fix this issue.

**Comment by brasilcraft54** [comment] 2021-07-28 13:53
> The issue comes from pterodactyl since their latest update.
> Here is the solution :
> 
> <img alt="Screenshot_5362" width="518" src="https://user-images.githubusercontent.com/31826333/127334233-e5d57ff5-a250-4958-ad9f-131b507df8c4.png">
> 
> I had the same issue, I had to set pid_limit to 0 to fix this issue.

I already did that and it didn't solve what I did above

**Comment by brasilcraft54** [comment] 2021-07-28 13:54
The only thing that will solve this is to do what I said above, not to use /is biome, and not to use the island entity limit.

**Comment by brasilcraft54** [comment] 2021-07-28 13:56
for me it solved removing all the superiorskyblock checking entities

**Comment by WarnDangerous** [comment] 2021-07-28 13:56
Dev will tells you the error in on your side, he told me the same things when I had this issue. And it was related to pterodactyl/docker.

**Comment by brasilcraft54** [comment] 2021-07-28 13:57
add container_pid_limit: 0  ?

**Comment by brasilcraft54** [comment] 2021-07-28 13:57
and upgrade to the latest version?

**Comment by brasilcraft54** [comment] 2021-07-28 13:58
my server is already online with 40-50 players when I made the modifications in superiorskyblock taking out the entities and taking out the permission to change the biome

**Comment by WarnDangerous** [comment] 2021-07-28 14:00
Yes, solved my issue by setting it to 0 and then restart server and wings

The version I use : 
- pterodactyl 1.4.2
- wings 1.4.4

**Comment by brasilcraft54** [comment] 2021-07-28 14:04
I use this version too but it said to set it to 512 and it didn't solve the problem when I removed the entities from the checklist it solved the problem

**Comment by WarnDangerous** [comment] 2021-07-28 14:04
I told you that **512** didn't fix my issue, I had to set it to **0** to solve my issue !

**Comment by WarnDangerous** [comment] 2021-07-28 14:05
So set it to **0**

**Comment by brasilcraft54** [comment] 2021-07-28 14:07
superiorskyblock is full of bugs and I created this report to help people that don't have access to the panel and don't have a dedicated panel like us, there are other bugs too, like the spam that happens when you complete a quest, today I found another bug in superiorskyblock that is in settings -> optimize: false when this is set to true, the plugin jetminions and cloudcollectors does not work right and more the 2 problems above I never had a problem with this and I am only reporting to the owner of the plugin when he has time to fix these problems, because in these 5 years I never had this problem so I already did the test my server hit 66 online with superiorskyblock so it still has many bugs and memory leaks.

**Comment by brasilcraft54** [comment] 2021-07-28 14:08
> So set it to **0**

could you show your timings?

**Comment by brasilcraft54** [comment] 2021-07-28 14:11
my timings https://timings.pl3x.net/?id=ed065c2689f14f0283f3839a4a7d30ba   it seems that superiorskyblock is affecting many plugins still like wildstacker. if you enable optimization within the superiorskyblock settings you will have a problem with jetminions if you have this plugin.

**Comment by brasilcraft54** [comment] 2021-07-28 14:56
> So set it to **0**

set this to 0 what would that do?

**Comment by OmerBenGera** [comment] 2021-07-28 21:09
Duplicate of #369

**Closed by OmerBenGera** 2021-07-28 21:09 UTC
Labels: Bug Report, Pending

**Comment by brasilcraft54** [comment] 2021-07-29 01:23
no this topic I created to report you the 2 worst bugs you are having that are not being fixed

**Comment by brasilcraft54** [comment] 2021-07-29 01:24
there are many more bugs but you don't fix any of them.

**Comment by WarnDangerous** [comment] 2021-07-29 01:26
> no this topic I created to report you the 2 worst bugs you are having that are not being fixed

The two bugs are related, on the other ticket he is saying he'll fix them.

The dev told the plugin wouldn't be 100% updated, but he would take some time to fixs bugs, he isn't actively developping the plugin anymore, he just offer some updates when he gets time.

**Comment by brasilcraft54** [comment] 2021-07-29 01:36
the plugin is generating delays on the server too I don't understand why check my timings

**Comment by OmerBenGera** [comment] 2021-07-30 07:55
The only bug report you opened is this one.
If you believe there are more issues with the plugin, feel free to open new issues.
