### ISSUE TITLE
Private warps reset to public on server restart

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#139] opened 2021-03-29 18:05 UTC
**Minecraft's Version**
1.16.5 Yatopia

**Plugin's Version**: -
SuperiorSkyblock-b102

**Describe the bug**
Private warps that have changed information reset back to public on server restart.

**To Reproduce**
Create a warp, make it public, edit the warp, and then wait for restart.

**Additional information**
Confirmed this happens across a few days.

**Comment by OmerBenGera** [comment] 2021-03-29 19:25
I can't seem to replicate the issue

**Comment by Skizzles** [comment] 2021-03-30 09:57
From my testing it only seems to occur when the warp has lore changed and its item display as well.

**Comment by OmerBenGera** [comment] 2021-03-30 12:06
Seems to work as intended for me, even if I change the lore and the item display of the warp.

**Comment by Skizzles** [comment] 2021-03-30 20:56
I will see if I can get a video to show / some screenshots.

**Comment by Skizzles** [comment] 2021-03-31 14:58
https://screenshots.skizzles.me/wAnA3/KibIXani76.mp4

Video showing the warp having to be closed again after restart.

**Comment by OmerBenGera** [comment] 2021-04-02 12:55
Fixed in an unpublished dev build (will be released soon probably)

**Closed by OmerBenGera** 2021-04-02 12:55 UTC
Labels: Bug Report, Further Investigation
