### ISSUE TITLE
Kick island members error

### ISSUE THREAD

**Issue by 0VERR** [BG-Software-LLC/SuperiorSkyblock2#734] opened 2021-11-14 12:51 UTC
### Minecraft's Version

1.17 airplane

### Plugin's Version

362 & 1.8.1

### Session Logs

I dont have this file inside SuperiorSkyBlock2 folder

### Describe the bug

It is not possible to kick a member from our island, when we kick him under /is members it still shows him as a member, in addition when he founds his own island it shows him as a leader under /is members of our island. There is no way to kick a member from our island - https://youtu.be/CuUFI2iKfAs . Bug is fixed after restarting server

### To Reproduce

-> Invite player to island
-> Kick player
-> Player still is in our island
-> Player which kicked create island
-> In our /is members he get LEADER

### Additional Information

https://youtu.be/CuUFI2iKfAs

Also please put in the STABLE VERSION a version that has been tested and is stable like in the old days, currently the stable version has critical bugs like the one listed above.

**Comment by 0VERR** [comment] 2021-11-14 12:56
I forgot also, that when this BUG happens, the player who has the island cannot invite ANYONE to the island until the server is restarted

**Comment by OmerBenGera** [comment] 2021-11-14 14:09
Use latest dev build.
After that  include the session logs file.

**Comment by 0VERR** [comment] 2021-11-14 14:10
I now using latest version, where is this session logs file? https://imgur.com/a/B3F1ZkO

**Comment by OmerBenGera** [comment] 2021-11-14 14:14
Inside the plugin's folder.
If you dont use latest dev build, you will not see it.

Make sure you install latest dev build and not latest stable version

**Comment by 0VERR** [comment] 2021-11-14 14:31
I have latest, i dont have this file https://imgur.com/a/B3F1ZkO

**Comment by OmerBenGera** [comment] 2021-11-14 15:51
Weird.
Send me the latest.log file (located in the logs folder of the server)

**Comment by rolfie12** [comment] 2021-11-20 09:10
Hello @OmerBenGera , I can confirm this is a bug and will provide you the necessary information that the original reporter couldn't provide.
It is quite serious since those bugged members can also see the island team chat from the island they left.
A player on my server recorded how to replicate the bug as well, I will follow up to that recording by sending the session.logs part that represent the recording or most of it.
The server is running Paper 1.17.1 build 386.
SuperiorSkyblock2 dev build 366, cannot update yet to a higher one because of schematics being broken on newer dev builds and we run a production server, but I doubt this issue here is fixed in any of the new dev builds anyways.

The video proof: https://www.youtube.com/watch?v=LMemYSoQOsM
The session.logs that might help checking this: https://pastebin.com/wuvVinc2

**Additional details:**
Running /is admin info MEMELORD69420 shows him as the island leader but shows another bugged leader which should not show as this is not a role that can be given to 2 members on 1 island. Proof: https://imgur.com/a/STabMST

At the same time after running the above command, using /is admin info ItsR4yz shows him as leader of his own island too.
Proof: https://imgur.com/a/usUIqS3

As stated by the reporter above this is fixed after each server restart, but still quite a big issue during the day until the next daily restart. In conclusion there's an issue when a player leave/is kicked from an island, leading to a bugged player that is seemingly part of 2 islands at the same time.

**Comment by OmerBenGera** [comment] 2021-11-20 09:28
@rolfie12 Thanks for the additional info.
It seems like you tried to do that process multiple times, not once as shown in the video.
How many times did you try until it occurred?
As for me, I can't replicate it - I have an alt that joins the island, leaves and everything seems to be fine.

Also, about the schematics bug, it's been addressed in the latest builds.

**Comment by rolfie12** [comment] 2021-11-20 09:42
I just tried the latest dev build on my test server before the production one and had this error: https://pastebin.com/kenc5zff

Regarding the bug, It happens for all our players but the recording was only to show how to replicate it.
I asked the member and apparently the bug happens all the time It doesn't require multiple tries, however when it happens It doesn't seem to be bugging the name again. As you might have noticed in the end of the video, after the player left the second time his name was only there once not twice, strange but its causing a lot of problems and specially to the island member limit upgrade.
Thank you!

**Comment by OmerBenGera** [comment] 2021-11-20 09:47
@rolfie12 open an issue about the error.

About the bug, I think I understand what the issue is.
Members should be added and stored in a sorted way by their names.
However, when ItsRayz joins the island, you can see he's above the member that his name starts with "C". This makes no sense, as "C" is before "I". However, in the second time you invite him, he's found at the correct location, and therefore can be removed.

I will look into that right away, hopefully I will be able to find the cause of the issue.

**Comment by rolfie12** [comment] 2021-11-20 09:50
Thank you very much, I will open an issue about the error asap.

**Comment by OmerBenGera** [comment] 2021-11-20 10:08
The issue was the way members were stored in the island, and that the player must was in another island with a non-member role before. The combination of the player added to the island with a different role than a member, and that members were sorted by their roles as well, causing the player to not be in the correct order, and when he was removed from the list of members, it failed.

The issue is addressed in latest build. Let me know if it works for you as well.

**Comment by rolfie12** [comment] 2021-11-20 10:22
Thank you, I would try it but I just reported another issue with the latest dev builds in another opened issue.
When the other issue is fixed then I can test this new fix, the other issue causes immediate crash on startup.
Thanks for checking!

**Comment by OmerBenGera** [comment] 2021-11-20 13:52
I am closing this for now, if it still occurs lmk

**Closed by OmerBenGera** 2021-11-20 13:52 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
