### ISSUE TITLE
Warps reset after restarts

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#723] opened 2021-11-12 15:42 UTC
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b347

### Describe the bug

`
[18:35:44 WARN]: [SuperiorSkyblock2] Task #7320428 for SuperiorSkyblock2 v1.8.0.347 generated an exception
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.island.warps.IslandWarp.getLocation()" because the return value of "java.util.Map.get(Object)" is null
        at com.bgsoftware.superiorskyblock.island.SIsland.warpPlayerWithoutWarmup(SIsland.java:2542) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.warpPlayer(SIsland.java:2537) ~[?:?]
        at com.bgsoftware.superiorskyblock.menu.impl.MenuWarps.lambda$simulateClick$1(MenuWarps.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Airplane-11]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1489) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-11]
`

### To Reproduce

After update to 347 version every restart break some players warps, they can disappear fully or remain in the menu, but when clicked, it throws this error ^

**Comment by OmerBenGera** [comment] 2021-11-12 16:02
It seems like you have warps that are saved under warp categories but not actually part of the island.
Does this player have warps with weird names or something like that?

**Comment by OmerBenGera** [comment] 2021-11-12 16:07
I uploaded a version that will should fix the errors, however it's still weird that it happened in first place.

**Comment by exzolink** [comment] 2021-11-12 16:50
> 
> 
> It seems like you have warps that are saved under warp categories but not actually part of the island. Does this player have warps with weird names or something like that?

Warps categories are disabled
No, the names are the most common

**Comment by OmerBenGera** [comment] 2021-11-12 17:00
> 
> 
> > It seems like you have warps that are saved under warp categories but not actually part of the island. Does this player have warps with weird names or something like that?
> 
> Warps categories are disabled No, the names are the most common

Might be something with them being disabled.
I will look into that.

**Comment by exzolink** [comment] 2021-11-13 12:19
Still reset warps for some players after restart

**Comment by OmerBenGera** [comment] 2021-11-13 12:24
Try replicating it yourself on your localhost.

**Comment by nivcoo** [comment] 2021-11-14 15:46
I've same issue but after this version i can display player warp but i can't deleted it and when i click on some warps i've this error : "Invalid warp : name of the warp"

**Comment by exzolink** [comment] 2021-11-14 20:03
> 
> 
> Try replicating it yourself on your localhost.

I can give you my database and tell player names whose warps is being removed

**Comment by OmerBenGera** [comment] 2021-11-19 11:35
> 
> 
> > Try replicating it yourself on your localhost.
> 
> I can give you my database and tell player names whose warps is being removed

This can work, yes.
Mind doing so?

**Comment by exzolink** [comment] 2021-11-19 21:28
Thats weird, but in a few days warps stopped resetting

**Comment by exzolink** [comment] 2021-11-20 13:03
Ok, thats happened again
Add me on discord please ExZo#8155

**Comment by OmerBenGera** [comment] 2021-11-20 13:50
I think it occurs when the warp names are too long.
I hopefully gonna release a dev build that fixes the issue soon.

**Comment by OmerBenGera** [comment] 2021-11-20 13:57
Check out latest build, hopefully warps will not reset again.

**Comment by exzolink** [comment] 2021-11-20 14:09
Warp names was less 30 characters, also sometimes instead of warp resets warp icon to default book

> Check out latest build, hopefully warps will not reset again.

**Comment by OmerBenGera** [comment] 2021-11-20 14:11
> Warp names was less 30 characters, also sometimes instead of warp resets warp icon to default book
> 
> > Check out latest build, hopefully warps will not reset again.

Warp names could have a maximum of 32 chars, however the sql-limit was 30.
I am pretty sure this difference caused some issues with loading warps and saving them into the database.
Hopefully this is fixed as well.

**Comment by exzolink** [comment] 2021-11-20 14:13
Ok, lets see

**Comment by OmerBenGera** [comment] 2021-11-20 14:17
Warps may still disappear after the first restart, however from that point they shouldn't.

**Comment by exzolink** [comment] 2021-11-20 23:51
Warps dont disappear, but icons resets every restart

**Comment by OmerBenGera** [comment] 2021-11-21 05:08
I will look into that in the weekend.

**Comment by exzolink** [comment] 2021-11-22 22:12
Some warps disappeared today (latest build)

**Comment by OmerBenGera** [comment] 2021-11-26 08:25
> Some warps disappeared today (latest build)
Were the warps in the database before they got deleted?

**Comment by OmerBenGera** [comment] 2021-12-03 09:58
Any news regarding this?

**Comment by nivcoo** [comment] 2021-12-03 09:59
Yes i've this issue everyday

**Comment by nivcoo** [comment] 2021-12-03 10:00
The warp is in /is warp gui but we can click on it or delete it with the command, so the warp stay here witthout configuration

**Comment by nivcoo** [comment] 2021-12-03 10:01
I've the issue sinc this update https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/f1f01ad20a178a988e7f9d10aa20a9ab1c60bda3

**Comment by OmerBenGera** [comment] 2021-12-03 11:38
What happens when you try to delete the island using /is delwarp?

**Comment by nivcoo** [comment] 2021-12-03 11:40
> What happens when you try to delete the island using /is delwarp?

The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui

**Comment by OmerBenGera** [comment] 2021-12-03 11:45
> > What happens when you try to delete the island using /is delwarp?
> 
> The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui

Is this warp in your database..?

**Comment by nivcoo** [comment] 2021-12-03 13:26
> > > What happens when you try to delete the island using /is delwarp?
> > 
> > 
> > The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui
> 
> Is this warp in your database..?

No in db

**Comment by OmerBenGera** [comment] 2021-12-03 13:43
> > > > What happens when you try to delete the island using /is delwarp?
> > > 
> > > 
> > > The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui
> > 
> > 
> > Is this warp in your database..?
> 
> No in db

Then after a restart, this warp is gone, am I correct?

**Comment by nivcoo** [comment] 2021-12-03 13:44
> > > > > What happens when you try to delete the island using /is delwarp?
> > > > 
> > > > 
> > > > The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui
> > > 
> > > 
> > > Is this warp in your database..?
> > 
> > 
> > No in db
> 
> Then after a restart, this warp is gone, am I correct?

Yes that's it

**Comment by OmerBenGera** [comment] 2021-12-03 13:56
> > > > > > What happens when you try to delete the island using /is delwarp?
> > > > > 
> > > > > 
> > > > > The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui
> > > > 
> > > > 
> > > > Is this warp in your database..?
> > > 
> > > 
> > > No in db
> > 
> > 
> > Then after a restart, this warp is gone, am I correct?
> 
> Yes that's it

Seems like players create them then and they are not registered correctly.
Do you know how they create the warps? using /is setwarp or using a sign?

**Comment by nivcoo** [comment] 2021-12-03 14:03
> > > > > > > What happens when you try to delete the island using /is delwarp?
> > > > > > 
> > > > > > 
> > > > > > The plugi doesn't tab complete the warp and return "warp not found" message but he stay in /is warp gui
> > > > > 
> > > > > 
> > > > > Is this warp in your database..?
> > > > 
> > > > 
> > > > No in db
> > > 
> > > 
> > > Then after a restart, this warp is gone, am I correct?
> > 
> > 
> > Yes that's it
> 
> Seems like players create them then and they are not registered correctly. Do you know how they create the warps? using /is setwarp or using a sign?

With /is setwarp command

**Comment by nivcoo** [comment] 2021-12-03 14:04
But for some other warp, only description and title disapear, and sometimes we can't be teleported on it

**Comment by UpInSmoke-NetherCraft** [comment] 2021-12-04 21:26
I can confirm I also have this issue on Paper 1.16.5 #786 w/ latest build of SuperiorSkyBlock

I have rebuilt "Dev" server on localhost of my SkyBlock svr w/ minimal plugins; just core stuff and pre-reqs, LuckPerms, ProtocolLib, PAPI, etc + SuperiorSkyblock.

Same issue...

From what I can tell if "player" (me) logs out at least 5 min after creating warp and server reboot does not happen until another 5 to 15 minutes, the warp will be saved....

However, if player is kicked pre-emptively prior to reboot or disconnects themselves within 5 min of reboot. The warp does not seem to be fully save in DB and is missing upon restart of server

Haven't done enough testing to confirm the above statement 100% but from initial testing this seems to be the case. Hope this helps.

**Comment by OmerBenGera** [comment] 2021-12-08 14:45
Should be fixed in latest build.

**Comment by OmerBenGera** [comment] 2021-12-11 15:03
Closing this for now
If it occurs again, lmk

**Closed by OmerBenGera** 2021-12-11 15:03 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
