### ISSUE TITLE
Permission, level error

### ISSUE THREAD

**Issue by Smart0926** [BG-Software-LLC/SuperiorSkyblock2#430] opened 2021-08-08 21:29 UTC
### Minecraft's Version

1.16.5

### Plugin's Version

1.7.0.jar 
203

### Describe the bug

There is a problem with the level in the latest version 1.7.0.jar. I placed many blocks and items on the island. When using /is level, there is no level and Lv.0 is displayed.

In the #203 version of the .jar development version, its level is normal, but there is a very serious bug, which is the permission bug. This permission error is not fixed in the latest version #1.7.0.jar. This problem is the most serious in version #203. In the #203 version, players can directly destroy other people's sky islands without passing the permission regulations. I don't know my situation. Which version to upgrade, because there are problems, the latest and old versions, but there are bugs

### To Reproduce

As explained above

**Comment by OmerBenGera** [comment] 2021-08-09 05:28
I dont know about any permission bug issue in build 203 and it should work well.
The temo fiz for now is to revert to 203 or disable /is level for now.

**Comment by OmerBenGera** [comment] 2021-08-09 05:28
Duplicate of #411

**Closed by OmerBenGera** 2021-08-09 05:28 UTC
Labels: Bug Report, Pending
