### ISSUE TITLE
CropGrowth [Upgrade] Issue

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/SuperiorSkyblock2#1092] opened 2022-05-02 03:59 UTC
### Minecraft's Version

This server is running Paper version git-Paper-"d3c1023" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d3c1023)
You are 49 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-216 (MC: 1.18.1)

### Plugin's Version

SuperiorSkyblock2 1.10.10 b625

### Describe the bug

So when i upgraded the island crop growth, there is a weird sugar_cane_block and wheat_seeds above x:150 or 125 kept spawning and generating an infinite amount of sugar canes and wheat seeds

### To Reproduce

/is create <name> [schem]

/is upgrade #Choose crop-growth upgrade the hoe and maxed it once you've done

start planting the seeds and the sugar cane...

### Additional Information

https://youtu.be/q151nvUvlDo

![image](https://user-images.githubusercontent.com/58950562/166182578-397e08b5-a187-4632-b188-af6000a9d746.png)

**Comment by OmerBenGera** [comment] 2022-05-02 06:25
Duplicate of #889

**Closed by OmerBenGera** 2022-05-02 06:25 UTC
Labels: Pending
