### ISSUE TITLE
Citizens island top placeholders.

### ISSUE THREAD

**Issue by Florens11** [BG-Software-LLC/SuperiorSkyblock2#1094] opened 2022-05-02 17:04 UTC
### Minecraft's Version

1.8.8 FoxSpigot

### Plugin's Version

1.10.0

### Describe the bug

I wanted to make a top leaderboard with citizens. But it wont update the skins. I had no idea why so i asked it in the citizens support discord. Where they said this: 
![image](https://user-images.githubusercontent.com/52450422/166291871-fcfc7240-d00f-44e9-a539-e41190c20947.png)

He also said:
"here's an example of one developer who fixed their placeholder with the same problem: https://github.com/PlaceholderAPI/SuperbVote-Expansion/commit/719bc4f546e340da4e70dba48df0addb3a7ebdd4"

### To Reproduce

Use citizens, create a npc and use /npc skin %superior_island_top_level_leader_1%

**Comment by OmerBenGera** [comment] 2022-05-02 17:19
Duplicate of #1090

**Closed by OmerBenGera** 2022-05-02 17:19 UTC
Labels: Pending
