### ISSUE TITLE
Top islands not responding and not sorting correctly

### ISSUE THREAD

**Issue by KasaiSora** [BG-Software-LLC/SuperiorSkyblock2#1527] opened 2022-12-28 19:57 UTC
### Minecraft's Version

1.18.2

### Plugin's Version

2022.9

### Describe the bug

When going to /is panel and then to top islands, the interface is not responding. All the sort methodes are not working and I can't switch between them. The top one, sort by value, is glowing. Though it's not sorting by value and a random player that just joined the server will be on top of the list.

### To Reproduce

Have about 6 players on your server, all with a different island level/value. This is when the sorting/interface stopped working for me

### Additional Information

https://youtu.be/wRhU7TTLeOo

Edit: When placing a block after the server has restarted, it get this log:
[21:51:23 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[21:51:23 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_18_R2' loaded!
[21:51:23 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[21:51:23 WARN]: [NBTAPI] [NBTAPI] The NBT-API located at 'package com.qualityplus.assistant.lib.de.tr7zw.changeme.nbtapi' seems to be outdated!
[21:51:23 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.10.0' Newest Version: 2.11.1'
[21:51:23 WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!

Don't know if it got anything to do with the issue

**Comment by OmerBenGera** [comment] 2022-12-28 21:21
Duplicate of #1514

**Closed by OmerBenGera** 2022-12-28 21:21 UTC
Labels: Pending
