### ISSUE TITLE
Not completing island creation

### ISSUE THREAD

**Issue by SalomonPicos** [BG-Software-LLC/SuperiorSkyblock2#1695] opened 2023-04-18 13:52 UTC
### Minecraft's Version

![immagine](https://user-images.githubusercontent.com/88857385/232798642-d824ec46-b5c2-48b3-9ee4-1fdd50a7b027.png)

### Plugin's Version

2023.1-b9

### Describe the bug

i updated to this version of the plugin and reseted both plugin's data and islands worlds and now, when i try to create a Island, it sends the "creating island.." message but nothing happens.

No errors in console, not during startup neither when creating island.

### To Reproduce

Create a island.

**Comment by WarnDa** [comment] 2023-04-26 06:24
Reason here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1686#issuecomment-1509855309

**Comment by OmerBenGera** [comment] 2023-04-28 08:06
Duplicate of #1686

**Closed by OmerBenGera** 2023-04-28 08:06 UTC
Labels: Pending
