### ISSUE TITLE
PlayerPortalEvent

### ISSUE THREAD

**Issue by Godinhooo** [BG-Software-LLC/SuperiorSkyblock2#2015] opened 2024-03-02 05:33 UTC
### Minecraft's Version

1.8.8

### Plugin's Version

SuperiorSkyblock2-2023.3

### Describe the bug

When trying to teleport to The End through the portal, it doesn't work and gives an error

### To Reproduce

Portal The end

### Additional Information

[02:23:27 ERROR]: Could not pass event PlayerPortalEvent to SuperiorSkyblock2 v2023.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.PlayerList.changeDimension(PlayerList.java:690) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.EntityPlayer.c(EntityPlayer.java:552) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:302) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:181) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:262) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1485) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:178) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:385) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:883) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:818) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:654) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$0(MinecraftServer.java:135) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException: destinationLocation cannot be null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        at com.bgsoftware.superiorskyblock.service.portals.PortalsManagerServiceImpl.handlePlayerPortal(PortalsManagerServiceImpl.java:74) ~[?:?]
        at com.bgsoftware.superiorskyblock.listener.PortalsListener.onPlayerPortal(PortalsListener.java:52) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[FlamePaper-1.1.1.jar:git-PaperSpigot-94ac179e]
        ... 25 more

**Comment by freddycor** [comment] 2024-03-07 19:48
If you're on Multiverse, you have to install Multiverse-NetherPortals and set it up. Fixed it for me

**Comment by Godinhooo** [comment] 2024-03-09 02:28
> If you're on Multiverse, you have to install Multiverse-NetherPortals and set it up. Fixed it for me

My friend, this comes at the right time, I went back to version 2023.1, but there were several bugs and dupes
Thank you very much, this fixed it, but I think the idea of not depending on many third-party plugins is cool.

**Comment by OmerBenGera** [comment] 2024-05-11 17:28
Duplicate of #2038

**Closed by OmerBenGera** 2024-05-11 17:28 UTC
Labels: Pending
