### ISSUE TITLE
bug with spawners

### ISSUE THREAD

**Issue by xsorencoolx** [BG-Software-LLC/SuperiorSkyblock2#1308] opened 2022-08-01 05:02 UTC
### Minecraft's Version

paper 1.16.5

### Plugin's Version

743 dev build

### Describe the bug

Hey so when i updated dev build from 724 to 743 most of my members' spawner turn into pig but worth of them is blaze
and i use wildstacker stable build i didnt have any problem before update but now i do reason i update was old issue that got fix when people go to nether there level go negative

### To Reproduce

updated plugin and this happend and lots of member reporting this to me

### Additional Information

![Screenshot (216)](https://user-images.githubusercontent.com/51112473/182075576-0b6a1d59-23a8-4e86-b77a-217ffe1f0c19.png)
![Screenshot (215)](https://user-images.githubusercontent.com/51112473/182075592-8891d248-6969-4842-bf36-ff5360b1b45a.png)

**Comment by xsorencoolx** [comment] 2022-08-03 03:23
ok i downgrade to 725 and i dont have any other reports for spawners but now they saying there is level are getting so low
i think the spawner problem is https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/e694ab56483edbe1696410ca239003baa7f220a6
on this update if i go under this update they will turn into pigs

**Comment by OmerBenGera** [comment] 2022-08-03 05:48
> ok i downgrade to 725 and i dont have any other reports for spawners but now they saying there is level are getting so low i think the spawner problem is [e694ab5](https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/e694ab56483edbe1696410ca239003baa7f220a6) on this update if i go under this update they will turn into pigs

Interesting, I will look into it.

**Comment by OmerBenGera** [comment] 2022-08-03 06:17
After some testings, it looks like an issue with ViaVersion.
I removed completely SuperiorSkyblock and it still happens, however once I removed ViaVersion it fixed itself.

I'll report it over them.

**Comment by xsorencoolx** [comment] 2022-08-03 14:59
still not fixed

**Comment by OmerBenGera** [comment] 2022-08-04 08:18
@xsorencoolx ViaVersion has pushed a new dev build that fixes the issue.
Can you test it out as well?
https://ci.viaversion.com/job/ViaVersion/633/

**Comment by xsorencoolx** [comment] 2022-08-04 16:22
ok i will tell you if its fixed

**Comment by xsorencoolx** [comment] 2022-08-05 05:24
ok i updated viaversion and ssb and most of my members spawner turn into pig again i did downgrade to  725

**Comment by OmerBenGera** [comment] 2022-08-05 06:41
> ok i updated viaversion and ssb and most of my members spawner turn into pig again i did downgrade to 725

When do the spawners turn into pigs?

**Comment by OmerBenGera** [comment] 2022-08-05 08:12
I tried it myself on 1.16.5 (just placed a spawner and let it spawn entities) and it stays the same.

**Comment by xsorencoolx** [comment] 2022-08-05 09:14
you use wildstacker last stable build?

**Comment by OmerBenGera** [comment] 2022-08-05 09:25
> you use wildstacker last stable build? and stack 10 spawners

I use WS latest dev build.

**Comment by OmerBenGera** [comment] 2022-08-05 09:26
Btw, this is SSB's issues tracker, not WildStacker.
Try it without any plugins but SSB, and check if the issue still occurs... If it doesn't, then we can close this.

**Comment by xsorencoolx** [comment] 2022-08-05 11:50
then can you please tell me whats the reason when i update ssb to last dev build my spawners will turn into pig randomly but in dev build 725 they dont?

**Comment by OmerBenGera** [comment] 2022-08-05 13:30
> then can you please tell me whats the reason when i update ssb to last dev build my spawners will turn into pig randomly but in dev build 725 they dont?

I don't know, that's what we try to find out.
Have you tried it with only SSB installed on your server?

**Comment by xsorencoolx** [comment] 2022-08-05 14:45
i did it didnt happened i said its randomly

**Comment by OmerBenGera** [comment] 2022-08-05 14:50
> i did it didnt happened i said its randomly

Try installing plugins one by one until it happens.

**Comment by OmerBenGera** [comment] 2022-08-05 20:20
> i did it didnt happened i said its randomly

Another person had the same issue and by updating ViaVersion it was fixed.

**Comment by OmerBenGera** [comment] 2022-08-05 20:59
The issue was confirmed by others, still trying to get it myself

**Comment by OmerBenGera** [comment] 2022-08-05 21:21
Check out latest dev build, let me know if it works now

**Comment by xsorencoolx** [comment] 2022-08-06 10:29
it seems its fixed if i have more report i will tell you

**Closed** 2022-08-06 10:38 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
