### ISSUE TITLE
WildStacker's custom flag doesn't work

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1147] opened 2022-04-05 01:29 UTC
### Minecraft's Version

  [Mon 20:26:16 INFO ] Current: git-Purpur-1586 (MC: 1.18.2)*

### Plugin's Version

  [Mon 20:27:19 INFO ] WildStacker version 3.7.0
  [Mon 20:27:19 INFO ] Stacking drops, entities, blocks and spawners into one object!
  [Mon 20:27:19 INFO ] Website: https://bg-software.com/
  [Mon 20:27:19 INFO ] Author: Ome_R

### Describe the bug

I have SuperiorSkyblock hook set to true in config for wildstacker, and have correctly added it to settings.yml, but gives me this error when reloading plugin/restarting server: https://pastebin.com/ATGiK9R1

### To Reproduce

Add menu item to settings.yml

### Additional Information

![C429D932-7878-458C-849D-CE267DFC309E](https://user-images.githubusercontent.com/65089425/161661528-be2d01fd-cb5e-4d24-ae94-58fdcb24521a.png)
![93AE4673-7A07-4404-990B-94947F951B34](https://user-images.githubusercontent.com/65089425/161661530-be9265e7-f3bd-464c-9224-d480fa3b0625.png)

**Comment by DuneSciFye** [comment] 2022-05-22 01:30
Still doesn't show up

**Comment by DuneSciFye** [comment] 2022-05-22 23:36
I'm on SuperiorSkyblock2 version 1.10.1.665

**Comment by OmerBenGera** [comment] 2022-05-27 09:30
I pushed a new update of WildStacker.

Update WS, start the server and send me logs.
It shouldn't fix the issue, however it should give more information on why it didn't occur.

**Comment by DuneSciFye** [comment] 2022-05-28 00:26
https://paste.helpch.at/bovucexoca.md Here you go

**Comment by OmerBenGera** [comment] 2022-05-28 07:45
You're still using WildStacker 3.7.0 - update it to 3.7.0.306 and send me new logs

**Comment by DuneSciFye** [comment] 2022-05-29 20:11
https://mclo.gs/RBzOdDF

**Comment by OmerBenGera** [comment] 2022-07-02 10:20
The issue is because WildStacker and SuperiorSkyblock conflicts with each other - SSB depends on WS while WS depends on SSB. This brings an issue as WildStacker needs to be loaded first so it can register its custom island flag, however that's not the case sometimes and SSB loads before WS.

I will see what can be done regarding this.

**Comment by OmerBenGera** [comment] 2022-07-02 10:30
Update WildStacker, let me know if it is fixed.

**Comment by OmerBenGera** [comment] 2022-07-14 17:18
Closing this for now
If it still occurs lmk

**Closed by OmerBenGera** 2022-07-14 17:18 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
