### ISSUE TITLE
there is a problem with the Custom Environment

### ISSUE THREAD

**Issue by xSavior-of-God** [BG-Software-LLC/SuperiorSkyblock2#247] opened 2021-05-09 22:58 UTC
**Minecraft's Version**
1.16

**Plugin's Version**: -
dev

**Describe the bug**
Hi Ome_R, how are you?
There is a bug related to Environment... some plugins can create their own custom Environment ( https://papermc.io/javadocs/paper/1.16/org/bukkit/World.Environment.html ), this causes errors, being that as I have noticed you tend to use the method "World.Environment.values()"
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/0ba33aac4a85bedec11ac05f8ca190913f33b4b7/src/main/java/com/bgsoftware/superiorskyblock/island/SIsland.java#L720

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/0ba33aac4a85bedec11ac05f8ca190913f33b4b7/src/main/java/com/bgsoftware/superiorskyblock/island/SIsland.java#L161
 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/island/SIsland.java

instead you should create a enum of your own 'Environment' for manage them.
Like this:
```JAVA
public enum Environment {
    NORMAL,
    NETHER,
    THE_END

}
```

All this to avoid errors caused by non-existent worlds of custom Environment type

**Comment by OmerBenGera** [comment] 2021-05-14 10:22
Why would it not work? I am using the Bukkit methods.
If paper doesn't support them, then it's an issue that they should address.

**Comment by OmerBenGera** [comment] 2021-05-14 12:05
I just tried replicating the issue but couldn't find an issue

**Comment by xSavior-of-God** [comment] 2021-05-14 12:08
Try it in 1.16.5 with paper (for example try to increase the radius of the island)

**Comment by OmerBenGera** [comment] 2021-05-14 13:03
How increasing the radius of the island has anything to do with that?

**Comment by OmerBenGera** [comment] 2021-05-14 13:03
I am not exactly sure what's the issue anyways so if you can explain it again it would be great

**Comment by xSavior-of-God** [comment] 2021-05-14 13:12
as you can see the "CUSTOM" evironment has been added in 1.16 (https://papermc.io/javadocs/paper/1.16/org/bukkit/World.Environment.html), the point is that being that you use the function in which you scroll all the Environments the error is that there is no island with custom Env. (this happens in my server with ASW, perhaps without it does not give the error)

**Comment by xSavior-of-God** [comment] 2021-05-14 13:13
if you give me 2h I will send you the error via pastebin

**Comment by xSavior-of-God** [comment] 2021-05-16 04:45
Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
this is the error relative of the command `/is admin setsize xSavior_of_God 100`
https://pastebin.com/pyHKqhPw

(_If you need it, I have a stable ASWM addon that you could use for testing_)

**Comment by OmerBenGera** [comment] 2021-05-16 05:45
> 
> 
> Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> https://pastebin.com/pyHKqhPw
> 
> (_If you need it, I have a stable ASWM addon that you could use for testing_)

I think SlimeWorldManager doesn't support CUSTOM as an environment

**Comment by xSavior-of-God** [comment] 2021-05-16 14:41
> > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > https://pastebin.com/pyHKqhPw
> > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> 
> I think SlimeWorldManager doesn't support CUSTOM as an environment

Ehm, i know, but why you need CUSTOM environment for an island?
`at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``

**Comment by OmerBenGera** [comment] 2021-05-16 15:47
> 
> 
> > > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > > https://pastebin.com/pyHKqhPw
> > > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> > 
> > 
> > I think SlimeWorldManager doesn't support CUSTOM as an environment
> 
> Ehm, i know, but why you need CUSTOM environment for an island?
> `at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``

I don't need it..?

**Comment by xSavior-of-God** [comment] 2021-05-16 16:30
> > > > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > > > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > > > https://pastebin.com/pyHKqhPw
> > > > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> > > 
> > > 
> > > I think SlimeWorldManager doesn't support CUSTOM as an environment
> > 
> > 
> > Ehm, i know, but why you need CUSTOM environment for an island?
> > `at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``
> 
> I don't need it..?

So, why you ask to ASWM the CUSTOM island world?
`at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:32)`

**Comment by OmerBenGera** [comment] 2021-05-16 18:53
> 
> 
> > > > > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > > > > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > > > > https://pastebin.com/pyHKqhPw
> > > > > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> > > > 
> > > > 
> > > > I think SlimeWorldManager doesn't support CUSTOM as an environment
> > > 
> > > 
> > > Ehm, i know, but why you need CUSTOM environment for an island?
> > > `at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``
> > 
> > 
> > I don't need it..?
> 
> So, why you ask to ASWM the CUSTOM island world?
> `at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:32)`

I don't... It asks for the environment of the world you want to get (nether, normal, the_end... also custom if they want)
I don't understand how the issue is related to SSB if SWM doesn't support the CUSTOM environment

**Comment by xSavior-of-God** [comment] 2021-05-16 19:36
> > > > > > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > > > > > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > > > > > https://pastebin.com/pyHKqhPw
> > > > > > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> > > > > 
> > > > > 
> > > > > I think SlimeWorldManager doesn't support CUSTOM as an environment
> > > > 
> > > > 
> > > > Ehm, i know, but why you need CUSTOM environment for an island?
> > > > `at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``
> > > 
> > > 
> > > I don't need it..?
> > 
> > 
> > So, why you ask to ASWM the CUSTOM island world?
> > `at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:32)`
> 
> I don't... It asks for the environment of the world you want to get (nether, normal, the_end... also custom if they want)
> I don't understand how the issue is related to SSB if SWM doesn't support the CUSTOM environment

I mean why are you asking for the CUSTOM environment when i type "/is admin setsize xSavior_of_God 100", if you only need normal, nether and the_end?

**Comment by OmerBenGera** [comment] 2021-05-17 07:01
> 
> 
> > > > > > > Sorry for the delay... I checked, and the problem persist only if I use the SlimeWorldManager addon
> > > > > > > this is the error relative of the command `/is admin setsize xSavior_of_God 100`
> > > > > > > https://pastebin.com/pyHKqhPw
> > > > > > > (_If you need it, I have a stable ASWM addon that you could use for testing_)
> > > > > > 
> > > > > > 
> > > > > > I think SlimeWorldManager doesn't support CUSTOM as an environment
> > > > > 
> > > > > 
> > > > > Ehm, i know, but why you need CUSTOM environment for an island?
> > > > > `at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.getIslandsWorld(ProvidersHandler.java:318)``
> > > > 
> > > > 
> > > > I don't need it..?
> > > 
> > > 
> > > So, why you ask to ASWM the CUSTOM island world?
> > > `at com.bgsoftware.ssbslimeworldmanager.SSBWorldManager$SlimeWorldsProvider.getIslandsWorld(SSBWorldManager.java:32)`
> > 
> > 
> > I don't... It asks for the environment of the world you want to get (nether, normal, the_end... also custom if they want)
> > I don't understand how the issue is related to SSB if SWM doesn't support the CUSTOM environment
> 
> I mean why are you asking for the CUSTOM environment when i type "/is admin setsize xSavior_of_God 100", if you only need normal, nether and the_end?

Because when you run setsize, there is logic that updates things in the island worlds, and a CUSTOM world environment can be a thing. I am closing this issue for now, it seems like the issue is with SWM.

**Closed by OmerBenGera** 2021-05-17 07:01 UTC
Labels: Bug Report, Further Investigation
