### ISSUE TITLE
Server crashing when someone joins

### ISSUE THREAD

**Issue by WaterArchery** [BG-Software-LLC/SuperiorSkyblock2#2067] opened 2024-05-01 09:12 UTC
### Minecraft's Version

Current: git-SlimeWorldManager-43 (MC: 1.20.4)*
Previous: git-SlimeWorldManager-15848 (MC: 1.20.4)
* Unknown version

I am using SlimeWorldManager With Purpur

### Plugin's Version

[12:11:33 INFO]: SuperiorSkyblock2 version 2023.3-b171

### Describe the bug

In very rare cases, when someone joins the server crashes with stacked block log. It happens nearly every day but I don’t think there is any trigger to do that. It just happens randomly.

Logs: https://mclo.gs/oJMxjsd

### To Reproduce

It is hard to reproduce because it happens randomly. 

Create a server with AdvancedSlimePurpur and SlimeWorldManager module
Place stacked block to your island
Quit server
Restart the server
Join the server

**Comment by OmerBenGera** [comment] 2024-05-11 11:21
The issue is due to ASP broke accessing to chunks data when it is loaded.
Check out latest dev build, let me know if it still occurs or not.

**Comment by OmerBenGera** [comment] 2024-05-11 13:22
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment] 2024-07-14 18:34
Closing this for now
If the issue still occurs, let me know

**Closed by OmerBenGera** 2024-07-14 18:34 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
