### ISSUE TITLE
Wrong return placeholder %superior_island_exists%

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#1279] opened 2022-07-18 17:05 UTC
### Minecraft's Version

1.19 - paper last build

### Plugin's Version

last dev build

### Describe the bug

When I try to parse the placeholder `%superior_island_exists%` with somes players I have the wrong return value.

This is my config file: "fr_FR"

PLACEHOLDER_NO: 'No'
PLACEHOLDER_YES: 'Yes'

When I parse the placeholder for me :
![image](https://user-images.githubusercontent.com/60007549/179564567-357553c2-e32f-4421-aad1-3b94431d71d3.png)

And for some guys:
![image](https://user-images.githubusercontent.com/60007549/179564616-160d61fe-88e6-4867-83b2-2b1bff6015ba.png)

We both have an island.

### To Reproduce

/papi parse PSEUDO %superior_island_exists%

**Comment by Teyir** [comment] 2022-07-18 17:06
Okey I have the error....

Sometimes the plugin get the en-US language file and not the good (fr-FR).

**Comment by Teyir** [comment] 2022-07-18 20:40
The player has 2 accounts and 1 account get get french translate et the other the en_US

**Comment by OmerBenGera** [comment] 2022-07-19 10:54
> The player has 2 accounts and 1 account get get french translate et the other the en_US

As I said, he might have changed his language to english using `/is lang` - so it doesnt matter how many accounts this player uses.

**Comment by OmerBenGera** [comment] 2022-07-19 10:55
Try it yourself - change your locale to english using `/is lang` and you'll see the same output as that player.

Anyways not a bug, so I am closing this

**Closed by OmerBenGera** 2022-07-19 10:55 UTC
Labels: Pending

**Comment by Teyir** [comment] 2022-07-20 11:12
> Try it yourself - change your locale to english using `/is lang` and you'll see the same output as that player.
> 
> Anyways not a bug, so I am closing this

After some investigation the player never using /is lang ...

**Comment by OmerBenGera** [comment] 2022-07-21 04:04
> > Try it yourself - change your locale to english using `/is lang` and you'll see the same output as that player.
> > Anyways not a bug, so I am closing this
> 
> After some investigation the player never using /is lang ...

Then tell him to use it so he change his language to french
