### ISSUE TITLE
Barrel Placement issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1033] opened 2022-04-03 18:51 UTC
### Minecraft's Version

1.18.2

### Plugin's Version

b579

### Describe the bug

Hello, i use the wildstacker barrel feature and i've this issue https://www.toptal.com/developers/hastebin/mesacifixe.properties (I send it here because the error start with ss2). After that wait minutes and the barrel will become a simple cauldron

### To Reproduce

Place barrel with wildstacker and ss2

**Comment by nivcoo** [comment] 2022-04-03 18:52
linked to barrel i've this error with inventory (Maybe linked) : https://www.toptal.com/developers/hastebin/ucarezolus.properties

**Comment by nivcoo** [comment] 2022-04-03 19:18
As we can see, here the cauldron is normal cauldron https://pics.revolis.fr/2022/04/03/21-17_mHud.png

**Comment by OmerBenGera** [comment] 2022-04-03 20:11
Duplicate of #1032

**Closed by OmerBenGera** 2022-04-03 20:11 UTC
Labels: Pending

**Comment by nivcoo** [comment] 2022-04-05 13:20
Isn't exactly the same issue because this one is barrel and the other is for spawner
