### ISSUE TITLE
Count of Blocs

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#633] opened 2021-09-28 11:43 UTC
### Minecraft's Version

1.12.2

### Plugin's Version

b318

### Describe the bug

Hello when i do /is admin count username i've this issue https://pics.revolis.fr/2021-09/28/13-42_vE2D.png

### To Reproduce

/is admin count username after /is recalc

**Comment by OmerBenGera** [comment] 2021-09-28 11:50
Does `/is admin recalc <player-name>` helps?
This issue should already been fixed in the build you use.

**Comment by nivcoo** [comment] 2021-09-28 11:51
No after /is admin recalc username i've the same issue

**Comment by nivcoo** [comment] 2021-09-28 14:50
In my db i've that : https://hastebin.com/ubuxikazuy.json for this island

**Comment by OmerBenGera** [comment] 2021-09-28 18:25
Weird, it should be fixed.
Are you able to replicate the issue on another island? If so, are you able to replicate it on another server with only SSB installed using default files?

**Comment by nivcoo** [comment] 2021-09-28 18:28
I've this issue with issue with all islands (I haven't this issue with previous version (Before the new db system)).

I join also @CryLegende or @MrCry (Idk the username) because he has the same issue on his server

**Comment by nivcoo** [comment] 2021-09-28 18:30
I've created new island and after that did /is recalc and i've that https://pics.revolis.fr/2021-09/28/20-29_ruNS.png

**Comment by CryLegende** [comment] 2021-09-28 22:43
I confirm the bug is on all islands and still here on a new island

**Comment by OmerBenGera** [comment] 2021-09-29 06:04
Are you able to replicate the issue on another server with default files?

**Comment by nivcoo** [comment] 2021-09-29 10:25
I haven't the issue with default files

**Comment by nivcoo** [comment] 2021-09-29 10:53
I know how to replicate the issue with default files ! And this issue create this issue : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/587 ! SO, you have to put block in "block-limits:" which isn't in level/worth file like piston. create new island, places pistons randomly like https://pics.revolis.fr/2021-09/29/12-52_rlf7.png after that restart the server. do /is recalc and /is count and you can have the issue, I will fix this by adding the missing blocks in the files of worth but before there was no this problem

**Comment by nivcoo** [comment] 2021-09-29 10:58
It's fixed the piston but not chest/double chest and enderchest and enchantement table : https://pics.revolis.fr/2021-09/29/12-58_FHKU.png https://pics.revolis.fr/2021-09/29/12-58_L9Tc.png

**Comment by nivcoo** [comment] 2021-09-29 11:01
When we place enderchest or chest/trappedchest into block-limits the count is bug

**Comment by nivcoo** [comment] 2021-09-29 11:17
> When we place enderchest or chest/trappedchest into block-limits the count is bug

Sorry this issue is fixed after the restart. To Conclude, now we have to put every block into block limit in level/worth files to fix this issue

**Comment by nivcoo** [comment] 2021-09-29 11:18
@CryLegende If you want you can put the block in you level file like that https://pics.revolis.fr/2021-09/29/13-18_oO8l.png

**Comment by CryLegende** [comment] 2021-09-29 11:19
I think all blocks that have a data depending on the positioning of the bloc (Like pistons, chests, log, stairs...)

**Comment by nivcoo** [comment] 2021-09-29 11:20
> I think all blocks that have a data depending on the positioning of the bloc (Like pistons, chests, log, stairs...) cause the problem

Yes but not, we have this issue with only blocks in "block-limits" so it's linked with that. Try like me and let me know

**Comment by nivcoo** [comment] 2021-09-29 11:22
Because if you don't set value in worth file the plugin doesn't display the block into /is count but with "block-limits" yes so i think it's an issue with that

**Comment by CryLegende** [comment] 2021-09-29 11:29
> Because if you don't set value in worth file the plugin doesn't display the block into /is count but with "block-limits" yes so i think it's an issue with that

My worth file is empty since the beginning of my servers and my /is count was always working fine until this bug

**Comment by nivcoo** [comment] 2021-09-29 11:31
> > Because if you don't set value in worth file the plugin doesn't display the block into /is count but with "block-limits" yes so i think it's an issue with that
> 
> My worth file is empty since the beginning of my servers and my /is count was always working fine until this bug

For me also but it's a new issue and we can fix this issue like that temporarily

**Comment by OmerBenGera** [comment] 2021-10-01 11:11
Check out latest dev build, hopefully it's fixed.
You don't have to set the blocks of your limits in the worth value anymore.

**Comment by nivcoo** [comment] 2021-10-01 11:17
It works thx

**Comment by OmerBenGera** [comment] 2021-10-01 11:45
Great, everything works now as intended?

**Comment by CryLegende** [comment] 2021-10-02 00:30
Work fine on the latest build for me too

**Comment by OmerBenGera** [comment] 2021-10-02 08:00
Perfect!

**Closed by OmerBenGera** 2021-10-02 08:00 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
