### ISSUE TITLE
Island calculation 

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#442] opened 2021-08-13 14:10 UTC
### Minecraft's Version

1.12.2

### Plugin's Version

B215

### Describe the bug

Hello, the update doesn't works : https://pics.revolis.fr/2021-08/13/13-57_ibnQ.png when i do /is level i have always this message, also with is admin recalc username

### To Reproduce

Execute /is level or /is admin recalc username

**Comment by OmerBenGera** [comment] 2021-08-14 10:51
I can't seem to replicate the issue.
Are you able to replicate it on a server with only SSB installed?

**Comment by nivcoo** [comment] 2021-08-14 10:51
I have wildstacker also

**Comment by OmerBenGera** [comment] 2021-08-14 10:59
> 
> 
> I have wildstacker also

Weird, as I tested it with WildStacker as well.
Are you able to replicate it with only SSB and WS installed on your server?

**Comment by nivcoo** [comment] 2021-08-14 11:01
I will try that sunday

**Comment by nivcoo** [comment] 2021-08-15 14:13
I've tried and same with only superior/wildstacker, and i can't interract with my island so

**Comment by nivcoo** [comment] 2021-08-15 14:59
I've print the map and i've : https://pics.revolis.fr/2021-08/15/16-57_qmF6.png [Not completed] before the : chunksToLoad.forEachCompleted so maybe the issue is here

**Comment by OmerBenGera** [comment] 2021-08-15 18:14
let me know how to replicate it.

**Comment by OmerBenGera** [comment] 2021-08-15 18:15
also, which map did you print?

**Comment by nivcoo** [comment] 2021-08-15 18:16
I print chunksToLoad

**Comment by OmerBenGera** [comment] 2021-08-15 18:19
so for no reason, the plugin is not loading chunks for you. Show me this section of your config:
```
# How many chunks should be loaded in one tick by SuperiorSkyblock?
chunks-per-tick: 10
```

**Comment by nivcoo** [comment] 2021-08-15 18:20
https://pics.revolis.fr/2021-08/15/20-19_DP62.png it works correctly with previous version of chunk calculation but i have to have the latest

**Comment by OmerBenGera** [comment] 2021-08-15 18:21
does it work without WildStacker being installed?

**Comment by nivcoo** [comment] 2021-08-15 18:21
I will try it now

**Comment by nivcoo** [comment] 2021-08-15 18:23
No it doesn't works also without ws

**Comment by OmerBenGera** [comment] 2021-08-15 18:24
I think there are issues with loading chunks on your server, as it seems like the plugin doesn't load them for no reason.

**Comment by OmerBenGera** [comment] 2021-08-15 18:24
Make sure you use Paper 1.12.2 and not regular spigot, should help.

**Comment by nivcoo** [comment] 2021-08-15 18:25
I've only, Superiorskyblock and viaversion, 
it works very well with build b203 why the new method will change that? I use kspigot (i sent you the jar previously on discord i think)

**Comment by OmerBenGera** [comment] 2021-08-15 18:32
> 
> 
> I've only, Superiorskyblock and viaversion,
> it works very well with build b203 why the new method will change that? I use kspigot (i sent you the jar previously on discord i think)

I don't know why it doesn't work for you. Try adding debug messages or something and find the cause of it.

**Comment by nivcoo** [comment] 2021-08-15 18:33
Can I send my complete config for testing? (discord by preference)

**Comment by nivcoo** [comment] 2021-08-15 18:34
I've /is reset and /is create and after /is level and i've one error https://pics.revolis.fr/2021-08/15/20-34_LWK9.png

**Comment by nivcoo** [comment] 2021-08-15 18:35
https://hastebin.com/iwocifacod.properties

**Comment by OmerBenGera** [comment] 2021-08-15 18:37
> 
> 
> I've /is reset and /is create and after /is level and i've one error https://pics.revolis.fr/2021-08/15/20-34_LWK9.png

then of course it doesn't work, you have an error...
It's fixed in latest dev build

**Closed** 2021-08-15 18:38 UTC
Labels: Bug Report, Further Investigation

**Comment by nivcoo** [comment] 2021-08-15 18:40
It's strange because before /is reset i haven't error but it' works !! Thx you so much, you do very good work on your plugins
