### ISSUE TITLE
when a player creates an island the server has a chance to crash

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#400] opened 2021-07-26 21:15 UTC
### Minecraft's Version

paper-1.17.1-133

### Plugin's Version

SuperiorSkyblock2-b199.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

[21:07:50 INFO]: GuardianRei issued server command: /is
[21:07:51 INFO]: UUID of player Nex is cd4d8f52-0eae-38dc-8ab6-acbdb2617969
>....[1783.882s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1783.883s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[21:07:52 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[21:07:52 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[21:07:52 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:07:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[1783.939s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1783.939s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[21:07:52 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[21:07:52 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[21:07:52 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:07:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>....[1784.010s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1784.011s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[21:07:52 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[21:07:52 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[21:07:52 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:07:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:07:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:07:52 INFO]: Nex[/172.18.0.1:40376] logged in with entity id 5579 at ([SuperiorWorld]-2979.764375548616, 96.81290757981593, 20.296910845706392)

### To Reproduce

/is

### Additional Information

when it reaches about 20 - 30 players and if someone enters and creates an island it has a chance of crashing my server is a dedicated i7 9° SSD 480, 64GB RAM, I saw someone saying this on discord /is even questioned but now I know that this is really causing the server to crash after 30 minutes or 1 hour, I have removed all plugins and really confirmed that it is the SuperiorSkyBlock

It also happens when you change the biome of the island and it crashes if there are 10-20 people on it, but I removed this option, so I came up with the other option of /is when I create an island and the server shows this message and has a high chance of crashing.

server does not stay online for 2 hours and crashes and the server has 12gb of ram

(47): AdvancedOreGen, AntiCraft, AntiCreeper*, AntiCurse, AuctionHouse, BottledExp, ChestCommands, ChestShop, CMILib, CrazyCrates, DinoVoteRewards*, EpicHoppers, Essentials, EssentialsSpawn, HolographicDisplays, IllegalStack, ImageMaps, Legendchat*, LuckPerms, MarriageMaster, mcMMO, Multiverse-Core, nChat, NoPlugins, PixelVip*, PlaceholderAPI, PlayerPoints, PlugMan, ProtocolLib, ShopGUIPlus, SilkSpawners, SimpleClans, SuperiorSkyblock2, TAB, UberEnchant, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidTeleport, Votifier, WildChests, WildStacker, WildTools, Wither*, WorldEdit, WorldGuard

**Comment by OmerBenGera** [comment] 2021-07-28 21:08
Duplicate of #404

**Closed by OmerBenGera** 2021-07-28 21:08 UTC
Labels: Bug Report, Pending
