### ISSUE TITLE
How do I restart a player completely?

### ISSUE THREAD

**Issue by kamronalexander** [BG-Software-LLC/SuperiorSkyblock2#892] opened 2022-01-29 08:26 UTC
### Minecraft's Version

1.16.4

### Plugin's Version

lastest

### Describe the bug

Cant reset a player completely

### To Reproduce

unknown

**Comment by OmerBenGera** [comment] 2022-01-29 09:15
What do you mean?
What is there to reset in a player?

**Comment by OmerBenGera** [comment] 2022-01-29 09:15
Also, this is not a bug, so I am closing this.
You can still comment here or ask on the discord server.

**Closed by OmerBenGera** 2022-01-29 09:15 UTC
Labels: Pending
