### ISSUE TITLE
Skinrestorer

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#939] opened 2022-02-20 16:33 UTC
### Minecraft's Version

Purpur-1561 (MC: 1.18.1)

### Plugin's Version

SuperiorSkyblock2-1.8.4-b523

(since 1.8.4)

### Describe the bug

Skinrestorer dont work with SS2 (/island top)

Im using skinrestorer in bungeecord and spigot side

### To Reproduce

Server offline mode, use skin restorer and check /island top

### Additional Information

![154612375-ec0a0bd5-50d9-406a-aab7-1d813f2f12a4](https://user-images.githubusercontent.com/98712497/154853305-da7aacab-e831-483e-a706-782b64f7fe4e.png)
![154612372-5d13a3a2-46d8-4e42-ae70-fa637572ea17](https://user-images.githubusercontent.com/98712497/154853310-f10d4af7-2d66-410f-88d1-5ee9cda26020.png)

**Comment by OmerBenGera** [comment] 2022-02-20 17:37
Duplicate of #936

**Closed by OmerBenGera** 2022-02-20 17:37 UTC
Labels: Pending
