### ISSUE TITLE
bug about island level

### ISSUE THREAD

**Issue by herobrinein** [BG-Software-LLC/SuperiorSkyblock2#1832] opened 2023-08-05 12:14 UTC
### Minecraft's Version

1.20.1 purpur

### Plugin's Version

v2023.2

### Describe the bug

The numerical calculation of island values seems problematic. Sometimes the player's island value changes quickly, even with the naked eye, but at the beginning of the refresh, the value after the refresh is very different from the value before the refresh.

### To Reproduce

[19:25:45 INFO]: [✰-2,178,036] 服主||Herobrine_CN ➜ s
[19:26:14 INFO]: [✰-2,178,033] 服主||Herobrine_CN ➜ look this
[19:26:20 INFO]: [✰-2,178,033] 服主||Herobrine_CN ➜ the island level
[19:26:33 INFO]: [✰-2,178,063] 服主||Herobrine_CN ➜ and i will run a command
[19:26:40 INFO]: Herobrine_CN issued server command: /is level
[19:26:50 INFO]: [✰1.96K] 服主||Herobrine_CN ➜ so what happend?

**Comment by OmerBenGera** [comment] 2023-08-05 13:31
Island level and worth values are affected when blocks are placed or broken on your island.
Run `/is admin debug block_place` and `/is admin debug block_break` and find out what makes the values to change.

This is probably not a bug, therefore I am closing this.

**Closed by OmerBenGera** 2023-08-05 13:31 UTC
Labels: Pending
