### ISSUE TITLE
Island level not counting well

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#1399] opened 2022-10-06 13:12 UTC
### Minecraft's Version

1.8.8

### Plugin's Version

Latest dev build, 849

### Describe the bug

Hello, so when players put valued blocks that were modified on blockvalues folder, level isn't counting well, players put dragon eggs for example, and when typing /is level, they lose the level that this dragon egg was giving.

Seems that more people are having this issue on discord group.

Thanks! 

### To Reproduce

Not mine, it's a image from discord group, but you should do /is level after placing valued blocks

https://cdn.discordapp.com/attachments/554282577322704896/1027502755432103977/unknown.png

**Comment by OmerBenGera** [comment] 2022-10-06 16:30
Duplicate of #1396

**Closed by OmerBenGera** 2022-10-06 16:30 UTC
Labels: Pending

**Comment by ArefyNetwork** [comment] 2022-10-06 16:34
Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)

And then take a look on /is values, so weird
https://www.youtube.com/watch?v=j3h89tCjRkg
