### ISSUE TITLE
Placeholders mistake

### ISSUE THREAD

**Issue by Cr4zyGeek** [BG-Software-LLC/SuperiorSkyblock2#1304] opened 2022-07-29 16:48 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

SuperiorSkyblock2-1.11.0-b731

### Describe the bug

Placeholders that display numerical values containing commas are displaying invalid character.

### To Reproduce

-

### Additional Information

![image](https://user-images.githubusercontent.com/67514681/181806034-63812760-ed61-47c7-a329-7abe109d0b57.png)

**Comment by OmerBenGera** [comment] 2022-07-29 17:36
Change your numbers-format in the config file to something that is not broken.
Not a bug, closing.

**Closed by OmerBenGera** 2022-07-29 17:36 UTC
Labels: Pending

**Comment by Cr4zyGeek** [comment] 2022-07-29 18:35
Oops, I was searching for something like that in all config files but I'm blind sorry :$

**Comment by OmerBenGera** [comment] 2022-07-29 18:43
> Oops, I was searching for something like that in all config files but I'm blind sorry :$

All's good :)
