### ISSUE TITLE
Sync Chunk Load Event lag in the End World

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#639] opened 2021-10-02 00:17 UTC
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b252

### Describe the bug

When i teleport on the End island calls Sync Chunk Load Event and drop tps for 2-3 secs
(Dragon Fight is enabled btw)
[Timings Screenshot](https://imgur.com/9LxtReg)

### To Reproduce

Teleport on End island

**Comment by OmerBenGera** [comment] 2021-10-02 08:00
This lag is caused by loading chunks in the end, this has nothing to do with the plugin.
If you believe there is something to do with the plugin, take a spark profiler when the lag occurs and send it here.
For now, I am closing this.

**Closed by OmerBenGera** 2021-10-02 08:00 UTC
Labels: Pending

**Comment by exzolink** [comment] 2021-10-05 13:41
Fixed with sync-chunk-writes false in server.properties
