### ISSUE TITLE
New players cant create islands

### ISSUE THREAD

**Issue by WaterArchery** [BG-Software-LLC/SuperiorSkyblock2#1689] opened 2023-04-15 15:14 UTC
### Minecraft's Version

1.18.2 purpur

### Plugin's Version

Latest dev build

### Describe the bug

When player creates an island, all of the players getting leader on the new island. They are creating 1 island and the others who create after that not creates island they become the leader of the previous island.

### To Reproduce

Create island with 2 account 

### Additional Information

![989B5432-9409-4747-A5C8-0DAB2EF780A4](https://user-images.githubusercontent.com/64959220/232233333-653b7b77-4906-469c-8794-043db5d5a41c.png)

**Comment by WarnDa** [comment] 2023-04-26 06:24
Reason here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1686#issuecomment-1509855309

**Comment by OmerBenGera** [comment] 2023-04-28 08:06
Duplicate of #1686

**Closed by OmerBenGera** 2023-04-28 08:06 UTC
Labels: Pending
