### ISSUE TITLE
Table stacked_blocks in MySQL is too short

### ISSUE THREAD

**Issue by flamingomg** [BG-Software-LLC/SuperiorSkyblock2#730] opened 2021-11-14 06:20 UTC
### Minecraft's Version

1.16.5

### Plugin's Version

lastest dev build

### Session Logs

[06:35:23] [SuperiorSkyblock Database Thread 0/INFO]: [SuperiorSkyblock2] Failed to execute query REPLACE INTO ssstacked_blocks (`location`,`amount`,`block_type`) VALUES(SuperiorWorld, -3008, 101, 7799,4672,IRON_BLOCK:0);
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'location' at row 1
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.database.sql.StatementHolder.lambda$execute$4(StatementHolder.java:104)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.database.sql.SQLSession.buildStatement(SQLSession.java:186)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.database.sql.SQLHelper.buildStatement(SQLHelper.java:52)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.database.sql.StatementHolder.execute(StatementHolder.java:99)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at com.bgsoftware.superiorskyblock.database.sql.StatementHolder.lambda$execute$3(StatementHolder.java:88)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[06:35:23] [SuperiorSkyblock Database Thread 0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

### Describe the bug

spam print in console

### To Reproduce

last version of dev build

**Comment by OmerBenGera** [comment] 2021-11-14 07:04
Duplicate of #685

**Comment by flamingomg** [comment] 2021-11-14 07:06
this has nothing to do with the database conversion, the mysql database is new.

**Comment by OmerBenGera** [comment] 2021-11-15 12:45
There is an issue with creating the stacked_blocks table, you are correct.
I will look into that this weekend.
Sorry about that.

**Comment by Skizzles** [comment] 2021-11-15 12:46
stacked_blocks has location set to varchar(30) and yours is setting location to 31 which is causing the issue.

(Added details for when you are available Omer)

**Comment by flamingomg** [comment] 2021-11-18 12:26
> stacked_blocks has location set to varchar(30) and yours is setting location to 31 which is causing the issue.
> 
> (Added details for when you are available Omer)

how may i change the vatchar?

**Comment by OmerBenGera** [comment] 2021-11-18 14:41
> > stacked_blocks has location set to varchar(30) and yours is setting location to 31 which is causing the issue.
> > (Added details for when you are available Omer)
> 
> how may i change the vatchar?

Dont worry about it, I will do that on the plugin's side.

**Comment by OmerBenGera** [comment] 2021-11-18 21:29
Fixed in latest build

**Closed by OmerBenGera** 2021-11-18 21:29 UTC
Labels: ✔️ Confirmed
