### ISSUE TITLE
IslandWorthUpdateEvent

### ISSUE THREAD

**Issue by tindz123** [BG-Software-LLC/SuperiorSkyblock2#693] opened 2021-11-01 06:01 UTC
### Minecraft's Version

1.16.5 and paper

### Plugin's Version

SuperiorSkyblock2-1.8-b338

### Describe the bug

When the member broke some blocks on their island, the console spammed a lot of lines 
Could not pass event IslandWorthUpdateEvent to SuperiorSkyblock2 v1.8-DEVb338
java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget from class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator (org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @108fa0dc; org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator is in unnamed module of loader com.bgsoftware.superiorskyblock.module.ModuleClassLoader @325b2950)
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.createJumpTarget(LocalVariableTypesCalculator.java:419) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.getOrCreateJumpTarget(LocalVariableTypesCalculator.java:1196) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1234) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1230) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:457) ~[?:?]
        at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:461) ~[?:?]
        at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpressionOnEmptyStack(LocalVariableTypesCalculator.java:598) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterExpressionStatement(LocalVariableTypesCalculator.java:580) ~[?:?]
        at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase$LocalVariableTypeCalculationPhase.transform(CompilationPhase.java:277) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1531) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1451) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:761) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
        at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:210) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:196) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:187) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor920.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-788]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-788]
        at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandWorthUpdateEvent(EventsCaller.java:174) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$saveBlockCounts$62(SIsland.java:1904) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-788]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-788]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

*Full logs: https://pastebin.com/fsQ4sN3x

### To Reproduce

And when the member stops smashing blocks and ores, it stops too

**Comment by OmerBenGera** [comment] 2021-11-04 15:33
Duplicate of #371

**Closed by OmerBenGera** 2021-11-04 15:33 UTC
Labels: Pending
