### ISSUE TITLE
Spawners turns into pig spawner on chunk unload

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1391] opened 2022-10-02 10:50 UTC
### Minecraft's Version

1.16.5

### Plugin's Version

832

### Describe the bug

Spawners turns into pig spawner on chunk unload
Bug appear after 805 update
(Spawners from Slimefun)

### To Reproduce

Place spawner with not a pig and rejoin server

**Comment by OmerBenGera** [comment] 2022-10-02 14:21
I am using 
```
This server is running Paper version git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```
I tried replicating the issue using vanilla spawners (I gave myself cow spawners using WildStacker) and unloaded my island chunks. When I came back the spawners stayed as cows.
Try it yourself on a server with only SSB installed (use other spawners that are not Slimefun's).
If the issue doesn't occur but only occurs with Slimefun, we can say the issue is Slimefun's.

**Comment by exzolink** [comment] 2022-10-02 14:37
> I am using
> 
> ```
> This server is running Paper version git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
> ```
> 
> I tried replicating the issue using vanilla spawners (I gave myself cow spawners using WildStacker) and unloaded my island chunks. When I came back the spawners stayed as cows. Try it yourself on a server with only SSB installed (use other spawners that are not Slimefun's). If the issue doesn't occur but only occurs with Slimefun, we can say the issue is Slimefun's.

Thats how slimefun spawners work
https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/AbstractMonsterSpawner.java#L79

**Comment by OmerBenGera** [comment] 2022-10-02 14:47
> 

How do I give myself a spawner?

**Comment by exzolink** [comment] 2022-10-02 14:50
> How do I give myself a spawner?

Oh, you need to break a spawner with a pickaxe of containment and then repair it on ancient altar
If you want you can join my server and i will give you already repaired spawner

**Comment by OmerBenGera** [comment] 2022-10-02 14:56
> > How do I give myself a spawner?
> 
> Oh, you need to break a spawner with a pickaxe of containment and then repair it on ancient altar, you cant give spawner with a command. If you want you can join my server and i will give you already repaired spawner

That's fine, gonna do that by myself :)

**Comment by OmerBenGera** [comment] 2022-10-02 15:10
I can't replicate the issue, looks fine for me.

**Comment by exzolink** [comment] 2022-10-02 15:48
> I can't replicate the issue, seems fine for me. Mind taking a video of the issue?

https://disk.yandex.ru/d/DbITaeHJDUheQA

**Comment by exzolink** [comment] 2022-10-02 15:50
Only after 805 update

**Comment by OmerBenGera** [comment] 2022-10-02 16:08
What spigot jar do you use?
The exact output of /version please.

**Comment by exzolink** [comment] 2022-10-02 16:22
This server is running Airplane version git-Airplane-11 (MC: 1.16.5) Kibble 1.7.1* (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version

**Comment by OmerBenGera** [comment] 2022-10-02 16:26
> This server is running Airplane version git-Airplane-11 (MC: 1.16.5) Kibble 1.7.1* (Implementing API version 1.16.5-R0.1-SNAPSHOT) Unknown version

Try using Paper, let me know if it works (even on another server)

**Comment by exzolink** [comment] 2022-10-02 16:31
> > This server is running Airplane version git-Airplane-11 (MC: 1.16.5) Kibble 1.7.1* (Implementing API version 1.16.5-R0.1-SNAPSHOT) Unknown version
> 
> Try using Paper, let me know if it works (even on another server)

Installed paper 1.16.5, bug is gone

**Comment by OmerBenGera** [comment] 2022-10-02 16:33
> > > This server is running Airplane version git-Airplane-11 (MC: 1.16.5) Kibble 1.7.1* (Implementing API version 1.16.5-R0.1-SNAPSHOT) Unknown version
> > 
> > 
> > Try using Paper, let me know if it works (even on another server)
> 
> Installed paper 1.16.5, bug is gone

Probably a compatibility issue with Airplane.
I can't download Airplane as their website doesn't respond - mind giving me a copy of the jar over discord?

**Comment by exzolink** [comment] 2022-10-02 16:34
ExZo#8155

**Comment by OmerBenGera** [comment] 2022-10-02 16:45
I could replicate the issue with Airplane.

**Comment by OmerBenGera** [comment] 2022-10-02 17:00
Fixed in latest dev build

**Closed by OmerBenGera** 2022-10-02 17:00 UTC
Labels: ✔️ Confirmed

**Comment by exzolink** [comment] 2022-10-02 17:03
Thank you!
