### ISSUE TITLE
Server in constant restart loop

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#886] opened 2022-01-26 22:28 UTC
### Minecraft's Version

I can’t get the server to start long enough to run any commands as it immediately goes to stopping, but it’s Purpur 1.17.1

### Plugin's Version

SuperiorSkyblock2-1.8.2-b391.jar

### Describe the bug

I get this issue when I start my server, and it restarts my server the moment it everything is running, putting it in an infinite restart loop https://pastebin.com/VDWUkV6f

### To Reproduce

Start the server

### Additional Information

Entire startup log: https://pastebin.com/6hnMGki2

**Comment by OmerBenGera** [comment] 2022-01-27 10:02
Update SSB, let me know if it still occurs.

**Comment by DuneSciFye** [comment] 2022-01-27 12:01
Just updated to build 494, uploaded the plugin and restarted the server, but still same thing. 
![Uploading E5A26471-383E-4AC1-8296-872F6C582AEE.png…]()

**Comment by DuneSciFye** [comment] 2022-01-27 12:06
Here is the error: https://pastebin.com/bh2Xx2UW

**Comment by OmerBenGera** [comment] 2022-01-27 17:19
Duplicate of #879

**Closed by OmerBenGera** 2022-01-27 17:19 UTC
Labels: 📝 Missing information, ❌ Unconfirmed
