### ISSUE TITLE
Error /is warp ( because "islandWarp" is null)

### ISSUE THREAD

**Issue by TunanaX** [BG-Software-LLC/SuperiorSkyblock2#1699] opened 2023-04-26 03:25 UTC
### Minecraft's Version

paper-1.12.2-1620.jar

### Plugin's Version

SuperiorSkyblock2-2023.1.jar

### Describe the bug

[SuperiorSkyblock2] Task #1939 for SuperiorSkyblock2 v2023.1 generated an exception
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.island.warps.IslandWarp.getName()" because "islandWarp" is null

Could not pass event InventoryClickEvent to SuperiorSkyblock2 v2023.1
org.bukkit.event.EventException: null

### To Reproduce

Open menu /is warp not /is warps
left click or right on the cell in the warp menu
will cause an error on the console

### Additional Information

https://pastes.dev/i5kZf33WYJ
https://www.youtube.com/watch?v=bqKp3F2Z4WA

**Comment by OmerBenGera** [comment] 2023-04-28 10:47
Duplicate of #1691 1691

**Closed by OmerBenGera** 2023-04-28 10:47 UTC
Labels: Pending
