### ISSUE TITLE
Ultimate Stacker and Block limit

### ISSUE THREAD

**Issue by xEllesi** [BG-Software-LLC/SuperiorSkyblock2#340] opened 2021-07-04 21:09 UTC
**Minecraft's Version**
This server is running Tuinity version git-Tuinity-"f88659c" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
Dev #177

**Describe the bug**
More than spawners permited on the island

**To Reproduce**
So i have 2 max spawners in my island if i put 1 spawner and them stack, i can put more 2 spawners on the ground, just doing that i have infinity spawners i can put

**Additional information**

**Comment by OmerBenGera** [comment] 2021-07-07 15:50
The issue is that you can exceed block limits?
If so, what plugin are you using for stacking the spawners and blocks?

**Comment by xEllesi** [comment] 2021-07-08 09:22
Yes it exceed, i use ultimate stacker

**Comment by OmerBenGera** [comment] 2021-07-08 15:02
It works flawlessly fine for me.
Make sure you have set a limit for spawners using /is admin setblocklimit <> SPAWNER:<type> <limit>

**Comment by OmerBenGera** [comment] 2021-07-08 15:25
Fixed in latest dev build :)

**Closed by OmerBenGera** 2021-07-08 15:25 UTC
Labels: Bug Report, Further Investigation
