### ISSUE TITLE
Cannot invoke "java.util.Locale.getLanguage()" because "userLocale" is null

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#879] opened 2022-01-25 14:42 UTC
### Minecraft's Version

1.18.1 (pufferfish b-37)

### Plugin's Version

1.8.3 -b488

Modules:
DiscordStatistics: -b5
NashornEngine: -b4

### Describe the bug

When I start the server I have this error:

`>.... [15:38:29 WARN]: [SuperiorSkyblock2] Task #64 for SuperiorSkyblock2 v1.8.3.488 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.Locale.getLanguage()" because "userLocale" is null
at com.bgsoftware.superiorskyblock.database.bridge.PlayersDatabaseBridge.insertPlayer(PlayersDatabaseBridge.java:101) ~[SuperiorSkyblock2-1.8.3-b488.jar:?]
at com.bgsoftware.superiorskyblock.player.PlayersHandler.getSuperiorPlayer(PlayersHandler.java:61) ~[SuperiorSkyblock2-1.8.3-b488.jar:?]
at com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.getPlayer(SuperiorSkyblockAPI.java:52) ~[SuperiorSkyblock2-1.8.3-b488.jar:?]
at com.bgsoftware.superiorskyblock.missions.BlocksMissions.loadProgress(BlocksMissions.java:142) ~[?:?]
at com.bgsoftware.superiorskyblock.mission.MissionsHandler.loadMissionsData(MissionsHandler.java:360) ~[SuperiorSkyblock2-1.8.3-b488.jar:?]
at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.lambda$onEnable$0(MissionsModule.java:138) ~[SuperiorSkyblock2-1.8.3-b488.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

And the server stop

### To Reproduce

Just start the server.

**Comment by Teyir** [comment] 2022-01-25 14:44
And if I remove the Discord Statistics module I don't have any error

**Comment by OmerBenGera** [comment] 2022-01-25 15:29
Did you delete your database?

**Comment by Teyir** [comment] 2022-01-25 17:56
No

**Comment by OmerBenGera** [comment] 2022-01-25 17:58
Your missions data is loaded and tries to load a non-existing player.
This can happen only if you have your missions data saving data for players that don't exist in the database...

**Comment by OmerBenGera** [comment] 2022-01-25 18:02
Please upload your entire logs file to pastebin and send it here as well.

**Comment by DuneSciFye** [comment] 2022-01-26 15:38
I also got this issue: https://pastebin.com/VDWUkV6f

My entire log is here: https://pastebin.com/6hnMGki2

**Comment by OmerBenGera** [comment] 2022-01-26 21:18
> 

Are you associated with @Teyir ..?

**Comment by DuneSciFye** [comment] 2022-01-26 22:20
No I’m not, I was going to report this issue but saw someone already posted the issue, so I just wanted to say I also got the error

**Comment by DuneSciFye** [comment] 2022-01-26 22:23
And I just looked and the error is actually different 😅
I thought it was the same one because I remembered “is null” and the server crashing over and over, which is the same as his issue. My fault, I’ll make a separate issue

**Comment by DuneSciFye** [comment] 2022-01-27 19:42
Is this still unconfirmed?

**Comment by OmerBenGera** [comment] 2022-01-27 19:50
> Is this still unconfirmed?

As I said before, this happens because you deleted the database and didn't wipe missions data.
It tries to retrieve data of an unknown player, which causes this error.

If you don't think that's case, try replicating the issue on another server.

**Comment by DuneSciFye** [comment] 2022-01-27 20:12
I’ve never messed with the database, it was working fine, with my server auto restarting every day, and then yesterday this happened

**Comment by OmerBenGera** [comment] 2022-01-27 20:14
> I’ve never messed with the database, it was working fine, with my server auto restarting every day, and then yesterday this happened

Send me entire logs with the error in them.

**Comment by DuneSciFye** [comment] 2022-01-27 20:19
This is the entire log from when I start the server to when it automatically restarts: https://pastebin.com/6hnMGki2

**Comment by OmerBenGera** [comment] 2022-01-27 20:20
> This is the entire log from when I start the server to when it automatically restarts: https://pastebin.com/6hnMGki2

This logs contains the error from a really old version.
Use latest dev build and send me a new logs containing the error.

**Comment by DuneSciFye** [comment] 2022-01-27 23:04
Here is a new one: https://pastebin.com/SVNuHNjm

**Comment by DuneSciFye** [comment] 2022-01-27 23:04
I'm going to download the broken database in case you need it and upload a working database from a backup

**Comment by DuneSciFye** [comment] 2022-01-27 23:38
![image](https://user-images.githubusercontent.com/65089425/151461262-54877a37-74ed-4417-96bd-ec72636018f2.png)
This was the issue. I left it blank one time when trying to remove island level

**Comment by OmerBenGera** [comment] 2022-02-04 11:16
> ![image](https://user-images.githubusercontent.com/65089425/151461262-54877a37-74ed-4417-96bd-ec72636018f2.png) This was the issue. I left it blank one time when trying to remove island level

An empty string is not a valid number, that's why it occurs.
However, it's not related to the original issue, so let's stick to the original issue.

**Comment by OmerBenGera** [comment] 2022-02-12 15:28
@Teyir Check out latest dev build, let me know if it fixes the issue.

**Comment by OmerBenGera** [comment] 2022-02-17 19:48
The issue happened when modules loaded data of players before the plugin loaded data from database.
This should be fixed. If it doesn't, please open a new issue and let me know for which plugin it occurs.

**Closed by OmerBenGera** 2022-02-17 19:48 UTC
Labels: 🔧 Potential fix, ❌ Unconfirmed
