### ISSUE TITLE
Very negative bonus

### ISSUE THREAD

**Issue by jfoucher** [BG-Software-LLC/SuperiorSkyblock2#2002] opened 2024-02-20 19:17 UTC
### Minecraft's Version

paper 1.20.4

### Plugin's Version

2023.3

### Describe the bug

Two islands on my server islands have a worth bonus that is  -28181 
The level bonus is -14090.5
all other islands also have negative bonuses, but most are like -258 / -129
These the islands.worth_bonus and islands.level_bonus in the database

### To Reproduce

I'm not sure, there are 3 members on this island, and after a server restart their bonus has gone very negative. I adjusted it manually to a more reasonable value, which worked, but when I ran syncbonus, it came back to -28181

### Additional Information

I did not find anything relevant when looking at past issues.

**Comment by OmerBenGera** [comment] 2024-02-23 13:46
If you have configured the level and worth to be adjusted to the schematic, if your players break the schematic, their worth and level will go negative. You can fix it by removing the adjust configuration, or by disabling negative levels and worth values in the config file (This is only for visualize, the plugin will still treat their values as negative)

Closing this, not a bug.

**Comment by jfoucher** [comment] 2024-02-24 20:39
So what should the worth_bonus be on a brand new island ? AFAIK these players haven't touched the nether island, have only added blocks to the normal island, and have not gone to the end.

**Comment by OmerBenGera** [comment] 2024-02-25 21:31
> So what should the worth_bonus be on a brand new island ? AFAIK these players haven't touched the nether island, have only added blocks to the normal island, and have not gone to the end.

If you dont want to adjust the worth to the schemaric blocks, it should be set to 0. Otherwise, it should be the negative value of the schematic worth value

**Comment by jfoucher** [comment] 2024-02-26 12:20
Ok so I tried to see how it works in a new server.
I created my island, and the worth_bonus shows this
![Screenshot from 2024-02-26 13-03-29](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/152015/c912c0d4-c619-44b0-8770-4c96b49d4eac)
I assume this is the negative value of the normal world island.
I then modified the config file to allow for the nether
I then gave myself some obsidian and a flint and steel to create a nether portal.
I enter the portal.
the worth_bonus now shows this : 
![Screenshot from 2024-02-26 13-13-56](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/152015/20bcb560-2329-42e8-b174-5585f3093c80)
This means the value of the nether island has been counted
How when I check the level of my island in game, it shows this : 

![Screenshot from 2024-02-26 13-14-45](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/152015/7184cbeb-29b6-43b3-bbce-c71f3f9fd9ee)

I don't understand where the -4201 comes from, because I have not touched either island. I assume the calculated worth and level should still be zero. If this is the desired behaviour, let me know and I'll drop this issue.

**Comment by OmerBenGera** [comment] 2024-02-27 21:24
Might be because some part of the nether schematic is out of the border.
Try increasing your border, then run `/is recalc`

**Comment by jfoucher** [comment] 2024-02-28 12:32
Increasing the border size to level 2 (100) seemed to do the trick. The worth_bonus did not change, but the worth now shows 128 (which must be the nether portal I built) So the bug is that the default nether island is too big for the starting island size then is that it ? maybe the worthbonus calculation should take into account the border size limit, or the total worth calc should take into account the current border size... I don't know how feasible those two options are though.

**Comment by OmerBenGera** [comment] 2024-03-01 10:28
That's not really a bug.
You can make the nether schematic fit in the original border, or have it unlocked only after they had their border increased.

The worth of the island will never count blocks outside of the border, as it doesn't make a lot of sense.
Play with it, or just cut the schematic - whatever fits your server :)

**Comment by OmerBenGera** [comment] 2024-03-09 14:56
I am closing this as you received a solution
If you still need help with that, make sure you send a message on the discord server

**Closed by OmerBenGera** 2024-03-09 14:56 UTC
Labels: Pending
