### ISSUE TITLE
island Chest do not work

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#619] opened 2021-09-24 15:07 UTC
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b316

### Describe the bug

The island chest for new player is empty (it told them "this chest is locked". I have to manually add them (using admin command)

### To Reproduce

Create a new server, set : 
island-chests:
  # The chest title.
  chest-title: '&4Chest'
  # Default amount of pages.
  # You can set this value to 0 to not have any pages by default.
  default-pages: 16
  # Default size for the pages.
  default-size: 6

in your config, create an island.

**Comment by OmerBenGera** [comment] 2021-09-24 17:20
It works fine for me on latest dev build.

**Comment by WarnDa** [comment] 2021-09-24 20:12
A player also get the issue :
> The number of island chests is not registered, sometimes it is reset

So it might be island chest resetting for some players.

I'm using MySQL, maybe chests do not save well with the new database system

**Comment by OmerBenGera** [comment] 2021-09-25 06:27
> A player also get the issue :
> 
> > The number of island chests is not registered, sometimes it is reset
> 
> So it might be island chest resetting for some players.
> 
> I'm using MySQL, maybe chests do not save well with the new database system

This sounds like another issue.
This issue is about default chests not working for new islands.
About the new reported issue, please open a new issue regarding this. Make sure you are able to replicate it, otherwise I wont be able to fix it.

**Comment by WarnDa** [comment] 2021-09-25 08:39
I don't know if it applies for all players, but I know there are issues with the chest, where some players do not get chests, not all of them.

I created another issue for island chest resetting (I got the issue this morning)

**Comment by OmerBenGera** [comment] 2021-09-25 09:43
As I said before, I tried to replicate the issue (I set default pages and sizes) and everything worked as it should.
Were you able to replicate the issue on another server?

**Comment by WarnDa** [comment] 2021-09-27 10:58
So, I got news !

I created a new version (on paper 1.16.5)
I used this config :
> island-chests:
  # The chest title.
  chest-title: '&4Island Chest'
  # Default amount of pages.
  # You can set this value to 0 to not have any pages by default.
  default-pages: 10
  # Default size for the pages.
  default-size: 3
 
using MySQL.
 
 I created an island, I had all my chests (10), I put 2 items in the chest 1
 I restarted server, now I only got 1 chest (the 1) the other are blocked.
![Screenshot_6403](https://user-images.githubusercontent.com/31826333/134895874-b964d8b4-e9b6-4fe5-ab88-69684fd5d0e6.png)

**Comment by OmerBenGera** [comment] 2021-09-28 08:42
It seems like if there are default chests and you don't fill them with items, they aren't saved (which is normal, as it's useless data to save). However, they are not loaded back to game when server starts, which is not intended.
Or in other words, confirmed.

**Comment by OmerBenGera** [comment] 2021-09-28 11:22
Should be fixed in latest dev build

**Comment by WarnDa** [comment] 2021-09-29 09:32
Island chest now work, but I still get my clear problem.
I can't reproduce it... I'll try to inspect the mysql database and check, but I really don't know the issue

**Comment by OmerBenGera** [comment] 2021-09-30 06:50
Island chests get cleared?
Maybe it happened on the restart of the old build?

**Comment by WarnDa** [comment] 2021-09-30 09:30
> Island chests get cleared? Maybe it happened on the restart of the old build?

Yes, always after a restart. But I can't reproduce it on a fresh server.

I'm on MySQL, maybe it's an issue with old build converting to new ones, and now chest get cleared after each restart

**Comment by OmerBenGera** [comment] 2021-09-30 11:36
I understand.
We'll move to the other issue then :)

**Closed by OmerBenGera** 2021-09-30 11:36 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
