### ISSUE TITLE
The problem of entering hell or the end in versions after SuperiorSkyblock2-2023.3-b166!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2071] opened 2024-05-07 16:41 UTC
### Minecraft's Version

[00:30:09 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-SlimeWorldManager-31 (MC: 1.20.4)
* You are running the latest version

### Plugin's Version

[00:32:48 INFO]: SuperiorSkyblock2 version 2023.3-b166
[00:32:48 INFO]: Feature packed Skyblock core.
[00:32:48 INFO]: Website: https://bg-software.com/
[00:32:48 INFO]: Author: Ome_R

All subsequent versions of this version will appear!

### Describe the bug

After creating a normal island and then building a hell gate or end gate, when there are players nearby and you teleport to the specified dimension through the hell gate or end gate, the game of the player next to the portal will be stuck! There will also be some weird problems!

### To Reproduce

When using SuperiorSkyblock2 version 2023.3-b166 or later, open hell and the end in the default configuration and then create other islands besides the normal island. When someone enters the end or hell next to you, the game will freeze for the people next to you, and some strange problems will also occur!

**Comment by OmerBenGera** [comment] 2024-05-11 13:27
Duplicate of #2061

**Closed by OmerBenGera** 2024-05-11 13:27 UTC
Labels: Pending

**Comment by wlm1455925277** [comment] 2024-05-11 13:32
Please do not use normal island to try. You can try it using other islands.

**Comment by wlm1455925277** [comment] 2024-05-11 13:33
> 的副本 #2061

Please do not use normal island to try. You can try it using other islands.

**Comment by wlm1455925277** [comment] 2024-05-11 13:35
> 的副本 #2061

Please do not use normal island to try. You can try it using other islands. For example, desert and mycel will only have this problem!

**Comment by wlm1455925277** [comment] 2024-05-11 13:36
Also requires the latest purpur core 1.20.4

**Comment by wlm1455925277** [comment] 2024-05-11 13:36
> 的副本 #2061

Also requires the latest purpur core 1.20.4
