### ISSUE TITLE
Error Spawner place event

### ISSUE THREAD

**Issue by Lele289** [BG-Software-LLC/SuperiorSkyblock2#1907] opened 2023-10-28 01:10 UTC
### Minecraft's Version

Minecraft version: 1.20.2, purpur.jar

### Plugin's Version

Plugin version: 2023.3

### Describe the bug

When I place a spawner on the island, the following error appears in the console: 
[error console.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/13194077/error.console.txt)

### To Reproduce

take the spawner with this command /give <username> spawner, and place the block on Island, and gote the error

### Additional Information

with the spawners i use silkspawner_2 plugin for add the permission to take the spawner without broke

**Comment by OmerBenGera** [comment] 2023-11-03 14:41
Use `/ws give` if you have WildStacker installed in order to obtain spawner items.
This should fix the issue.

**Comment by OmerBenGera** [comment] 2023-11-03 14:49
Duplicate of #1911

**Closed by OmerBenGera** 2023-11-03 14:49 UTC
Labels: Pending
