### ISSUE TITLE
Servers Crashes every 40-60 minutes

### ISSUE THREAD

**Issue by PaulKahleer** [BG-Software-LLC/SuperiorSkyblock2#1046] opened 2022-04-11 15:26 UTC
### Minecraft's Version

PaperSpigot 1.8.9

### Plugin's Version

1.9.0

### Describe the bug
My server crashes when there are about 60-70 players online and OutMemory issues start. Im using Aikar Flags
`java -Xms128M -Xmx10240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar nogui`

I have been trying to fix this problem for days. I have a base of 70-100 players and it is impossible to maintain it. I already removed all the plugins and left only the SuperiorSkyblock2 and it still happens.

### To Reproduce
There is no process to reproduce this problem, I really don't know what the problem is, but OutMemory shuts down the server. I have 10 GB and I think that is more than enough for 70-100 players, more than 10gb would be unnecessary. 
I have enough ram in all my machine

I did a memory analysis in MAT to see what was happening and these were the results
### Additional Information

![Problem1](https://user-images.githubusercontent.com/99153368/162772302-bddd00dd-dae9-4613-8d3b-a4ab13fa3421.png)
![Problem2](https://user-images.githubusercontent.com/99153368/162772314-0d2e4de6-874d-4176-ac7a-4740de1254ee.png)
![Problem3](https://user-images.githubusercontent.com/99153368/162772320-171ba279-28df-4190-92ee-5c5faa714c04.png)

**Comment by OmerBenGera** [comment] 2022-04-11 15:39
Skyblock may consume a lot of ram due to the large amount of different chunks that can be loaded at the same time.

I doubt its an issue with the plugin, however without heapdump I cant check it out.

**Comment by OmerBenGera** [comment] 2022-04-11 15:44
> I have a spark heapdump report. How can i give you them? It weighs like 300MB :/ I really need your help

Upload it to mediafire and send a link here
I will not be able to help until the weekend anyways

**Comment by PaulKahleer** [comment] 2022-04-11 16:30
https://www.mediafire.com/file/5sqb2hcuvkwo1a8/Heapdump.tar.gz/file

**Comment by WarnDa** [comment] 2022-04-12 11:52
Is it not the issue with a lot of chunk loading for entity limit you fixed in latest dev build ?

**Comment by PaulKahleer** [comment] 2022-04-12 16:11
Im testing but i think that it isn't normal:
https://spark.lucko.me/VD93GOHPXi My tps are very low with latest dev build

![Sin título](https://user-images.githubusercontent.com/99153368/163006789-4c81ce85-bc3c-4bb6-b854-110073545600.png)

**Comment by PaulKahleer** [comment] 2022-04-12 17:21
It still happens :/

**Comment by PaulKahleer** [comment] 2022-04-12 21:32
I think that SuperiorSkyblock has a lot of Memory leak

**Comment by WarnDa** [comment] 2022-04-12 21:35
Here the issue are missions, Ome_R will have to work on it.
But 1.8 skyblock server is really outdated, no performance issue on 1.16-1.18

**Comment by PaulKahleer** [comment] 2022-04-12 21:38
> 

I know a server with 100 players with SuperiorSkyblock (1.8.9) but i don't know what version plugin they are using:/ (I want to use his version, when i type /is help they have 8 help pages and im using other version because i have 9 help pages)

**Comment by OmerBenGera** [comment] 2022-04-14 20:09
I investigated the heap dump.

Problem Suspect 1 - This is not a memory leak. It's the schematics loaded to memory. I will look into optimizing it a bit more tho, hopefully I will be able to do something regarding this.

Problem Suspect 3 - You have over 9k islands on your server, which are all loaded to memory.

Anyways, there isn't any memory leak. I recommend giving your server more RAM if needed, as the combination of chunks being loaded as well as the data of SSB causing it to run out of memory.

**Comment by PaulKahleer** [comment] 2022-04-14 20:10
How much memory is enough for 70-100 players (1.8.9)?

**Comment by OmerBenGera** [comment] 2022-04-14 20:12
> How much memory is enough for 70-100 players (1.8.9)?

I have no clue. You currently have 8 (and not 10 as you mentioned before)

**Comment by PaulKahleer** [comment] 2022-04-14 20:13
I'll put more gb ram, and when the server restarts I'll come back again to find a solution

**Comment by WarnDa** [comment] 2022-04-14 20:15
> Problem Suspect 3 - You have over 9k islands on your server, which are all loaded to memory.

If I got 20k islands, they will all be loaded ? How much memory it takes approximately ?

**Comment by OmerBenGera** [comment] 2022-04-14 21:04
> > Problem Suspect 3 - You have over 9k islands on your server, which are all loaded to memory.
> 
> And i think that it's a problem:/ Why 9k islands should be loaded, it would be logical to do something to disable them

You can use delete them if you wish...
They are loaded to memory for performance.

The issue is probably chunks loading more than that tbh

**Comment by OmerBenGera** [comment] 2022-04-14 21:05
`/is admin purge` is the command you're looking for.

**Comment by WarnDa** [comment] 2022-04-15 07:42
I can’t purge island because players come back after 6 months when there is a big update.
Only keep in memory active islands, that were loaded during the last week, it would help with memory

**Comment by OmerBenGera** [comment] 2022-04-15 09:35
> I can’t purge island because players come back after 6 months when there is a big update. Only keep in memory active islands, that were loaded during the last week, it would help with memory

When they needed to be loaded it will lag the server, which will be awful.

**Comment by PaulKahleer** [comment] 2022-04-15 14:43
> When they needed to be loaded it will lag the server, which will be awful.

And is there a solution? I think that with more ram always it will be a problem:/
Because i have a big server (1-2 months) and i will have 40k islands or more

**Comment by OmerBenGera** [comment] 2022-04-15 18:01
> > When they needed to be loaded it will lag the server, which will be awful.
> 
> And is there a solution? I think that with more ram always it will be a problem:/ Because i have a big server (1-2 months) and i will have 40k islands or more

There's nothing to fix, as it doesnt consume that amount of ram anyways (1GB~ at most)

The main issue is chunks, focus on that.

**Comment by OmerBenGera** [comment] 2022-04-28 17:44
Any news regarding this?

**Comment by PaulKahleer** [comment] 2022-04-28 17:48
Nothing i will use other thing, this is bad for legacy version :/

**Comment by PaulKahleer** [comment] 2022-04-28 17:49
I was testing a lot of things, i did is purge, and still happens (I tested just with superiorskyblock plugin and nothing)

**Comment by OmerBenGera** [comment] 2022-04-28 17:57
> I was testing a lot of things, i did is purge, and still happens (I tested just with superiorskyblock plugin and nothing)

I told you the issue is with chunks, of course purge would not fix the issue.
It only approves my point that it's not an issue with the plugin, but with chunks causing massive ram usage on your server. This also makes sense due to the fact that players are spread across the entire world, and they share almost no chunks together whatsoever.

I am closing this for now; I recommend you to listen to my advice and to what I wrote here :)

**Closed by OmerBenGera** 2022-04-28 17:57 UTC
Labels: ❌ Unconfirmed

**Comment by PaulKahleer** [comment] 2022-05-06 16:34
Do you know what i must do with my chunks? Any ideas?

**Comment by OmerBenGera** [comment] 2022-05-06 18:44
> Do you know what i must do with my chunks? Any ideas?

Get a more optimized spigot jar. Recent version are better in terms of chunks
