### ISSUE TITLE
worth calculating error (schematic offset problem)

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#365] opened 2021-07-13 22:24 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

1.7.0 devb196

### Describe the bug

If schematic-offset is set to true, /is level say me the level is 0.
But if i try to use %superior_island_total_worth_format% or %superior_island_total_worth% worth is 4,000.0 (it calculate schematic value).

### To Reproduce

none

**Comment by OmerBenGera** [comment] 2021-07-16 16:32
That's probably because the plugin doesn't calculate worth of islands all the time, and it has a 60-seconds delay when calculating total worths. When the island is created, the worth is actually set with the offset. After that, it's changed and the offset is being applied. This makes it so the total worth is calculated first without the offset, however this should be updated after a minute.
Is this the case on your server?

**Comment by SbirTeo** [comment] 2021-07-17 14:11
Come posso risolvere?

**Comment by OmerBenGera** [comment] 2021-07-17 16:40
> Come posso risolvere?

???

**Comment by SbirTeo** [comment] 2021-07-17 16:43
How can i fix?

Il Sab 17 Lug 2021, 18:41 Ome_R ***@***.***> ha scritto:

**Comment by OmerBenGera** [comment] 2021-07-30 16:29
The total worth seems to work fine, it takes a minute to update but after that it works as intended.
I am closing this for now

**Closed by OmerBenGera** 2021-07-30 16:29 UTC
Labels: Bug Report, Further Investigation
