### ISSUE TITLE
Regarding the error that occurs after installing the Slime Worlds module and configuring it to open the end world.

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2013] opened 2024-03-01 12:36 UTC
### Minecraft's Version

[20:32:54 INFO]: Checking version, please wait...
[20:32:55 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-15783 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9f16b53 on paper_upstream)
Unknown version
Previous version: git-SlimeWorldManager-15776 (MC: 1.20.4)

### Plugin's Version

[20:33:16 INFO]: SuperiorSkyblock2 version 2023.3-b147
[20:33:16 INFO]: Feature packed Skyblock core.
[20:33:16 INFO]: Website: https://bg-software.com/
[20:33:16 INFO]: Author: Ome_R

### Describe the bug

I have tested the problem when you use the Slem Worlds module and then open the nether and the end in the configuration file and use the command /is admin tp [island name] nether and /is admin tp [island name] the_end to open the end and hell. After adjusting the island size to 60, this island will report an error!

### To Reproduce

I have tested the problem when you use the Slem Worlds module and then open the nether and the end in the configuration file and use the command /is admin tp [island name] nether and /is admin tp [island name] the_end to open the end and hell. After adjusting the island size to 60, this island will report an error!

### Additional Information

https://mclo.gs/IhuiuM2

**Comment by OmerBenGera** [comment] 2024-03-09 15:22
Duplicate of #2003

**Closed by OmerBenGera** 2024-03-09 15:22 UTC
Labels: Pending
