### ISSUE TITLE
Offline Users' islands are not being recalculated

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/SuperiorSkyblock2#849] opened 2022-01-17 10:37 UTC
### Minecraft's Version

1.17.1 Purpur

### Plugin's Version

Dev B468

### Describe the bug

After updating to latest dev, offline users are no longer having their islands recalculated setting them at 0 worth/level. Specifically reloading the island fixes the issue (I.E. if a user does /is recalc or an admin does /is admin recalc <name>) then it'll fix their island worth, however trying to recalculate all islands does not fix the issue.

### To Reproduce

- Update to latest dev build (468) from dev build 444
- Have a user be offline
- Watch their island not recalculate as it should

### Additional Information

Offline User:
https://i.imgur.com/m6neXuD.png
After recalculating with /is admin recalc SkateboardYak:
https://i.imgur.com/1Th3Flc.png

**Comment by WarnDa** [comment] 2022-01-18 09:43
Can confirm, all islands are level 0 after a restart, and I have to recalc them to fix it.

**Comment by OmerBenGera** [comment] 2022-01-18 12:38
I think I know what the issue is.
The plugin doesnt calculate worth for "inactive" islands, which probably makes the plugin to also not calculate their worth when they are loaded.
I will look into it, thanks for reporting.

**Comment by OmerBenGera** [comment] 2022-01-18 12:39
Just so I understand, it only happens for inactive islands, right?

**Comment by WarnDa** [comment] 2022-01-18 12:56
> Just so I understand, it only happens for inactive islands, right?

It happens for all islands after a restart, and you have to login and recalc your island to get your island level

**Comment by OmerBenGera** [comment] 2022-01-18 14:21
> > Just so I understand, it only happens for inactive islands, right?
> 
> It happens for all islands after a restart, and you have to login and recalc your island to get your island level

Ah, I understand.
I will look into that.
Mind checking if the block counts are saved to database?

**Comment by WarnDa** [comment] 2022-01-18 14:25
> > > Just so I understand, it only happens for inactive islands, right?
> > 
> > 
> > It happens for all islands after a restart, and you have to login and recalc your island to get your island level
> 
> Ah, I understand. I will look into that. Mind checking if the block counts are saved to database after the server is closed?

Seems saved
![image](https://user-images.githubusercontent.com/31826333/149955641-6579903a-871b-473b-bcec-60d1dbc4373f.png)

**Comment by WarnDa** [comment] 2022-01-18 15:54
> > > > > Just so I understand, it only happens for inactive islands, right?
> > > > 
> > > > 
> > > > It happens for all islands after a restart, and you have to login and recalc your island to get your island level
> > > 
> > > 
> > > Ah, I understand. I will look into that. Mind checking if the block counts are saved to database after the server is closed?
> > 
> > 
> > Seems saved ![image](https://user-images.githubusercontent.com/31826333/149955641-6579903a-871b-473b-bcec-60d1dbc4373f.png)
> 
> Okay, great. These islands actually not having worth when server starts, right?

Yes, worth and level is 0

**Comment by OmerBenGera** [comment] 2022-01-20 17:48
Fixed in latest build.

**Closed by OmerBenGera** 2022-01-20 17:48 UTC
Labels: ✔️ Confirmed
