### ISSUE TITLE
I can't even boot up the server with this plugin in there

### ISSUE THREAD

**Issue by UntouchedOdin0** [BG-Software-LLC/SuperiorSkyblock2#582] opened 2021-09-07 15:46 UTC
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

b295

### Describe the bug

I get constantly spammed with
`
[16:41:22] [Worker-Main-5/FATAL]: Failed to schedule load callback for chunk [-11, -4]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1322) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$42(ChunkTracker.java:1306) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.bgsoftware.superiorskyblock.world.generator.IslandsGenerator.generateChunkData(IslandsGenerator.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.buildSurfaceAndBedrock(CustomChunkGenerator.java:122) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$7(ChunkStatus.java:77) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:276) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1308) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$42(ChunkTracker.java:1306) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 8 more
`

### To Reproduce

Just install the plugin and try and load it and enjoy the errors.

### Additional Information

If you need any more info please contact me on discord via UntouchedOdin0#1504

**Comment by OmerBenGera** [comment] 2021-09-07 16:15
Look for the error that causes the server to not load and send it via pastebin.
The error you attached is because your server stopped.

**Comment by OmerBenGera** [comment] 2021-09-07 16:16
My guess is that you ignored the error that tells you to install the scripts engine, as you use 1.17.1 (java 16).
I am closing this, if that's not the cause make sure you let me know here

**Closed by OmerBenGera** 2021-09-07 16:16 UTC
Labels: ❌ Unconfirmed
