### ISSUE TITLE
Is recalc doesn't work correctly

### ISSUE THREAD

**Issue by Eth4nSP** [BG-Software-LLC/SuperiorSkyblock2#922] opened 2022-02-14 00:13 UTC
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-20 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9556fd on HEAD)

### Plugin's Version

SuperiorSkyblock2-1.8.3

### Describe the bug

when using /is recalc it does not work correctly, I was testing in several islands in most of them it recalculates the blocks, but in some of them it does not work correctly.
Testing I realized that it calculates absolutely all the blocks placed but the island level does not increase, it stays at 0, adding that the blocks placed previously is as if they added negatively, because for the level counter to increase you must place new blocks to reach the level that had the island before.
This error happened to me in a restart and since then I could not find a way to solve it, it is as if the island was bugged.

### To Reproduce

I don´t know the real reason

### Additional Information

![2022-02-13_20 18 46](https://user-images.githubusercontent.com/94498054/153781874-1f047a1d-4b72-4e7b-9217-3f5b6d587f08.png)

translate:
/is recalc
Processing your ask
The island value is 0
-------
/is level
Processing your ask
The island value is 0

**Comment by OmerBenGera** [comment] 2022-02-15 07:23
Duplicate of #921

**Closed by OmerBenGera** 2022-02-15 07:23 UTC
Labels: Pending
