### ISSUE TITLE
Is Permission AutoStacker

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#228] opened 2021-04-23 15:27 UTC
Hello i use SuperiorSkyblock2-b127 in 1.12.2 the permission "valuable_break" not works correctly, without the permission player be able to break the autostacker.

**Comment by OmerBenGera** [comment] 2021-04-30 15:30
I don't know what AutoStacker is, but maybe they need to add support for SSB or fix the priority of the event they listen to.
SSB disabled the interaction with valueable blocks on NORMAL priority of BlockBreakEvent and PlayerInteractEvent.

**Comment by nivcoo** [comment] 2021-04-30 15:37
AutoStacker (sorry it's the name on my server) is the "stacked-blocks" so it's integrated in superiorskyblock and previously you have added the permission "valuable_break" in /is permission to protect these blocks but now without permission my player can break theses blocks

**Comment by OmerBenGera** [comment] 2021-04-30 19:24
I understand now. How do you break the blocks?

**Comment by nivcoo** [comment] 2021-04-30 19:26
Yes so, give /is permission to break for visitor without the permission to "valuable_break" and you can see with any item the player will be able to break the "stacked-blocks" without the permission which protect their

**Comment by OmerBenGera** [comment] 2021-05-14 17:38
I couldn't seem to replicate the issue

**Comment by OmerBenGera** [comment] 2021-05-22 11:43
Any news regarding this?

**Comment by nivcoo** [comment] 2021-05-22 16:20
I have always the issue

**Comment by OmerBenGera** [comment] 2021-05-22 16:24
Take a video of the issue, as I couldn't replicate it.

**Comment by nivcoo** [comment] 2021-05-22 16:28
Visitor : Suhis_
Permission ON for visitor : Block Break
Permission OFF for visitor : Valuable Break

: https://pics.revolis.fr/2021-05/22/18-27_urUq.mp4

**Comment by nivcoo** [comment] 2021-05-22 16:28
Block Break : https://pics.revolis.fr/2021-05/22/18-28_yQDP.png
Valuable Break : https://pics.revolis.fr/2021-05/22/18-28_Orao.png

**Comment by nivcoo** [comment] 2021-05-22 16:35
I just understood that "Valuable Break" does not contain the "stacked-blocks" but only a list of blocks in the configuration

**Comment by OmerBenGera** [comment] 2021-05-22 16:36
You must configure your valuable blocks in the config, of course

**Comment by nivcoo** [comment] 2021-05-22 16:37
So there is no option to protect all the "stacked-blocks" ?

**Comment by OmerBenGera** [comment] 2021-05-22 16:37
> 
> 
> So there is no option to protect all the "stacked-blocks" ?

Add all the stacked blocks to the valuable blocks list. These are two different features that has nothing to do with each other

**Comment by nivcoo** [comment] 2021-05-22 16:39
Except that I have for example obisidian "stackers", some have 1 million except that obsidian can be used for build and therefore not very logical to classify in blocks of values ​​but I will do that

**Comment by OmerBenGera** [comment] 2021-05-22 16:41
> 
> 
> Except that I have for example obisidian "stackers", some have 1 million except that obsidian can be used for build and therefore not very logical to classify in blocks of values ​​but I will do that

What's the difference between a stacked block and a regular block then? They have the same value.

**Comment by OmerBenGera** [comment] 2021-05-22 16:41
Anyways, I am closing this as it's not a bug.

**Closed by OmerBenGera** 2021-05-22 16:41 UTC
Labels: Bug Report, Further Investigation
