### ISSUE TITLE
Is close teleport bug

### ISSUE THREAD

**Issue by Tom18314** [BG-Software-LLC/SuperiorSkyblock2#1914] opened 2023-11-05 13:54 UTC
### Minecraft's Version

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Plugin's Version

2023.3

### Describe the bug

I was hosting an event on my island with approximately 15 players present. I noticed that even after I closed my island to the public, these individuals continued to appear on my /is expel list.

The issue is that when I reopen and then close my island again, all the players on my expel list are teleported to spawn.

### To Reproduce

1. Let players visit the island
2. Close the island for public (players remain on expel list)
3. Reopen the island
4. Close the island 

### Additional Information

[https://medal.tv/games/minecraft/clips/1zJHsCfO6K5O_1/saFxSf737XgS?invite=cr-MSx4enIsMTg0NTQyMjMyLA](url)

**Comment by OmerBenGera** [comment] 2023-11-17 15:19
Once you close the island, all the players that don't have access to it are teleported out of it.
You could avoid it by adding the permission CLOSE_BYPASS to the players that were in the event, and revoke the permission to them once the event is finished.

**Comment by OmerBenGera** [comment] 2023-11-24 16:11
I am closing this as it is not a bug.
For further support, make sure you visit the discord server

**Closed by OmerBenGera** 2023-11-24 16:11 UTC
Labels: Pending
