### ISSUE TITLE
Null World Issue 

### ISSUE THREAD

**Issue by seanm-cloud** [BG-Software-LLC/SuperiorSkyblock2#1290] opened 2022-07-21 05:04 UTC
### Minecraft's Version

Pufferfish 1.18.2 Latest Version 

### Plugin's Version

1.11.0

### Describe the bug

https://pastebin.com/DTNu9r1d

### To Reproduce

https://pastebin.com/DTNu9r1d

**Comment by OmerBenGera** [comment] 2022-07-21 05:06
Duplicate of #1289

**Closed by OmerBenGera** 2022-07-21 05:06 UTC
Labels: Pending
