### ISSUE TITLE
Holograms and Stacking blocks

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#940] opened 2022-02-20 16:36 UTC
### Minecraft's Version

Purpur-1561 (MC: 1.18.1)

### Plugin's Version

SuperiorSkyblock2-1.8.4-b526

### Describe the bug

When you go to spawn and comeback to your island, holograms on stacked blocks dont work.

### To Reproduce

Put block stacking like diamond blocks, go to another world and come back (same if server restart or wtv)

### Additional Information

![2022-02-20_11 34 12](https://user-images.githubusercontent.com/98712497/154853463-39e2f831-a59b-4cee-9c79-61cca86cd1ce.png)

**Comment by OmerBenGera** [comment] 2022-02-20 17:39
Do they still have their stack sizes?

**Comment by DuckyDou** [comment] 2022-02-20 17:46
Yes only holograms not show

**Comment by OmerBenGera** [comment] 2022-02-21 17:51
Does it happen on a server with only SSB installed?

**Comment by DuckyDou** [comment] 2022-02-21 21:16
yes exactly and with plugin too

**Comment by SwartZCoding** [comment] 2022-02-22 10:52
> yes exactly and with plugin too

"With plugin too" ?? That's meen others plugins or just SSB & HolographicDisplay ?

**Comment by DuckyDou** [comment] 2022-02-22 13:30
Ssb and for holograms HolographicDisplay

**Comment by OmerBenGera** [comment] 2022-02-22 14:00
Try it with only SSB installed and no other plugins expect SSB.

**Comment by DuckyDou** [comment] 2022-02-22 14:10
So if i want use ssb i need to use without plugin? Tf

**Comment by OmerBenGera** [comment] 2022-02-22 17:47
> So if i want use ssb i need to use without plugin? Tf

I want to see if there is a conflict with another plugin.
Instead of arguing, just try it and we will see if there are any imcompabilities.

**Comment by Davisiiiik** [comment] 2022-02-22 18:27
I have encountered same issue on my server.
Server: Paper version git-Paper-207 (MC: 1.18.1)
Plugin: 1.8.4.525

I have done some testing, unloaded Holographic displays, issue still occures.

Steps I made to reproduce the problem:
- Be alone on my island
- Teleport away (/spawn for example)
- Wait few minutes (I suppose for chunks to unload)
- Teleport back using /is home

Now, holograms only in the chunk, where the home teleport is located disappear.
In some scenarios (when home teleport is in its original location) holograms disappear in the 4 closest chunks.

No other holograms had ever disappeared. Hope this helps a little.

**Comment by DuckyDou** [comment] 2022-02-22 18:55
With only ssb i have this issue

**Comment by DuckyDou** [comment] 2022-02-22 18:56
> yes exactly and with plugin too

.... i have already say yes ...

**Comment by OmerBenGera** [comment] 2022-02-24 19:41
It works fine for me on my server

**Comment by DuckyDou** [comment] 2022-02-25 03:53
Its strange.. im not alone with this issue

**Comment by OmerBenGera** [comment] 2022-02-25 11:01
Something on your setup is causing this to occur.

**Comment by DuckyDou** [comment] 2022-02-25 13:15
Same issue with new fresh install with default configuration nothing change ....

**Comment by OmerBenGera** [comment] 2022-02-25 13:30
> Same issue with new fresh install with default configuration nothing change ....

Let me know how to replicate the issue as I can't replicate it.

**Comment by DuckyDou** [comment] 2022-02-25 13:32
Place stacked block
Change world (wait 2-3 minutes)
Comeback to island

**Comment by OmerBenGera** [comment] 2022-02-25 13:34
> Place stacked block Change world (wait 2-3 minutes) Comeback to island

I did these exact same steps and everything works fine.

**Comment by DuckyDou** [comment] 2022-02-25 13:36
Strange because after remove and replace the stacker blocks all work great idk for what but its only first time you place stacked block

**Comment by OmerBenGera** [comment] 2022-02-25 14:58
> Strange because after remove and replace the stacker blocks all work great idk for what but its only first time you place stacked block

Weird. Are you able to replicate it with another set of stacked blocks?

**Comment by Davisiiiik** [comment] 2022-02-26 21:39
Today I did a lot of testing and now I know the cause of this problem. It is setting in config.yml `integrations.spawning`. If you set it to true, armor stands dont spawn near you on your island when you teleport.

**Comment by OmerBenGera** [comment] 2022-02-27 05:08
> Today I did a lot of testing and now I know the cause of this problem. It is setting in config.yml `afk-integrations.disable-spawning`. If you set it to true, armor stands dont spawn near you on your island when you teleport.

I will look into this in the weekend.

**Comment by OmerBenGera** [comment] 2022-03-10 21:07
The issue is fixed on latest dev build

**Closed by OmerBenGera** 2022-03-10 21:07 UTC
Labels: ✔️ Confirmed
