### ISSUE TITLE
Wither bug 

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1851] opened 2023-08-21 07:12 UTC
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### Plugin's Version

b-73

### Describe the bug

When disabled on the island by the "Wither Explosion" settings the wither will no longer do you any damage

### To Reproduce

The plugin should, even if the wither explosions were disabled, cause damage to the players

**Comment by OmerBenGera** [comment] 2023-08-26 10:42
It was intended that when disabling explosions, then they won't deal damage to players.
However, I can't really think why would I add such thing, as it doesn't make a lot of sense.
Therefore, I reverted these changes and it should be fixed in latest dev build.

**Closed by OmerBenGera** 2023-08-26 10:42 UTC
Labels: ✔️ Confirmed
