### ISSUE TITLE
Bank - chat issue

### ISSUE THREAD

**Issue by Muszek1** [BG-Software-LLC/SuperiorSkyblock2#1293] opened 2022-07-22 16:35 UTC
### Minecraft's Version

1.18.2

### Plugin's Version

1.11.0

### Describe the bug

Sometimes, when I withdraw the money from the bank (for e.g 50,000), it shows on the chat that I withdrawed 49999,99

### To Reproduce

It is easier to reproduce, when you put all money to bank and withdraw a lot of times.

**Comment by OmerBenGera** [comment] 2022-07-22 16:56
I don't quite understand what the issue is, especially because the last part of your sentence is in an unreadable font

**Comment by Muszek1** [comment] 2022-07-22 17:36
I corrected the sentence. The problem is when you withdraw and put money to bank, cents are running away (you pay 50000 and after withdraw you have got 49999,99)

**Comment by OmerBenGera** [comment] 2022-07-23 08:18
> I corrected the sentence. The problem is when you withdraw and put money to bank, cents are running away (you pay 50000 and after withdraw you have got 49999,99)

How do you deposit money into your bank? Using the GUI buttons? Using the chat?
Please give me full details on how to replicate the issue.

**Comment by Muszek1** [comment] 2022-07-23 21:05
1. Give 50000`$` to your player account
2. Open /is bank
3. Deposit all money to the bank
4. Withdraw all money from the bank
5. Repeat points 4 and 5 a lot of times
6. After many repeats you will lose 0.01`$`

**Comment by Muszek1** [comment] 2022-07-23 21:09
You can also not withdraw and deposit all money, but half money and repeats it a lot of times

**Comment by OmerBenGera** [comment] 2022-07-24 08:25
What economy plugin are you using?
I can't seem to replicate the issue

**Comment by Muszek1** [comment] 2022-07-24 10:00
Essentials

**Comment by OmerBenGera** [comment] 2022-07-24 10:16
> Essentials

I used Essentials as well and couldn't replicate it.
Mind making a video showcasing the issue and upload it to youtube (or any other streaming service), then send a link to it here?

**Comment by Muszek1** [comment] 2022-07-24 13:14
https://streamable.com/dbu91p

**Comment by Muszek1** [comment] 2022-07-24 13:15
bank na wyspie jest pusty means bank is empty
the icon on the top is to deposit/withdraw half of the money

**Comment by OmerBenGera** [comment] 2022-08-04 09:21
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment] 2022-08-12 07:22
I am closing this for now
If it still occurs, let me know

**Closed by OmerBenGera** 2022-08-12 07:22 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
