### ISSUE TITLE
after update SuperiorSkyblock2, all island's worth and level's are disappeard.

### ISSUE THREAD

**Issue by NCSV** [BG-Software-LLC/SuperiorSkyblock2#857] opened 2022-01-20 20:28 UTC
### Minecraft's Version

1.18.1 purur

### Plugin's Version

SuperiorSkyblock2-1.8.3-b468

### Describe the bug

after update SuperiorSkyblock2, all island's worth and level's are gone.
also player can't make worth by placing blocks, (fixed 0)

### To Reproduce

just see workth by /is level

### Additional Information

![2022-01-21_05 23 41](https://user-images.githubusercontent.com/25452835/150416639-1010e8fc-5e7b-487b-983a-aade282bc999.png)

**Comment by OmerBenGera** [comment] 2022-01-20 20:32
Duplicate of #849 
Fixed in latest dev build already.

**Closed by OmerBenGera** 2022-01-20 20:32 UTC
Labels: Pending
