### ISSUE TITLE
Island entity-limits don't work

### ISSUE THREAD

**Issue by Ammutadori075** [BG-Software-LLC/SuperiorSkyblock2#1988] opened 2024-02-04 10:30 UTC
### Minecraft's Version

1.20.1 Tested on Pufferfish, Purpur and Paper

### Plugin's Version

Superiorskyblock 2023.3 and dev versions too.

### Describe the bug

every time the server is restarted, the island limits are reset and the players can place entities and blocks even if they are limited in the configuration file.

### To Reproduce

Example : 
entity-limits:
  - VILLAGER:10
  
-  Player place 10 villager and try to place the 11th
-  Message Upgrades | You have reached the island''s limit for the entity Villgaer
-  The player cannot place other villagers
- Server restart
- The player can place another 10 villagers 
and so on.

**Comment by leon37921** [comment] 2024-02-06 23:03
Same problem for me with **entity limit** cow = 32.
Block limits are fine.
```
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-515 (MC: 1.19.4)

+ SuperiorSkyblock2 version 2023.3-b137 + other plugins
```
and
```
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-550 (MC: 1.19.4)

+ SuperiorSkyblock2 version 2023.3-b137 only
```

**Comment by anhcraft** [comment] 2024-02-23 07:08
+1 confirm
the entity limit does not track when an already-existing island loads: https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dfa049740888301613dddd80d7ae474d95149ce1/src/main/java/com/bgsoftware/superiorskyblock/listener/ChunksListener.java#L35

**Comment by OmerBenGera** [comment] 2024-03-09 14:37
There's a more large issue with the entity limits - it does not count entity counts in non-loaded chunks at all.
It needs to be redesigned completely.

**Comment by WarnDa** [comment] 2024-03-23 10:02
> There's a more large issue with the entity limits - it does not count entity counts in non-loaded chunks at all. It needs to be redesigned completely.

Hello,

While you are recoding this whole system, is it possible to make a system to ignore some mobs ?
I got a spawner plugin, and want to ignore the mobs spawned from this spawner on the limit, but count all the other mobs in the island.

I can pay for this option to be added

**Comment by WarnDa** [comment] 2024-04-22 15:13
> Check out latest dev build, I removed that check mentioned above and it should re-count entities after server restart now.

Just tried : 
- Placed 5 minecarts
- restarted
- Could place again 5 minecarts
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/f6d8e5bf-faef-43b7-80a5-523154606187)

- restart again, it displays 0
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/1d1d56ca-1a28-4f33-afef-58ec8c0c1c2d)

**Comment by WarnDa** [comment] 2024-04-22 15:19
Tested with cows, not the same issue but approximately the same
- before restart : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/41ac6059-53a3-4c36-878b-10487199a50c)

- after 1 restart : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/99b2a45f-7940-43ab-83e5-384bf8870ea7)

- after 2 restarts : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/6080e41c-686d-43a7-b21e-4ab7768c9f8f)

**Comment by WarnDa** [comment] 2024-04-22 15:23
Second test to see if it's related to chunks : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/50f0a814-b616-4580-877d-ba7a8aaaaf29)
I disconnect in the chunk where there is only 1 cow

And there is still 4 counted cow
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/1d454c4b-b42f-4bff-9137-26fcb4cc9118)

**Comment by Ammutadori075** [comment] 2024-04-22 15:29
Tested, unfortunately the problem is still present.

**Comment by WarnDa** [comment] 2024-05-11 12:08
Tested again after https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20Dev%20Builds/178/
And I can't reproduce the issue properly, idk if it's fully fixed or not

**Comment by OmerBenGera** [comment] 2024-05-11 13:32
> Tested again after https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20Dev%20Builds/178/ And I can't reproduce the issue, idk if it's fully fixed or not but it seems better !

Nothing was changed regarding entity limits in the last days/weeks/months.

**Comment by Ammutadori075** [comment] 2024-05-14 09:56
> Tested again after https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20Dev%20Builds/178/ And I can't reproduce the issue, idk if it's fully fixed or not but it seems better !

The problem is not solved, if the server is restarted while on the island, the limits are maintained, while if you are elsewhere, for example at the spawn, the limits are reset.

**Comment by OmerBenGera** [comment] 2024-05-24 20:40
Latest dev build should count entities in unloaded chunks & save entity counts to DB (similar to how it's done with block counts)

Let me know if it is better now

**Comment by WarnDa** [comment] 2024-05-28 19:57
Hello,

Player get issue where sometimes their limit is stuck as a certain amount (like 8 chicken) even if there is no mobs on their island.
I even tried to do a /killall, still the same.

(I am using wildstacker and mobs are stacked.)

Would it be possible to get a command, or to recalc every mobs when doing a **/is recalc** please ?

**Comment by WarnDa** [comment] 2024-06-19 13:19
> > Hello,
> > Player get issue where sometimes their limit is stuck as a certain amount (like 8 chicken) even if there is no mobs on their island. I even tried to do a /killall, still the same.
> > (I am using wildstacker and mobs are stacked.)
> > Would it be possible to get a command, or to recalc every mobs when doing a **/is recalc** please ?
> 
> Island entities recalculation happens when you load the island and that 5 minutes passed from the last entity recalculation

Found the issue.
We use the API not to count some mobs into the limit, but after the recalculation they count into the limit
When we spawn the entity we use : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/d75993e6-2b55-4e20-88ce-d01abc1e43e2)

**Comment by OmerBenGera** [comment] 2024-06-22 08:58
> > > Hello,
> > > Player get issue where sometimes their limit is stuck as a certain amount (like 8 chicken) even if there is no mobs on their island. I even tried to do a /killall, still the same.
> > > (I am using wildstacker and mobs are stacked.)
> > > Would it be possible to get a command, or to recalc every mobs when doing a **/is recalc** please ?
> > 
> > 
> > Island entities recalculation happens when you load the island and that 5 minutes passed from the last entity recalculation
> 
> Found the issue. We use the API not to count some mobs into the limit, but after the recalculation they count into the limit When we spawn the entity we use : ![image](https://private-user-images.githubusercontent.com/31826333/341089536-d75993e6-2b55-4e20-88ce-d01abc1e43e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDY5MzUsIm5iZiI6MTcxOTA0NjYzNSwicGF0aCI6Ii8zMTgyNjMzMy8zNDEwODk1MzYtZDc1OTkzZTYtMmI1NS00ZTIwLTg4Y2UtZDAxYWJjMWU0M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA4NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTk4YjQ3OTk2NTkyN2Y0NDk4ZjVlNzE5MmZlMDg2ZDc5Y2QxMTQ2NzlhZmMwMDY5MzE4ODA3MDkxOTQ1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RF9OL02Uue4OysjZ0ZxNxI7pXnbeX80NetQZsBM17f8)

I will look into this. 
Anyways, do not add new entity provider for each entity that you spawn. Add it only once, then use it for detecting all your custom mobs.

**Comment by OmerBenGera** [comment] 2024-06-22 09:09
@WarnDa Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment] 2024-06-25 15:45
> @WarnDa Check out latest dev build, let me know if it is fixed

I unloaded the chunk and went to another world 10mn, when I went back the mob were recalculated and counted for the limit :/
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/e2a70ecd-f950-4cc1-b19d-c382afd15c3f)

**Comment by OmerBenGera** [comment] 2024-06-26 10:26
> > @WarnDa Check out latest dev build, let me know if it is fixed
> 
> I unloaded the chunk and went to another world 10mn, when I went back the mob were recalculated and counted for the limit :/ ![image](https://private-user-images.githubusercontent.com/31826333/342800139-e2a70ecd-f950-4cc1-b19d-c382afd15c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTc4NzgsIm5iZiI6MTcxOTM5NzU3OCwicGF0aCI6Ii8zMTgyNjMzMy8zNDI4MDAxMzktZTJhNzBlY2QtZjk1MC00Y2MxLWIxOWQtYzM4MmFmZDE1YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZGMwYzY5NTgwNDE3YTg1M2M3NDAxMzIyZTVjYTJkODk0YmI5ZDVhM2RhNGMyZjM0ZmU0NWFmOTgwZjNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFWibUWIzm9QEf6ZNrarToDhcqtCyQvbRp8GxoFCoFw)

Check out your entity provider and debug it - the recalculation now calls it properly.

**Comment by WarnDa** [comment] 2024-06-29 09:05
> > > @WarnDa Check out latest dev build, let me know if it is fixed
> > 
> > 
> > I unloaded the chunk and went to another world 10mn, when I went back the mob were recalculated and counted for the limit :/ ![image](https://private-user-images.githubusercontent.com/31826333/342800139-e2a70ecd-f950-4cc1-b19d-c382afd15c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTc4NzgsIm5iZiI6MTcxOTM5NzU3OCwicGF0aCI6Ii8zMTgyNjMzMy8zNDI4MDAxMzktZTJhNzBlY2QtZjk1MC00Y2MxLWIxOWQtYzM4MmFmZDE1YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZGMwYzY5NTgwNDE3YTg1M2M3NDAxMzIyZTVjYTJkODk0YmI5ZDVhM2RhNGMyZjM0ZmU0NWFmOTgwZjNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFWibUWIzm9QEf6ZNrarToDhcqtCyQvbRp8GxoFCoFw)
> 
> Check out your entity provider and debug it - the recalculation now calls it properly.

We found the issue, you did this on NMS only for 1.21

**Comment by OmerBenGera** [comment] 2024-06-29 10:50
> > > > @WarnDa Check out latest dev build, let me know if it is fixed
> > > 
> > > 
> > > I unloaded the chunk and went to another world 10mn, when I went back the mob were recalculated and counted for the limit :/ ![image](https://private-user-images.githubusercontent.com/31826333/342800139-e2a70ecd-f950-4cc1-b19d-c382afd15c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTc4NzgsIm5iZiI6MTcxOTM5NzU3OCwicGF0aCI6Ii8zMTgyNjMzMy8zNDI4MDAxMzktZTJhNzBlY2QtZjk1MC00Y2MxLWIxOWQtYzM4MmFmZDE1YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZGMwYzY5NTgwNDE3YTg1M2M3NDAxMzIyZTVjYTJkODk0YmI5ZDVhM2RhNGMyZjM0ZmU0NWFmOTgwZjNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFWibUWIzm9QEf6ZNrarToDhcqtCyQvbRp8GxoFCoFw)
> > 
> > 
> > Check out your entity provider and debug it - the recalculation now calls it properly.
> 
> We found the issue, you did this on NMS only for 1.21

huh, my bad
Check out latest dev build, should be fixed.

**Comment by WarnDa** [comment] 2024-06-30 08:36
> > > > > @WarnDa Check out latest dev build, let me know if it is fixed
> > > > 
> > > > 
> > > > I unloaded the chunk and went to another world 10mn, when I went back the mob were recalculated and counted for the limit :/ ![image](https://private-user-images.githubusercontent.com/31826333/342800139-e2a70ecd-f950-4cc1-b19d-c382afd15c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTc4NzgsIm5iZiI6MTcxOTM5NzU3OCwicGF0aCI6Ii8zMTgyNjMzMy8zNDI4MDAxMzktZTJhNzBlY2QtZjk1MC00Y2MxLWIxOWQtYzM4MmFmZDE1YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZGMwYzY5NTgwNDE3YTg1M2M3NDAxMzIyZTVjYTJkODk0YmI5ZDVhM2RhNGMyZjM0ZmU0NWFmOTgwZjNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFWibUWIzm9QEf6ZNrarToDhcqtCyQvbRp8GxoFCoFw)
> > > 
> > > 
> > > Check out your entity provider and debug it - the recalculation now calls it properly.
> > 
> > 
> > We found the issue, you did this on NMS only for 1.21
> 
> huh, my bad Check out latest dev build, should be fixed.

Fixed ! Thanks

**Closed** 2024-06-30 20:10 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
