### ISSUE TITLE
Hoppers bug

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#796] opened 2021-12-25 15:24 UTC
### Minecraft's Version

[15:21:18 INFO]: Previous version: git-Purpur-"4ff0630" (MC: 1.17.1)

### Plugin's Version

[15:23:23 INFO]: SuperiorSkyblock2 version 1.8.2

### Describe the bug

Even if all of the hoppers on the island have been removed, the /is block still detects an invincible hopper, implying that there is an invincible hopper on the island. So, even if the hopper is full, it may still be utilized; for example, you can put 64 hoppers on the island, but only 25 of them can be used.

### To Reproduce

idk

**Comment by OmerBenGera** [comment] 2021-12-25 16:57
Run `/is recalc` and it will fix itself.
If the counted hoppers are not synced with the actual amount of hoppers in the island, it means you have a plugin that removes hoppers without letting SSB know about it, causing this to occur.
Find which plugin does it and report back so I can look and see if this can be fixed.

**Comment by OmerBenGera** [comment] 2021-12-30 11:13
Have you found a plugin that might be the cause of it?

**Comment by JoshuaPHYT** [comment] 2022-01-03 09:15
i cant find it. can you help me? i will send you plugins privately

**Comment by OmerBenGera** [comment] 2022-01-03 15:49
> i cant find it. can you help me? i will send you plugins privately

Try it on a server with only SSB installed. Then, try adding plugins to the server until you find what causes it to happen.

**Comment by JoshuaPHYT** [comment] 2022-01-04 01:17
i think i found the issue. it is clear lagg plugin

**Comment by OmerBenGera** [comment] 2022-01-04 08:08
> i think i found the issue. it is clear lagg plugin

Great.
Look how to disable it from interacting with hoppers so it will work with SSB :)
I am closing this for now.

**Closed by OmerBenGera** 2022-01-04 08:08 UTC
Labels: ❌ Unconfirmed
