### ISSUE TITLE
World not saving

### ISSUE THREAD

**Issue by andriycraft** [BG-Software-LLC/SuperiorSkyblock2#1164] opened 2022-05-28 12:35 UTC
### Minecraft's Version

> version
[15:32:52 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

 1.10.1.667

### Describe the bug

World not saving

### To Reproduce

Join the server
create an island
teleport to your island
change your world or rejoin or restart the server
teleport again to your island
BOOM! The chunks was reset

**Comment by andriycraft** [comment] 2022-05-28 12:35
Server plugins:
[15:35:13 INFO]: Plugins (24): AndriyCraftTools, Citizens, CommandNPC, CrazyAuctions, Essentials, ExecutableItems, JukeBox, LuckPerms, Multiverse-Core, MultiWorld, MyCommand, NBTAPI, NoteBlockAPI, PlaceholderAPI, SCore, SimpleBossBar, SimpleScore, SkinsRestorer, SuperiorSkyblock2, TradeSystem, Vault, ViaBackwards, ViaRewind, ViaVersion

**Comment by OmerBenGera** [comment] 2022-05-28 12:36
Duplicate of #1139

**Closed by OmerBenGera** 2022-05-28 12:36 UTC
Labels: Pending
