### ISSUE TITLE
console error (in random moment)

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2206] opened 2024-08-22 21:34 UTC
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21.1-16283-develop@0c68d84 (2024-08-21T16:50:37Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.2-b302

### Describe the bug

https://pastebin.com/2fGUd0VT

### To Reproduce

just popped up in console

**Comment by OmerBenGera** [comment] 2024-08-23 08:38
Duplicate of #2205

**Closed by OmerBenGera** 2024-08-23 08:38 UTC
Labels: Pending
