### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by vSKAH** [BG-Software-LLC/SuperiorSkyblock2#957] opened 2022-02-27 01:31 UTC
### Minecraft's Version

Pufferfish version git-Pufferfish-47 (MC:) 1.18.1 (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a786526 on HEAD)

### Plugin's Version

SuperiorSkyblock2 version 1.8.4

### Describe the bug

SettingsListener$PaperListener.onEntitySpawn() is heavy on the server with a lot of players

### To Reproduce

Get a lot of players, you'll see this task consumes a lot of tick but it shouldn't, and it makes server becoming laggy
Here are the stats with only 80 players, when in the middle of the afternoon I have 200 or 250 players my times drop considerably and it becomes unplayable.

### Additional Information

https://spark.lucko.me/8aDzMsIDyk

**Comment by OmerBenGera** [comment] 2022-02-27 05:11
Hey, this is a known issue.
It is caused by the entities limiter. There is already progress on fixing it, hopefully it will be released soon :)

For now, I am closing this.

**Closed by OmerBenGera** 2022-02-27 05:11 UTC
Labels: Pending
