### ISSUE TITLE
The island is not creating

### ISSUE THREAD

**Issue by KalviPL** [BG-Software-LLC/SuperiorSkyblock2#1693] opened 2023-04-16 18:21 UTC
### Minecraft's Version

Spigot 1.19.4

### Plugin's Version

Dev Build #9 14/04/2023 20:52:19

### Describe the bug

After typing the command /is create Name and selecting the basic scheme from the plugin, the island does not create, no errors pop up in the console

### To Reproduce

/is create Name

**Comment by nf-projects** [comment] 2023-04-17 21:22
I'm experiencing the same issue on 1.19.4 paper. When I type `/is go`, it tells me I can't teleport because there are no safe blocks.

**Comment by WarnDa** [comment] 2023-04-26 06:25
Reason here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1686#issuecomment-1509855309

**Comment by OmerBenGera** [comment] 2023-04-28 08:08
Duplicate of #1686

**Closed by OmerBenGera** 2023-04-28 08:08 UTC
Labels: Pending
