### ISSUE TITLE
Error - Error - Compatibility with paper 1.16.5 version 651

### ISSUE THREAD

**Issue by JLucassz** [BG-Software-LLC/SuperiorSkyblock2#244] opened 2021-05-08 19:25 UTC
**Minecraft's Version**
Minecraft 1.16.5
Paper-1.16.5-651

**Plugin's Version**: -
1.6.0

**Describe the bug**
The current version of the superior skyblock is not working with paper 1.16.5-651, when we created an island it presents this error:

![error](https://user-images.githubusercontent.com/76066285/117551027-ef46d600-b019-11eb-9afb-835f1c04f142.png)

https://paste.denizenscript.com/View/84351

**To Reproduce**
It happens when we start the server in the new version of the paper, the spigot is working normally

**Comment by OmerBenGera** [comment] 2021-05-09 07:29
Duplicate of #243

**Closed by OmerBenGera** 2021-05-09 07:29 UTC
Labels: Bug Report, Pending
