### ISSUE TITLE
spawnerprovider returning wrong location

### ISSUE THREAD

**Issue by Vyzon** [BG-Software-LLC/SuperiorSkyblock2#783] opened 2021-12-13 22:12 UTC
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

1.8.2

### Describe the bug

The spawnerprovider seems to be returning the wrong y coordinates when chunks are unloaded causing spawners to not calculate.

### To Reproduce

Idk I added a debug in my spawner plugin that returns the location of the spawner and it changes depending if the chunk is loaded.

Unloaded chunk: ![image](https://user-images.githubusercontent.com/10103575/145896847-3273f162-1259-4bfd-ac51-92dc9687bf30.png)
Loaded chunk: ![image](https://user-images.githubusercontent.com/10103575/145897097-4f324269-bd2c-4157-be9f-0ef6c8f0a563.png)

**Comment by OmerBenGera** [comment] 2021-12-15 21:17
Why are you using SpawnerProvider, and also who told you its safe to use it on unloaded chunks?

**Comment by OmerBenGera** [comment] 2021-12-15 21:18
Also, what SpawnerProvider are you using?

**Comment by Vyzon** [comment] 2021-12-16 00:49
What do you mean? I had to implement a custom spawnerprovider because I have a custom spawner plugin and stacked spawner counts won't show without it. I copied the implementation from the spawner providers inside of superior so I don't see why it would be an issue.

**Comment by OmerBenGera** [comment] 2021-12-16 13:32
> What do you mean? I had to create a custom spawnerprovider because I have a custom spawner plugin and stacked spawner counts won't show without it. I copied the implementation from the spawner providers inside of superior so I don't see why it would be an issue.

If you are handling the SpawnerProvider then your code is ran. How is it related to SuperiorSkyblock?
When the plugin uses your SpawnerProvider, your code is running, nothing else.

I might not understood the issue correctly, so if thats the case mind explaining it again?

**Comment by Vyzon** [comment] 2021-12-16 14:54
> > What do you mean? I had to create a custom spawnerprovider because I have a custom spawner plugin and stacked spawner counts won't show without it. I copied the implementation from the spawner providers inside of superior so I don't see why it would be an issue.
> 
> If you are handling the SpawnerProvider then your code is ran. How is it related to SuperiorSkyblock? When the plugin uses your SpawnerProvider, your code is running, nothing else.
> 
> I might not understood the issue correctly, so if thats the case mind explaining it again?

Because superiorskyblock is still what's returning the wrong location? You told me a long time ago I had to do this because you weren't going to implement spawnerprvoiders for custom spawner plugins. Here's my code:
https://www.toptal.com/developers/hastebin/goyujameta.coffeescript
https://www.toptal.com/developers/hastebin/okugibubus.java

**Comment by Vyzon** [comment] 2021-12-16 17:27
Subtracting 1440 from the locations y resolves this if its greater than 255, but this issue still exists in every other spawnerprovider.

**Comment by OmerBenGera** [comment] 2021-12-17 08:56
Mind showing me stack trace of the call when y's locatipn is 1440?
`new Exception().printStackTrace();`

Then send me the results so I can understand from where it gets called.

**Comment by OmerBenGera** [comment] 2021-12-17 08:59
Also, you know returning null will make the method called twice - once async then once sync. It doesnt seem like you have any check for that, which also makes no sense.

**Comment by Vyzon** [comment] 2021-12-17 15:46
I did, but I removed it when debugging. I'll make sure to add that back.

**Comment by OmerBenGera** [comment] 2021-12-17 21:21
Great. Once you have the stack-trace, upload it to pastebin and send it here for me please

**Comment by Vyzon** [comment] 2021-12-19 06:58
> Great. Once you have the stack-trace, upload it to pastebin and send it here for me please

My bad, I didn't see the previous reply.. https://pastebin.com/Wx3JQuCt

**Comment by OmerBenGera** [comment] 2021-12-19 07:00
> > Great. Once you have the stack-trace, upload it to pastebin and send it here for me please
> 
> My bad, I didn't see the previous reply.. https://pastebin.com/Wx3JQuCt

I believe the pastebin is private. Mind re-uploading it?

**Comment by Vyzon** [comment] 2021-12-19 07:53
https://pastebin.com/qcEJJhDb

**Comment by OmerBenGera** [comment] 2021-12-24 10:11
Right, there was an issue with detection of y-positions of chunk sections in 1.17 for unloaded chunks.
The issue is fixed in latest dev build, sorry for the trouble!

**Closed by OmerBenGera** 2021-12-24 10:11 UTC
Labels: ❌ Unconfirmed
