### ISSUE TITLE
SuperiorSkyblock problems with upgrades

### ISSUE THREAD

**Issue by Faobi69** [BG-Software-LLC/SuperiorSkyblock2#283] opened 2021-05-29 15:45 UTC
Minecraft's Version: Paper 1.16.5

Plugin's Version: 1.6.0

**Describe the bug**
Hi, I have encountered the following problem in updates:
- When a user buys an island upgrade it is given correctly, but if the server restarts for some reason the upgrades are reset and are never purchased by the user

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
There are no errors in the console, but I think the problem is caused by the fact that the purchase of upgrades is not taken into account because the plugin does not save data anywhere

**Comment by OmerBenGera** [comment] 2021-05-29 16:58
Look into the database and check if the upgrades are saved.

**Comment by OmerBenGera** [comment] 2021-06-04 15:26
Any news regarding this?

**Comment by Leyji** [comment] 2021-06-06 17:05
Same for me. Players are getting their upgrades reset over and over again.

**Comment by ArcevMC** [comment] 2021-06-07 11:35
Is the scripting system related to the mechanics of upgrades?

![image](https://user-images.githubusercontent.com/29128256/121010049-c06f6d00-c749-11eb-85b2-b72ef498138a.png)

**Comment by OmerBenGera** [comment] 2021-06-10 09:42
> Is the scripting system related to the mechanics of upgrades?
> 
> ![image](https://user-images.githubusercontent.com/29128256/121010049-c06f6d00-c749-11eb-85b2-b72ef498138a.png)

Not

**Comment by OmerBenGera** [comment] 2021-06-10 09:45
> Is the scripting system related to the mechanics of upgrades?
> 
> ![image](https://user-images.githubusercontent.com/29128256/121010049-c06f6d00-c749-11eb-85b2-b72ef498138a.png)

Not directly, but can cause issues of course.
Install the NashronEngine module so it will work (you probably have java 16)

**Comment by OmerBenGera** [comment] 2021-06-10 09:45
Also, no one have yet to give me an error or a way to replicate the issue, so right now I cant do anything with that.

**Comment by warzoneak** [comment] 2021-06-10 20:23
what are you looking for exactly. Im having this issue also. If i buy an upgrade for an island snf hspprn to restart the server none of the upgrades are there anymore.

Logs dont show any error's. I have tried with without a database and with sqlite and mysql all have same issue. 

In the sql database for upgrades it has this posted

`[{"name":"border-size","level":4},{"name":"minecarts-limit","level":4},{"name":"spawner-rates","level":4},{"name":"crop-growth","level":4},{"name":"generator-rates","level":4},{"name":"members-limit","level":4},{"name":"hoppers-limit","level":4},{"name":"mob-drops","level":4}]`

Which to me looks like the upgrades are saved but its not reading the database i assume. But has no issues putting data in the tables

**Comment by warzoneak** [comment] 2021-06-10 20:40
** Update ** 

I was using the Stable version from the website after downloading the dev version it is reading from the mysql database now. So maybe the issue is the in the stable version and thats why you cant replicate it yourself.

so Build #157 fixed this issue for me

**Comment by OmerBenGera** [comment] 2021-06-12 11:13
> 
> 
> what are you looking for exactly. Im having this issue also. If i buy an upgrade for an island and happen to restart the server none of the upgrades are there anymore.
> 
> Logs dont show any error's. I have tried without a database and with sqlite and mysql all have same issue.
> 
> In the sql database for upgrades it has this posted
> 
> `[{"name":"border-size","level":4},{"name":"minecarts-limit","level":4},{"name":"spawner-rates","level":4},{"name":"crop-growth","level":4},{"name":"generator-rates","level":4},{"name":"members-limit","level":4},{"name":"hoppers-limit","level":4},{"name":"mob-drops","level":4}]`
> 
> Which to me looks like the upgrades are saved but its not reading the database i assume. But has no issues putting data in the tables
> 
> https://gyazo.com/9ac0f6522924b2e2139f5a5fae55db08
> 
> Shows it connecting

Make sure you fix all the errors and then test if it works (for example, the script error that you had)
As it works flawlessly fine for me.

**Comment by Leyji** [comment] 2021-06-15 07:33
Build #157 also fixed the issue for me

**Comment by OmerBenGera** [comment] 2021-06-18 10:25
I am closing this for now as it seems to be resolved

**Closed by OmerBenGera** 2021-06-18 10:25 UTC
Labels: Bug Report, Further Investigation
