### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#437] opened 2021-08-13 00:05 UTC
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b209

### Describe the bug

I saw this error in console on server startup :
https://pastebin.com/nFycaGXD

### To Reproduce

idk

**Comment by OmerBenGera** [comment] 2021-08-13 10:44
Duplicate of #411

**Closed by OmerBenGera** 2021-08-13 10:44 UTC
Labels: Bug Report, Pending
