### ISSUE TITLE
Players' islands are removed from their data after server restart.

### ISSUE THREAD

**Issue by XHealthy** [BG-Software-LLC/SuperiorSkyblock2#1001] opened 2022-03-15 18:34 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

latest dev build #557

### Describe the bug

I saw a similar bug but mine is a bit different. 
Sometimes, after restarting the server, some players islands simply delete themselves from player's data. There is no error in the console but there is something like this:

`[11:41:39] [User Authenticator #3/INFO]: UUID of player _Healthy is b37b3161-dacf-4b35-bce9-455c4e077609 [11:41:39] [Server thread/INFO]: [SuperiorSkyblock2] Changing UUID of _Healthy to b37b3161-dacf-4b35-bce9-455c4e077609 [11:41:40] [Server thread/INFO]: _Healthy[/83.28.220.69:27539] logged in with entity id 215 at ([world]17.5, 137.0, -32.5) [11:41:40] [Craft Scheduler Thread - 20 - nLogin/INFO]: [nLogin] The user _Healthy has successfully logged in. [11:41:40] [Craft Scheduler Thread - 20 - nLogin/INFO]: [nLogin] The user _Healthy logged in automatically for having a premium account.`

This isn't the login plugin fault, because I checked it on other plugins as well

ssb2 changes the player's UUID even if the player's UUID has not changed.

It looks like this:
i have UUID "b37b..." > server restart > I'm logging in with uuid "b37b..." > ssb2 "`Changing UUID of _Healthy to "b37b..."` > 
My island exists but I practically do not have it. It is displayed on `/is top` but when I use `/is` it shows me the island creating  GUI.

### To Reproduce

Create an island and reset the server. 
This bug can appear once in 10 times, but also every restart. 
Sometimes it worked for an hour and when I turned on the server later, I didn't have an island anymore.

### Additional Information

after restart:
https://www.youtube.com/watch?v=KAHdwrGGFVM&ab_channel=Kacper

**Comment by OmerBenGera** [comment] 2022-03-15 21:45
Its exactly identical to the other issue.
Duplicate of #981

**Closed by OmerBenGera** 2022-03-15 21:45 UTC
Labels: Pending
