### ISSUE TITLE
Island upgrades resetting...

### ISSUE THREAD

**Issue by JakkitDE** [BG-Software-LLC/SuperiorSkyblock2#1727] opened 2023-05-18 13:14 UTC
### Minecraft's Version

1.19.4 PaperMC

### Plugin's Version

Latest Dev Build (#18 06/05/2023 14:33:35)

### Describe the bug

Island upgrades like size, block-limit & co.. are resetting. Even without restart. After an unknown amount of time the upgrades reset. We have to manually type in "/sky admin syncupgrades * " to recover them. I searched the console for errors: nothing. Everything's working fine.

### To Reproduce

Thats a bit complicated.. Because we just do nothing. The entire plugin works fine. Upgrading works fine, too. Only after an amount of time upgrades resetting. My players can see the reset by the border e.g..

**Comment by OmerBenGera** [comment] 2023-05-19 12:04
Look into what causing this to occur, as this doesn't happen for me.
You have a faulty configuration, command or another plugin somehow resets the upgrades.

**Comment by JakkitDE** [comment] 2023-05-22 17:21
> Look into what causing this to occur, as this doesn't happen for me. You have a faulty configuration, command or another plugin somehow resets the upgrades.

I can't find anything. It is not occuring for all players. The upgrades.yml file is a valid YAML file as I checked it. After syncupgrades it works for a unknown amount of time. Either after rejoin or after restart the upgrades got reset for some players.

**Comment by OmerBenGera** [comment] 2023-06-23 11:21
Is this still relevant?

**Comment by OmerBenGera** [comment] 2023-09-01 09:25
I am closing this due to lack of response
If the issue continues, let me know

**Comment by leon37921** [comment] 2024-01-27 11:20
Hey, I'm working together with JakkitDE

The problem is still there and happens quite randomly only to some players.
I've tried various things to reproduce the bug, so far without success. Neither as a normal player nor with Op.
- Created a new island and purchased several border-size upgrades
- Gave some players money for border-size upgrades

Players report that after purchasing a border-size upgrade (it's usually the upgrade from level 2 to level 3. But I couldn't reproduce this with my own islands) their island size was not changed. I had to manually enter the command '/sky admin syncupgrade playername' every time to sync the upgrade.
The players were on the island. No errors in the console.

While the server is running, the upgrade is not rolled back.

The upgrade will be reset when the server restarts.

previous SSB2 version: dev build b107
Current version: dev build b134
Server Version: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-515 (MC: 1.19.4)

main config.yml https://pastebin.com/uieQbh2P
upgrades config.yml https://pastebin.com/h0U7gsq3

**Comment by OmerBenGera** [comment] 2024-01-27 16:32
Let me know how to to replicate the issue.

**Comment by OmerBenGera** [comment] 2024-05-11 17:21
Any news regarding this?

**Comment by JakkitDE** [comment] 2024-05-11 18:52
> Any news regarding this?

Hello. Sadly no. The issue still happens every day. But there is no way to trigger the issue. Randomly players messaging us their border has reset. /is admin syncupgrades <Player> fixes it temporarily. Additional information: Not all islands get reset. It doesn`t matter if its an island which exists for a long time or if its an island which has been created just a few hours ago like those of new players. But when it resets until fixing, its only these Island. Neither all Islands nor all islands of all players currently playing.

**Comment by JakkitDE** [comment] 2024-05-11 18:54
Ahhh. No its still opened.

**Comment by JakkitDE** [comment] 2024-05-26 06:42
I am responding because I was told to do so. Kadnick (Discord) -> Thats me. I've openend the ticket.

**Comment by OmerBenGera** [comment] 2024-06-01 09:07
Does it happen after restarts, or it works and then suddenly it stops working on the same server session?

**Comment by JakkitDE** [comment] 2024-06-01 09:16
> Does it happen after restarts, or it works and then suddenly it stops working on the same server session?

It just randomly happens. A restart doesnt matter. Also it just happens for one specific player at the same time. Sync does fix it until it happens again for another one.

**Comment by OmerBenGera** [comment] 2024-06-01 09:58
When it happens, run `/is admin show <island>` and send me a screenshot of what you get

**Comment by JakkitDE** [comment] 2024-06-01 17:35
> When it happens, run `/is admin show <island>` and send me a screenshot of what you get

I have forwarded that information to my team Members. We will post it here as soon as possible. Thanks.

**Comment by JakkitDE** [comment] 2024-06-08 15:56
![2024-06-08_17 44 19](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20011543/79ed5b6e-428e-424c-8955-bc7835d3063f)
![2024-06-08_17 44 43](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20011543/10787118-2941-4b92-9a60-7d9e0707aff0)
![2024-06-08_17 45 33](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20011543/a7f67d39-17be-472b-be2a-ebfc5d2ea212)
So. Finally I catched it. Island size (german: Insel Größe) is 40 and has been reset whyever. I resynced all upgrades for all islands. Then Island size is 62. The border was correct after resync.

**Comment by OmerBenGera** [comment] 2024-06-11 08:56
It seems like it was really desynced from the upgrades value (there's no green symbol near it)
Run `/is admin debug SET_SIZE` as well as `/is admin debug SHOW_STACKTRACE` - this should print to console when setting island sizes of an island, which will desync it from the upgrade value, as well as the stack trace (it will be shown similar to how an error is printed to console)
Once it occurs, look for these logs in console and send it here

**Comment by JakkitDE** [comment] 2024-06-15 00:29
I will do so as soon as possible.

**Comment by OmerBenGera** [comment] 2024-07-14 18:36
@JakkitDE Any news regarding this?

**Comment by JakkitDE** [comment] 2024-07-14 19:55
> @JakkitDE Any news regarding this?

Sorry. Due to private circumstances I totally forgot about that. I will do it as soon as possible. Thank you.

**Comment by JakkitDE** [comment] 2024-07-17 11:39
> @JakkitDE Any news regarding this?

So, my admin tried to change an island size which resulted in this output.

[23:21:42 INFO]: [SuperiorSkyblock2] SIsland::setIslandSize {skrilly4} {4}
[23:21:42 WARN]: java.lang.Exception: Stack trace
[23:21:42 WARN]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.core.logging.Log.printStackTrace(Log.java:155)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.core.logging.Log.debug(Log.java:72)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.island.SIsland.setIslandSize(SIsland.java:1718)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.admin.CmdAdminSetSize.execute(CmdAdminSetSize.java:83)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.IAdminIslandCommand.execute(IAdminIslandCommand.java:27)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.execute(CmdAdmin.java:82)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18)
[23:21:42 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
[23:21:42 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[23:21:42 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[23:21:42 WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[23:21:42 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[23:21:42 WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[23:21:42 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)
[23:21:42 WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[23:21:42 WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[23:21:42 WARN]: 	at SuperiorSkyblock2-2024.1-b228.jar//com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand.execute(CommandsManagerImpl.java:309)
[23:21:42 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[23:21:42 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[23:21:42 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[23:21:42 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[23:21:42 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[23:21:42 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[23:21:42 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:21:42 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:21:42 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[23:21:42 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[23:21:42 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[23:21:42 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:112)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1557)
[23:21:42 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:21:42 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
​

**Comment by JakkitDE** [comment] 2024-07-20 06:07
Additional my Admin told me, island upgrades only would getting reset after restart. The exception was called when running the island size changing admin command.

**Comment by JakkitDE** [comment] 2024-07-20 06:08
I mean, the issue still also happens for other players. The command just was used to faster trigger the exception in console.

**Comment by OmerBenGera** [comment] 2024-07-20 07:41
If you set size of an island using `/is admin setsize`, it will not be synced with upgrades anymore, and the island will keep the size of the border you set to them - overriding the upgrade value.

**Comment by OmerBenGera** [comment] 2024-08-02 14:44
Any news regarding this?

**Comment by JakkitDE** [comment] 2024-08-03 05:03
No. I am almost every day at work. But also reading almost every day that some players border has been reset. The SET_SIZE and PRINT_STACKTRACE options are turned on. We have to look now. As far as I know the border seems to be reset for some players after a restart. But not sure actually.

**Comment by leon37921** [comment] 2024-08-03 08:58
I'm working with JakkitDE. I looked into the problem, checked the logs of the past 3 weeks and, except for the test command with "/is admin setsize", no debug messages were shown in the console (set_size + show_stacktrace).
Even with setting the border size with "/is admin setupgrade name border_size" manually and than buying a new island-upgrade, no debug message was shown in the console.
The island border of some players is resetted after every server restart.
No additional information or errors, sorry.

**Comment by OmerBenGera** [comment] 2024-08-03 09:19
> I'm working with JakkitDE. I looked into the problem, checked the logs of the past 3 weeks and, except for the test command with "/is admin setsize", no debug messages were shown in the console (set_size + show_stacktrace). Even with setting the border size with "/is admin setupgrade name border_size" manually and than buying a new island-upgrade, no debug message was shown in the console. The island border of some players is resetted after every server restart. No additional information or errors, sorry.

What do you see in the DB for the islands that have their upgrades reset?

**Comment by leon37921** [comment] 2024-08-03 09:59
DB: from "island_upgrades" border-size: 5
console: "/is admin show " border-size: 5
after "/is admin syncupgrades *" The island border is being expanded to the correct size but still "border-size: 5" for /is admin show command.

**Comment by OmerBenGera** [comment] 2024-08-03 13:24
> DB: from "island_upgrades" border-size: 5 console: "/is admin show " border-size: 5 after "/is admin syncupgrades *" The island border is being expanded to the correct size but still "border-size: 5" for /is admin show command. edit: border-size 5 is the correct size. After "/is admin syncupgrades *" the border is shifted from previous size to correct size 5.

What about in the islands table? Is there a custom border size?

**Comment by leon37921** [comment] 2024-08-03 20:23
> > DB: from "island_upgrades" border-size: 5 console: "/is admin show " border-size: 5 after "/is admin syncupgrades *" The island border is being expanded to the correct size but still "border-size: 5" for /is admin show command. edit: border-size 5 is the correct size. After "/is admin syncupgrades *" the border is shifted from previous size to correct size 5.
> 
> What about in the islands table? Is there a custom border size?

I don't have a custom border size in the "islands" table but
 "island_settings" shows the size of level 4 and not level 5

**Comment by OmerBenGera** [comment] 2024-08-09 15:00
> > > DB: from "island_upgrades" border-size: 5 console: "/is admin show " border-size: 5 after "/is admin syncupgrades *" The island border is being expanded to the correct size but still "border-size: 5" for /is admin show command. edit: border-size 5 is the correct size. After "/is admin syncupgrades *" the border is shifted from previous size to correct size 5.
> > 
> > 
> > What about in the islands table? Is there a custom border size?
> 
> I don't have a custom border size in the "islands" table but "island_settings" shows the size of level 4 and not level 5

It should be set to "-1" and not show an actual value.
This is why it resets after a restart.

Run `/is admin debug database_query` and `/is admin debug show_stacktrace` and wait for a query message that writes to `island_settings` and updates the `size` column. Then, send me the stack trace here

**Comment by leon37921** [comment] 2024-08-10 15:30
I can finally reproduce it.
How to reproduce the bug (SuperiorSkyblock2 version 2024.1-b288, Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)):
1. create island
2. buy border-upgrade
3. run command /is admin syncupgrades
4. buy another border-upgrade
5. restart server
→ island-border is not correct

Whole session from island-creation to server-stop:
https://pastebin.com/n32cLaVA
After server-restart, message with 'islands_settings' + 'size'
`[17:18:02 INFO]: skrilly4 issued server command: /sky admin syncupgrades skrilly4
[17:18:02 INFO]: [SuperiorSkyblock2] SQLTransactionProcessor::executeTransaction {UPDATE {prefix}islands_settings SET size=40 WHERE island=30fc51bb-0b9e-4061-9657-278e176ba74f;}
[17:18:02 WARN]: java.lang.Exception: Stack trace
[17:18:02 WARN]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.logging.Log.printStackTrace(Log.java:155)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.logging.Log.debug(Log.java:72)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeTransaction(SQLTransactionProcessor.java:86)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.lambda$processTransaction$0(SQLTransactionProcessor.java:41)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.customQuery(SQLiteSession.java:170)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.customQuery(SQLHelper.java:91)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.executeQuery(SQLTransactionProcessor.java:110)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLTransactionProcessor.processTransaction(SQLTransactionProcessor.java:36)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.processTransaction(DatabaseTransactionsExecutor.java:115)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.handleNextTransactionSafe(DatabaseTransactionsExecutor.java:105)
[17:18:02 WARN]: 	at SuperiorSkyblock2-2024.1-b288.jar//com.bgsoftware.superiorskyblock.core.database.transaction.DatabaseTransactionsExecutor.transactionsHandler(DatabaseTransactionsExecutor.java:83)
[17:18:02 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by OmerBenGera** [comment] 2024-08-24 11:44
Check out latest dev build, let me know if it is fixed
You will need to use `/is admin syncupgrades` again on islands that are not synced.

**Comment by leon37921** [comment] 2024-08-24 18:02
I got this error with b311, updated from b288.
Same world, database and plugins
```
[19:50:28] [Server thread/INFO]: [SuperiorSkyblock2] SQLDatabaseBridge::loadAllObjects ENTER {islands}
[19:50:28] [Server thread/ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading data from database:
[19:50:28] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.value.ValuesCache.fetch(ValuesCache.java:30)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.value.IntValueFixedSynced.of(IntValueFixedSynced.java:10)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.value.IntValue.syncedFixed(IntValue.java:16)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.upgrade.SUpgradeLevel.lambda$getBlockLimitsUpgradeValue$1(SUpgradeLevel.java:297)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.upgrade.SUpgradeLevel.getBlockLimitsUpgradeValue(SUpgradeLevel.java:295)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.SIsland.syncUpgrade(SIsland.java:4858)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.SIsland.lambda$updateUpgrades$77(SIsland.java:2831)
[19:50:28] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[19:50:28] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.SIsland.updateUpgrades(SIsland.java:2831)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.SIsland.<init>(SIsland.java:348)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.factory.FactoriesManagerImpl.createIsland(FactoriesManagerImpl.java:126)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.island.builder.IslandBuilderImpl.build(IslandBuilderImpl.java:893)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.DataManager.lambda$loadIslands$5(DataManager.java:253)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$0(SQLDatabaseBridge.java:37)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:35)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.executeQuery(SQLiteSession.java:202)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.select(SQLiteSession.java:156)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.select(SQLHelper.java:81)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:34)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.DataManager.loadIslands(DataManager.java:187)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.core.database.DataManager.loadData(DataManager.java:59)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:473)
[19:50:28] [Server thread/WARN]: 	at SuperiorSkyblock2-2024.2-b311.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:252)
[19:50:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[19:50:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[19:50:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:50:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:50:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[19:50:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[19:50:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[19:50:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[19:50:28] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[19:50:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[19:50:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:50:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
for all islands

**Comment by leon37921** [comment] 2024-08-26 20:30
sorry, I forgot the syncupgrades cmd
```
[22:27:32] [Server thread/INFO]: skrilly4 issued server command: /sky admin syncupgrades skrilly4
[22:27:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'sky admin syncupgrades skrilly4' in com.bgsoftware.superiorskyblock.commands.CommandsManagerImpl$PluginCommand(sky)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-435]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-435]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-435]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException

```

**Comment by leon37921** [comment] 2024-08-30 21:12
Looks like its fixed now. 
No errors, and the border is still correct after server-restarts.
🎉

**Comment by OmerBenGera** [comment] 2024-08-31 07:58
Amazing, glad it was finally resolved :)
If you have any issues, make sure you report them by opening new issues.

**Closed by OmerBenGera** 2024-08-31 07:58 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
