### ISSUE TITLE
build 258 breaks server [Advanced SWM]

### ISSUE THREAD

**Issue by neyti444** [BG-Software-LLC/SuperiorSkyblock2#2182] opened 2024-07-29 12:20 UTC
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.20.6-16004-develop@7c72925 (2024-05-28T19:17:31Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 28 version(s) behind
Download the new version from our Discord: https://discord.gg/YevvsMa
Previous version: 1.20.6-147-e41d44f (MC: 1.20.6)

### Plugin's Version

build 258

### Describe the bug

Island won't load

### To Reproduce

install the latest aswm and the newest version (or just build 258, because everything works on 257)

### Additional Information

[text.txt](https://github.com/user-attachments/files/16412835/text.txt)

**Comment by OmerBenGera** [comment] 2024-07-29 17:23
Duplicate of #2163

**Closed by OmerBenGera** 2024-07-29 17:23 UTC
Labels: Pending
