### ISSUE TITLE
how can i fix Cannot invoke "javax.script.ScriptEngine.eval(String, javax.script.Bindings)"?

### ISSUE THREAD

**Issue by filiperose** [BG-Software-LLC/SuperiorSkyblock2#252] opened 2021-05-13 07:29 UTC
[14:26:22] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String, javax.script.Bindings)" because "com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.engine" is null
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.convertValueToLevel(BlockValuesHandler.java:179)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.convertValuesToLevels(BlockValuesHandler.java:241)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.handlers.BlockValuesHandler.loadData(BlockValuesHandler.java:44)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:371)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:174)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:26:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:371)
[14:26:22] [Server thread/WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:174)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[14:26:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:26:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493)
[14:26:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407)
[14:26:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:555)
[14:26:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
[14:26:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
[14:26:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[14:26:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by OmerBenGera** [comment] 2021-05-14 10:09
Java version?

**Comment by filiperose** [comment] 2021-05-14 11:23
it's java 16

**Comment by OmerBenGera** [comment] 2021-05-14 11:35
Duplicate of #109

**Closed by OmerBenGera** 2021-05-14 11:35 UTC
Labels: Bug Report, Further Investigation
