### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#817] opened 2022-01-03 18:35 UTC
### Minecraft's Version

Checking version, please wait...
This server is running Paper version git-Paper-398 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 244b392 on ver/1.17.1)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-"08dd6c7" (MC: 1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8.3.421
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

This error: https://pastebin.com/9VYseeGh shows in console when starting the server and whenever a player joins the server.

### To Reproduce

I'm pretty sure this doesn't happen regularly, its just my databases fault

### Additional Information

Error: https://pastebin.com/9VYseeGh

**Comment by OmerBenGera** [comment] 2022-01-04 08:05
Send me the entire logs file please.
When an error of SQL is thrown, another message should be printed before it that shows the query that was meant to be queued, which is not in the stack trace you uploaded.

**Comment by DuneSciFye** [comment] 2022-01-11 21:41
https://pastebin.com/Ts1eGGDK

**Comment by OmerBenGera** [comment] 2022-01-13 18:51
Why is your players table missing the `uuid` column?

**Comment by DuneSciFye** [comment] 2022-01-13 23:41
I have no clue, I just set up the mysql database and put in the login information. Should I reset it? Or manually add it?

**Comment by OmerBenGera** [comment] 2022-01-14 09:41
> I have no clue, I just set up the mysql database and put in the login information. Should I reset it? Or manually add it?

Check if the `players` table is actually missing the `uuid` column or not.
If you don't have any important data anyways, then I'd say just to reset it.

**Comment by DuneSciFye** [comment] 2022-01-14 20:39
It does have the uuid column. 
![image](https://user-images.githubusercontent.com/65089425/149582105-56be8c88-67f9-4cf9-8846-5b2b5e4f0a29.png)
Since I don't have any important data, should I just reset it now? Or would you like to investigate

**Comment by DuneSciFye** [comment] 2022-01-15 00:52
I just deleted everything, and it still gives me the error in console

**Comment by OmerBenGera** [comment] 2022-01-15 07:09
> It does have the uuid column. ![image](https://user-images.githubusercontent.com/65089425/149582105-56be8c88-67f9-4cf9-8846-5b2b5e4f0a29.png) Since I don't have any important data, should I just reset it now? Or would you like to investigate

This is not a table of SSB.
I think you have another plugin with the same table names  that use the same database.
I recommend adding a custom prefix for tables to the SSB's config so they will be different.

**Comment by DuneSciFye** [comment] 2022-01-15 16:03
I just added SS2 as the prefix, deleted everything in the database currently, and restarted server. I still got this issue in console when I joined: https://pastebin.com/P5tW4FbV

Here is the SS2players table:
![image](https://user-images.githubusercontent.com/65089425/149628744-84648401-0a7f-4bbe-ad41-e982a3964255.png)

**Comment by DuneSciFye** [comment] 2022-01-15 16:39
I have another error in console:
![image](https://user-images.githubusercontent.com/65089425/149629923-75533858-e2cd-4fa0-909b-688eb7908031.png)

My full log is here: https://pastebin.com/4XZtQbG3

**Comment by OmerBenGera** [comment] 2022-01-15 17:21
> I just added SS2 as the prefix, deleted everything in the database currently, and restarted server. I still got this issue in console when I joined: https://pastebin.com/P5tW4FbV
> 
> Here is the SS2players table: ![image](https://user-images.githubusercontent.com/65089425/149628744-84648401-0a7f-4bbe-ad41-e982a3964255.png)

This error is related to ShopGUIPlus.

**Comment by OmerBenGera** [comment] 2022-01-15 17:22
> I have another error in console: ![image](https://user-images.githubusercontent.com/65089425/149629923-75533858-e2cd-4fa0-909b-688eb7908031.png)
> 
> My full log is here: https://pastebin.com/4XZtQbG3

And this one comes from SWM's hook.

**Comment by OmerBenGera** [comment] 2022-01-15 17:22
Closing this, seems to be fixed :)

**Closed by OmerBenGera** 2022-01-15 17:22 UTC
Labels: 📝 Missing information, ❌ Unconfirmed

**Comment by DuneSciFye** [comment] 2022-01-16 15:55
For the error related to SWM's hook, I asked in their discord server and they told me this: 
![image](https://user-images.githubusercontent.com/65089425/149667383-8579669c-74e7-44a7-b525-47a01cdbec40.png)

**Comment by OmerBenGera** [comment] 2022-01-16 19:30
> For the error related to SWM's hook, I asked in their discord server and they told me this: ![image](https://user-images.githubusercontent.com/65089425/149667383-8579669c-74e7-44a7-b525-47a01cdbec40.png)

The issue is with the addon you use, not SSB or ASWM itself.
