### ISSUE TITLE
Performance issue with upgrades

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#747] opened 2021-11-21 21:17 UTC
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b376

### Session Logs

can't upload it, way too heavy

### Describe the bug

Since I enabled upgrades, superior take 2-3x more % in spark.
https://spark.lucko.me/XE1ZYbUxPX

I have to enable it for limits to work  ( like told on the issue https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/587 )
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/587#issuecomment-949583082

### To Reproduce

Disable upgrades on a living server and do a spark
Then enable uprades and do a spark

Without upgrades enabled : 
https://spark.lucko.me/zEPs6v7WKV
With them enable : 
https://spark.lucko.me/XE1ZYbUxPX

But I don't use any upgrade at all.

**Comment by OmerBenGera** [comment] 2021-11-26 08:21
It looks fine for me, do you see anything particular that you think causes more lag in the spark?

**Comment by WarnDa** [comment] 2021-11-26 13:43
On this spark :
https://spark.lucko.me/P5Z3Rw9YuN

When upgrades are enable, a new function 
> com.bgsoftware.common.executors.WorkerExecutor.run()

Appear and make superior consome 3x more than with upgrades disable :/

**Comment by WarnDa** [comment] 2021-11-26 13:46
And with upgrades disabled : 
![Screenshot_60](https://user-images.githubusercontent.com/31826333/143590413-db12a712-1e5b-46e2-bc87-c4c0c6e64779.png)

**Comment by OmerBenGera** [comment] 2021-11-26 13:48
The worker you mentioned is for loading chunks - nothing that can be optimized on SSB's side.

**Comment by WarnDa** [comment] 2021-11-26 13:50
But is it possible to enable block/entity limit without enabling the worker ?

I don't use upgrade at all, but as mentionned in https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/587 I need to enable upgrades to use entity and block limit.

**Comment by OmerBenGera** [comment] 2021-11-26 13:53
Run `/is admin debug Action: Chunk Load Attempt`, let me know if you see more of these messages when upgrades are enabled than when they are disabled.

**Comment by WarnDa** [comment] 2021-11-26 13:55
WTF ??
I just ran the command and it restarted my server with all players online...

I'll try on my test server

**Comment by OmerBenGera** [comment] 2021-11-26 13:57
Why was the server restarted?
Look for errors or something

**Comment by WarnDa** [comment] 2021-11-26 14:02
Logs since I enabled the debug : 
https://paste.helpch.at/ifetujoxuz.sql

It loaded sooo much chunk per seconds

**Comment by OmerBenGera** [comment] 2021-11-26 14:10
> Logs since I enabled the debug : https://paste.helpch.at/ifetujoxuz.sql
> 
> It loaded sooo much chunk per seconds

Upload it to pastebin please, this website can't handle the text

**Comment by WarnDa** [comment] 2021-11-26 14:12
Too heavy for pastebin or hastebin *

**Comment by OmerBenGera** [comment] 2021-11-26 14:25
I don't know why every debug message started to be printed to screen tbh
about the chunk-load attempt, seems like there are many of these. Does the amount of them actually reduce after disabling upgrades?

**Comment by WarnDa** [comment] 2021-11-26 14:35
> I don't know why every debug message started to be printed to screen tbh about the chunk-load attempt, seems like there are many of these. Does the amount of them actually reduce after disabling upgrades?

I tried alone on my test server, I don't get any chunk loading attempt, I'll try to do more tests and see

**Comment by WarnDa** [comment] 2021-11-26 14:41
So : 

With upgrades enable : 
- It loads all my islands chunks everytime I spawn a mob :
> >.... [15:38:22 INFO]: WarnD issued server command: /spawnmob minecart
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 36, -2
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 36, -1
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 36, 0
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 37, -2
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 37, -1
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 37, 0
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 38, -1
>.... [15:38:22 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Chunk Load Attempt, Chunk: SuperiorWorld, 38, 0

- It doesn't load chunk when I place blocks (but limit work)

And with upgrade disabled : 
- I got no chunk loading attempt on anything (mob or blocks)

**Comment by OmerBenGera** [comment] 2021-11-26 19:32
It's probably tries to load the chunks because of the entity limit feature.
I will look into that, maybe it actually causes more lag.

**Comment by OmerBenGera** [comment] 2021-12-03 09:57
There's no such I can do, as it just loads the chunks and count the amount of entities in the chunk for the limit.
It shouldn't really lag your server, however if you believe it really does, lmk by commenting here.
For now, I am closing this.

**Closed by OmerBenGera** 2021-12-03 09:57 UTC
Labels: ❌ Unconfirmed

**Comment by WarnDa** [comment] 2021-12-03 13:04
There is no other way than loading ALL island chunk EVERYTIME a mob spawn ?
It's a bit heavy for the server yes, even if it "doesn't lag".
It takes up to 5-7% of server's performances in spark.

It wouldn't possible to do it differently, I explain : 
- Do your own mob count.

As when a mob spawn, you know it spawns, so you get a "counter" that add +1 to this mob, and as you already check for mob kill, you remove -1 to the mob count when a mob is killed.
And you can recalc entities every 2-3mn.

If people get 7 mobs instead of 5, that's not an issue. It's just to avoid player getting 50 mobs instead of 5.
So a "soft-limit" (as an option, and keep the current hard limit for those who want) would be the best idea !

**Comment by OmerBenGera** [comment] 2021-12-03 13:09
It doesn't load the chunks, as they are already loaded when a mob spawns.
About the "dynamic counting for mobs" - it's not really possible, as it's not possible to actually track when a mob is removed from the world, or if it goes through portals etc.
In other words, it has options to go out of the island and the plugin will not be able to target it due to lacking of events with Bukkit API.

**Comment by WarnDa** [comment] 2021-12-03 13:12
> It doesn't load the chunks, as they are already loaded when a mob spawns.

I got 1001x1001 islands, and when you kill 1 mob, it loads all the islands to count all mobs right ?

> About the "dynamic counting for mobs" - it's not really possible, as it's not possible to actually track when a mob is removed from the world, or if it goes through portals etc.

That's why I called it "soft limit" and it wouldn't be 100% accurate, but it would still limit people, on my server mobs are mainly used in farms, so they can't go through/outside borders. Only player and clearlag (that is hooked into wildstacker, so it's wildstacker which kill the mobs) can kill mobs.


I know that currently you need to do 1.18 support, but then if you got times I can really pay you for this feature, that would save 5-6% of server performances for my case.

Thanks :)

**Comment by OmerBenGera** [comment] 2021-12-03 13:42
> > It doesn't load the chunks, as they are already loaded when a mob spawns.
> 
> I got 1001x1001 islands, and when you kill 1 mob, it loads all the islands to count all mobs right ?
> 
> > About the "dynamic counting for mobs" - it's not really possible, as it's not possible to actually track when a mob is removed from the world, or if it goes through portals etc.
> 
> That's why I called it "soft limit" and it wouldn't be 100% accurate, but it would still limit people, on my server mobs are mainly used in farms, so they can't go through/outside borders. Only player and clearlag (that is hooked into wildstacker, so it's wildstacker which kill the mobs) can kill mobs.
> 
> I know that currently you need to do 1.18 support, but then if you got times I can really pay you for this feature, that would save 5-6% of server performances for my case.
> 
> Thanks :)

The plugin only loads chunks that are not empty (aka have blocks in them), so it doesn't really matter if you have a 1000x1000 island, what really matters is how many chunks you have with blocks in them. And again, when the mob is spawned, the chunks are already loaded anyways, so it doesn't really load any chunks.
I will think about implementing it (for free, I am not taking money).

**Comment by WarnDa** [comment] 2021-12-11 13:25
There is really a big big performance issue when upgrades are ON !

Since 3 days I had them OFF, and I had 25-30 MSPT with 90 players,
Today I have them ON, and I have 45-50 MSPT, still with 90 players,

So yes it has a big performance impact.

With upgrades (so limits) OFF: 
https://spark.lucko.me/FIeNYltWNE
<img width="452" alt="Screenshot_215" src="https://user-images.githubusercontent.com/31826333/145678238-694b31e3-e757-4ca3-8d1a-70f11e81f02e.png">
26mspt with 97 players

When ON :
https://spark.lucko.me/06BSQIeXsJ
![Screenshot_247](https://user-images.githubusercontent.com/31826333/145678248-1e75c5e9-07e0-4962-854a-d900832649c3.png)
50mspt with 80 players

**Comment by OmerBenGera** [comment] 2021-12-11 13:44
> There is really a big big performance issue when upgrades are ON !
> 
> Since 3 days I had them OFF, and I had 25-35 MSPT with 90 players, Today I have them ON, and I have 40-50 MSPT, still with 90 players,
> 
> So yes it has a big performance impact.
> 
> With upgrades (so limits) OFF: https://spark.lucko.me/FIeNYltWNE <img alt="Screenshot_215" width="452" src="https://user-images.githubusercontent.com/31826333/145678238-694b31e3-e757-4ca3-8d1a-70f11e81f02e.png"> 26mspt with 97 players
> 
> When ON : https://spark.lucko.me/06BSQIeXsJ ![Screenshot_247](https://user-images.githubusercontent.com/31826333/145678248-1e75c5e9-07e0-4962-854a-d900832649c3.png) 50mspt with 80 players

we already discussed what the issue is.
If your server can't handle SSB's entity limits and the way it works, just disable it.
