### ISSUE TITLE
Player crash on /is settings

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#890] opened 2022-01-27 21:14 UTC
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b494

### Describe the bug

Player sometimes crash when they do "/is settings"
Error they got : 
![unknown (10)](https://user-images.githubusercontent.com/31826333/151444108-e9410a45-f092-4549-8491-4024babeb6ff.png)

### To Reproduce

Idk

### Additional Information

<img width="1002" alt="Screenshot_362" src="https://user-images.githubusercontent.com/31826333/151444557-87558c77-e987-45b2-8fa8-308c76914991.png">
I'll send you the menu on discord

**Comment by OmerBenGera** [comment] 2022-01-27 21:26
As I told to WarnD, the issue is probably because of the amount of data that is sent when players open the menu.
This happens due to too many data with the items themselves - long lores that use unicode characters can cause the issue.
I adviced him to reduce the amount of data that is sent, and we will see if it helps or not.

**Comment by WarnDa** [comment] 2022-01-27 21:36
It worked perfectly, a single player changed "natural_monster_spawn", and now everyone that try to open the gui crash.

I'll try to find more informations

**Comment by OmerBenGera** [comment] 2022-01-27 21:54
I think I found what caused it.
Let me know if it's fixed in latest dev build.

**Comment by WarnDa** [comment] 2022-01-29 23:38
Fixed

**Closed** 2022-01-30 18:20 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
