### ISSUE TITLE
Island Creation not working

### ISSUE THREAD

**Issue by elkoyofficial** [BG-Software-LLC/SuperiorSkyblock2#1692] opened 2023-04-16 17:57 UTC
### Minecraft's Version

purpur-1962 (1.19.4)

### Plugin's Version

SuperiorSkyblock2-2023.1-b9. [Dev Build]

### Describe the bug

Everytime I change the config for superiorskyblock and change the world, it will not let you create an island. 

It says processes the request but doesn't actually generate anything. There's no errors.

### To Reproduce

Download purpur-1962 (1.19.4) & SuperiorSkyblock2-2023.1-b9. [Dev Build].

Change the world in the config, restart and try to generate a world.

**Comment by totKing** [comment] 2023-04-24 18:16
https://mclo.gs/jDEKt2q

**Comment by WarnDa** [comment] 2023-04-26 06:25
Reason here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1686#issuecomment-1509855309

**Comment by OmerBenGera** [comment] 2023-04-28 08:06
Duplicate of #1686

**Comment by OmerBenGera** [comment] 2023-04-28 08:07
Update the plugin to recent dev build, this error was fixed already.

**Closed by OmerBenGera** 2023-04-28 08:07 UTC
Labels: Pending
