### ISSUE TITLE
Crops dupe bug

### ISSUE THREAD

**Issue by OGreenC** [BG-Software-LLC/SuperiorSkyblock2#1672] opened 2023-04-06 13:47 UTC
### Minecraft's Version

Paper-411 MC. 1.17.1

### Plugin's Version

2022.9-b977

### Describe the bug

Players that are not a member of a island, is able to dupe crops, by placing a bed above the crop. (The bed placement is then immediately canceled by island protection of cause).

When doing this, in a totally dark environment, items will drop from the crop, but the crop will not be destroyed (please see below video)

I tried testing the exact same thing in worldguard, and it seems as if the problem also persists here. I was however able to find a plugin which fixes this problem for worldguard (also, they have posted a nice video of the scenario)
https://www.spigotmc.org/resources/wgbeddupefix-worldguard-bed-dupe-fix.107481/ 

What I would imagine happening, is that the crop is being updated, and vanilla behaviour kicks in, attempting to remove the crop as per. default behaviour when there's no light on a crop.

### To Reproduce

Build a small encapsulated room on a island, and place a tiled dirt, with a crop above (One might have to do this while there is actually light, but the light can be removed afterwards)

Teleport to the island as another player who is not a part of the island, and attempt to place a bed on top of the crop.

See video below:
https://www.youtube.com/watch?v=OZ99W8jlnfY&t=3s&ab_channel=ONIONs

*The particular video is taken from the above mentioned Spigot plugin for fixing the problem for worldguard, but as it is visually the exact same thing that is happening, I thought this would surffice.*

https://medal.tv/games/minecraft/clips/13deKo0Hq3YblQ/SR1mWy38vaZb?invite=cr-MSxkd04sNjY2MTcyNCw
*Or above, which I received from one of our players.*

**Comment by OmerBenGera** [comment] 2023-04-07 07:49
Apparently it was already been reported here: #1600 
However, their solution is a third-party one, as it's technically not a bug of SSB.

However, I decided to implement a built-in patch into the plugin so you don't need to use more plugins.
This is also been reported to Spigot: https://hub.spigotmc.org/jira/browse/SPIGOT-7315
Hopefully it will be fixed soon :)

**Closed by OmerBenGera** 2023-04-07 07:49 UTC
Labels: ✔️ Confirmed
