### ISSUE TITLE
superiorskyblock2 error in /is level calculation

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#411] opened 2021-07-31 17:30 UTC
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

SuperiorSkyblock2-b209.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

when a player types /is level the island value disappears until he gets new blocks on the ground see the 29k image it went to 0 when i gave /is level.

![2021-07-31_14 26 46](https://user-images.githubusercontent.com/67756407/127747921-107f4304-5c83-47ac-8679-7e7afe8dd52c.png)

![2021-07-31_14 26 55](https://user-images.githubusercontent.com/67756407/127747924-2096c5e4-86a0-43c3-a3e4-665e4553b5b2.png)

this happens with version 209 of superiorskyblock.

### To Reproduce

/is level

**Comment by brasilcraft54** [comment] 2021-07-31 17:36
this error is appearing on the console and the player is losing access to the island he could not put or move on the island.


![9000](https://user-images.githubusercontent.com/67756407/127748044-2d2946e3-4324-4bc2-a694-82d3f8d6c463.PNG)

**Comment by brasilcraft54** [comment] 2021-07-31 17:44
![image0](https://user-images.githubusercontent.com/67756407/127748231-2d730972-b634-42bb-a6ca-2084f4154b08.jpg)
this message appears.

**Comment by Skizzles** [comment] 2021-07-31 20:30
Can confirm the island level resetting.

**Comment by brasilcraft54** [comment] 2021-08-01 14:49
> Can confirm the island level resetting.

it does not reset it just goes to 0 but when you put more blocks it goes back to normal level, but if you type /is level, you lose access to the island it is calculating infinitely.

**Comment by nivcoo** [comment] 2021-08-01 16:44
I can confirm this bug, i have back my version to 203

**Comment by OmerBenGera** [comment] 2021-08-01 20:38
Revert back for the time being.

**Comment by nivcoo** [comment] 2021-08-02 00:17
> Revert back for the time being.

Yes but the previous version has bug with is missions

**Comment by OmerBenGera** [comment] 2021-08-02 09:43
> > Revert back for the time being.
> 
> Yes but the previous version has bug with is missions

Ok.

**Comment by OmerBenGera** [comment] 2021-08-02 09:45
> > > Revert back for the time being.
> > 
> > 
> > Yes but the previous version has bug with is missions
> 
> Ok.



> > Revert back for the time being.
> 
> Yes but the previous version has bug with is missions

I know, however I am not at home and I cant deal with it. You can make a PR that I will accept and it will be fixed faster, otherwise I advice to revert to an older version or just disable /is level for now

**Comment by nivcoo** [comment] 2021-08-04 02:05
I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded

**Comment by OmerBenGera** [comment] 2021-08-04 09:38
> I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded

The error is comes from thread-safety issue in CompletableFutureList.

**Comment by nivcoo** [comment] 2021-08-04 09:54
> > I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded
> 
> The error is comes from thread-safety issue in CompletableFutureList.


I spent several hours yesterday debugging all this but as I don't know the CompletableFuture at all, I tried to find out when it crashes. 
All the blocks are retrieved and their number too, but the onFinish of calculateChunks is not called and therefore does not return anything

**Comment by OmerBenGera** [comment] 2021-08-05 09:42
> > > I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded
> > 
> > 
> > The error is comes from thread-safety issue in CompletableFutureList.
> 
> I spent several hours yesterday debugging all this but as I don't know the CompletableFuture at all, I tried to find out when it crashes.
> All the blocks are retrieved and their number too, but the onFinish of calculateChunks is not called and therefore does not return anything

CompleteableFutureList is an ArrayList that I implemented a year ago, which holds CompleteableFuture objects and it knows to iterate through them and run a specific runnable when they finish. It didnt do any problems until latest versions, as they are more efficient and it makes the iteration on the list and adding new items to the list happening together, causing this error to occur.

**Comment by nivcoo** [comment] 2021-08-05 11:08
> > > > I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded
> > > 
> > > 
> > > The error is comes from thread-safety issue in CompletableFutureList.
> > 
> > 
> > I spent several hours yesterday debugging all this but as I don't know the CompletableFuture at all, I tried to find out when it crashes.
> > All the blocks are retrieved and their number too, but the onFinish of calculateChunks is not called and therefore does not return anything
> 
> CompleteableFutureList is an ArrayList that I implemented a year ago, which holds CompleteableFuture objects and it knows to iterate through them and run a specific runnable when they finish. It didnt do any problems until latest versions, as they are more efficient and it makes the iteration on the list and adding new items to the list happening together, causing this error to occur.

Do you know how to resolve that ? Or a track ? 
So I can try to settle it on my side and make a pull request. Because there I tried in vain

**Comment by OmerBenGera** [comment] 2021-08-05 15:33
> > > > > I have tried looking for the origin of the bug and would say it is only present when there is no snapshot and I think it is coming from the chunksCoords variable (I'm not sure). I don't have the impression that it contains the information it needs so the OnFinish is never called and therefore no block is loaded
> > > > 
> > > > 
> > > > The error is comes from thread-safety issue in CompletableFutureList.
> > > 
> > > 
> > > I spent several hours yesterday debugging all this but as I don't know the CompletableFuture at all, I tried to find out when it crashes.
> > > All the blocks are retrieved and their number too, but the onFinish of calculateChunks is not called and therefore does not return anything
> > 
> > 
> > CompleteableFutureList is an ArrayList that I implemented a year ago, which holds CompleteableFuture objects and it knows to iterate through them and run a specific runnable when they finish. It didnt do any problems until latest versions, as they are more efficient and it makes the iteration on the list and adding new items to the list happening together, causing this error to occur.
> 
> Do you know how to resolve that ? Or a track ?
> So I can try to settle it on my side and make a pull request. Because there I tried in vain

If you dont know how to fix it, then you are probably not the person that should fix it, as these are issues with threads that might lead to deadlock (server freeze, crash)  if they are not done correctly

**Comment by Reese14** [comment] 2021-08-08 17:45
> Revert back for the time being.

What version would you recommend using, without going 'too far' back?

**Comment by nivcoo** [comment] 2021-08-08 17:46
I said build 203 because after that he change the method

**Comment by Reese14** [comment] 2021-08-08 17:50
Okay, will give it a try. Thanks!

**Comment by OmerBenGera** [comment] 2021-08-13 11:06
Fixed in latest dev build

**Closed by OmerBenGera** 2021-08-13 11:06 UTC
Labels: Bug Report, Confirmed

**Comment by nivcoo** [comment] 2021-08-13 11:58
Hello, the update doesn't works : https://pics.revolis.fr/2021-08/13/13-57_ibnQ.png when i do /is level i have always this message, also with is admin recalc username

**Comment by OmerBenGera** [comment] 2021-08-13 12:25
> 
> 
> Hello, the update doesn't works : https://pics.revolis.fr/2021-08/13/13-57_ibnQ.png when i do /is level i have always this message, also with is admin recalc username

Your island is being recalculated, you can't calculate the island more than one time.
If there are errors when the calculation task occurs, then paste them here, otherwise - you need to be patient until the calculation task is done until you can run it again.

**Comment by nivcoo** [comment] 2021-08-13 12:38
> > Hello, the update doesn't works : https://pics.revolis.fr/2021-08/13/13-57_ibnQ.png when i do /is level i have always this message, also with is admin recalc username
> 
> Your island is being recalculated, you can't calculate the island more than one time.
> If there are errors when the calculation task occurs, then paste them here, otherwise - you need to be patient until the calculation task is done until you can run it again.

No it's not "normal", i have this issue after start of server and i have check, i haven't error in console. I have also this error after 30 minutes, i can't calculate my level

**Comment by nivcoo** [comment] 2021-08-13 12:40
It's not just a matter of being patient since I can in no way calculate the level/worth

**Comment by OmerBenGera** [comment] 2021-08-13 13:21
> 
> 
> > > Hello, the update doesn't works : https://pics.revolis.fr/2021-08/13/13-57_ibnQ.png when i do /is level i have always this message, also with is admin recalc username
> > 
> > 
> > Your island is being recalculated, you can't calculate the island more than one time.
> > If there are errors when the calculation task occurs, then paste them here, otherwise - you need to be patient until the calculation task is done until you can run it again.
> 
> No it's not "normal", i have this issue after start of server and i have check, i haven't error in console. I have also this error after 30 minutes, i can't calculate my level

Open a new issue then
